export type AccentColorId = 'purple' | 'blue' | 'indigo' | 'teal' | 'rose' | 'orange' | 'amber' | 'slate';

type AccentPaletteEntry = {
  label: string;
  swatch: string;
  light: Record<string, string>;
  dark: Record<string, string>;
};

export const ACCENT_PALETTE: Record<AccentColorId, AccentPaletteEntry> = {
  purple: {
    label: 'Purple',
    swatch: '#8b5cf6',
    light: {
      '--color-primary': '#8b5cf6',
      '--color-primary-hover': '#7c3aed',
      '--color-primary-foreground': '#ffffff',
      '--color-ring': '#a78bfa',
      '--color-secondary': '#eef2ff',
      '--color-secondary-hover': '#ede9fe',
      '--color-secondary-foreground': '#7c3aed',
      '--color-link': '#7c3aed',
      '--color-link-hover': '#6d28d9',
    },
    dark: {
      '--color-primary': '#8b5cf6',
      '--color-primary-hover': '#a78bfa',
      '--color-primary-foreground': '#ffffff',
      '--color-ring': '#a78bfa',
      '--color-secondary': '#4c1d95',
      '--color-secondary-hover': '#5b21b6',
      '--color-secondary-foreground': '#ffffff',
      '--color-link': '#a78bfa',
      '--color-link-hover': '#c4b5fd',
    },
  },
  blue: {
    label: 'Blue',
    swatch: '#3b82f6',
    light: {
      '--color-primary': '#2563eb',
      '--color-primary-hover': '#1d4ed8',
      '--color-primary-foreground': '#ffffff',
      '--color-ring': '#60a5fa',
      '--color-secondary': '#eff6ff',
      '--color-secondary-hover': '#dbeafe',
      '--color-secondary-foreground': '#1d4ed8',
      '--color-link': '#1d4ed8',
      '--color-link-hover': '#1e40af',
    },
    dark: {
      '--color-primary': '#60a5fa',
      '--color-primary-hover': '#93c5fd',
      '--color-primary-foreground': '#0f172a',
      '--color-ring': '#93c5fd',
      '--color-secondary': '#1e3a8a',
      '--color-secondary-hover': '#1e40af',
      '--color-secondary-foreground': '#ffffff',
      '--color-link': '#93c5fd',
      '--color-link-hover': '#bfdbfe',
    },
  },
  indigo: {
    label: 'Indigo',
    swatch: '#6366f1',
    light: {
      '--color-primary': '#4f46e5',
      '--color-primary-hover': '#4338ca',
      '--color-primary-foreground': '#ffffff',
      '--color-ring': '#818cf8',
      '--color-secondary': '#eef2ff',
      '--color-secondary-hover': '#e0e7ff',
      '--color-secondary-foreground': '#4338ca',
      '--color-link': '#4338ca',
      '--color-link-hover': '#3730a3',
    },
    dark: {
      '--color-primary': '#818cf8',
      '--color-primary-hover': '#a5b4fc',
      '--color-primary-foreground': '#0f172a',
      '--color-ring': '#a5b4fc',
      '--color-secondary': '#312e81',
      '--color-secondary-hover': '#3730a3',
      '--color-secondary-foreground': '#eef2ff',
      '--color-link': '#a5b4fc',
      '--color-link-hover': '#c7d2fe',
    },
  },
  teal: {
    label: 'Teal',
    swatch: '#14b8a6',
    light: {
      '--color-primary': '#0f766e',
      '--color-primary-hover': '#115e59',
      '--color-primary-foreground': '#ffffff',
      '--color-ring': '#2dd4bf',
      '--color-secondary': '#f0fdfa',
      '--color-secondary-hover': '#ccfbf1',
      '--color-secondary-foreground': '#115e59',
      '--color-link': '#0f766e',
      '--color-link-hover': '#115e59',
    },
    dark: {
      '--color-primary': '#2dd4bf',
      '--color-primary-hover': '#5eead4',
      '--color-primary-foreground': '#0f172a',
      '--color-ring': '#5eead4',
      '--color-secondary': '#134e4a',
      '--color-secondary-hover': '#0f766e',
      '--color-secondary-foreground': '#ccfbf1',
      '--color-link': '#5eead4',
      '--color-link-hover': '#99f6e4',
    },
  },
  rose: {
    label: 'Rose',
    swatch: '#e11d48',
    light: {
      '--color-primary': '#e11d48',
      '--color-primary-hover': '#be123c',
      '--color-primary-foreground': '#ffffff',
      '--color-ring': '#fb7185',
      '--color-secondary': '#fff1f2',
      '--color-secondary-hover': '#ffe4e6',
      '--color-secondary-foreground': '#be123c',
      '--color-link': '#be123c',
      '--color-link-hover': '#9f1239',
    },
    dark: {
      '--color-primary': '#fb7185',
      '--color-primary-hover': '#fda4af',
      '--color-primary-foreground': '#0f172a',
      '--color-ring': '#fda4af',
      '--color-secondary': '#881337',
      '--color-secondary-hover': '#9f1239',
      '--color-secondary-foreground': '#ffe4e6',
      '--color-link': '#fda4af',
      '--color-link-hover': '#fecdd3',
    },
  },
  orange: {
    label: 'Orange',
    swatch: '#ea580c',
    light: {
      '--color-primary': '#c2410c',
      '--color-primary-hover': '#9a3412',
      '--color-primary-foreground': '#ffffff',
      '--color-ring': '#fb923c',
      '--color-secondary': '#fff7ed',
      '--color-secondary-hover': '#ffedd5',
      '--color-secondary-foreground': '#9a3412',
      '--color-link': '#c2410c',
      '--color-link-hover': '#9a3412',
    },
    dark: {
      '--color-primary': '#fb923c',
      '--color-primary-hover': '#fdba74',
      '--color-primary-foreground': '#0f172a',
      '--color-ring': '#fdba74',
      '--color-secondary': '#7c2d12',
      '--color-secondary-hover': '#9a3412',
      '--color-secondary-foreground': '#ffedd5',
      '--color-link': '#fdba74',
      '--color-link-hover': '#fed7aa',
    },
  },
  amber: {
    label: 'Amber',
    swatch: '#d97706',
    light: {
      '--color-primary': '#b45309',
      '--color-primary-hover': '#92400e',
      '--color-primary-foreground': '#ffffff',
      '--color-ring': '#fbbf24',
      '--color-secondary': '#fffbeb',
      '--color-secondary-hover': '#fef3c7',
      '--color-secondary-foreground': '#92400e',
      '--color-link': '#b45309',
      '--color-link-hover': '#92400e',
    },
    dark: {
      '--color-primary': '#fbbf24',
      '--color-primary-hover': '#fcd34d',
      '--color-primary-foreground': '#0f172a',
      '--color-ring': '#fcd34d',
      '--color-secondary': '#78350f',
      '--color-secondary-hover': '#92400e',
      '--color-secondary-foreground': '#fef3c7',
      '--color-link': '#fcd34d',
      '--color-link-hover': '#fde68a',
    },
  },
  slate: {
    label: 'Slate',
    swatch: '#64748b',
    light: {
      '--color-primary': '#475569',
      '--color-primary-hover': '#334155',
      '--color-primary-foreground': '#ffffff',
      '--color-ring': '#94a3b8',
      '--color-secondary': '#f8fafc',
      '--color-secondary-hover': '#f1f5f9',
      '--color-secondary-foreground': '#334155',
      '--color-link': '#475569',
      '--color-link-hover': '#334155',
    },
    dark: {
      '--color-primary': '#94a3b8',
      '--color-primary-hover': '#cbd5e1',
      '--color-primary-foreground': '#0f172a',
      '--color-ring': '#cbd5e1',
      '--color-secondary': '#1e293b',
      '--color-secondary-hover': '#334155',
      '--color-secondary-foreground': '#f1f5f9',
      '--color-link': '#cbd5e1',
      '--color-link-hover': '#e2e8f0',
    },
  },
};
