export default {
  extends: ['stylelint-config-standard', 'stylelint-config-clean-order'],
  ignoreFiles: ['dist/**', 'release/**', 'out/**', 'resources/**', 'src/renderer/styles/**/*.css'],
  rules: {
    'at-rule-no-unknown': [true, { ignoreAtRules: ['layer'] }],
    'selector-class-pattern': null,
    'color-function-notation': null,
    'color-function-alias-notation': null,
    'alpha-value-notation': null,
    'import-notation': null,
    'keyframes-name-pattern': null,
    'order/properties-order': null,
    'order/order': null,
    'rule-empty-line-before': null,
    'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['global'] }],
    'selector-pseudo-element-no-unknown': [true, { ignorePseudoElements: ['global'] }],
    'property-no-vendor-prefix': null,
    'value-keyword-case': null,
    'color-hex-length': null,
    'font-family-name-quotes': null,
    'font-family-no-duplicate-names': null,
    'no-descending-specificity': null,
    'no-duplicate-selectors': null,
    'shorthand-property-no-redundant-values': null,
    'declaration-property-value-no-unknown': null,
    'declaration-property-value-keyword-no-deprecated': null,
    'declaration-block-single-line-max-declarations': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'declaration-block-no-duplicate-properties': null,
    'declaration-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'comment-empty-line-before': null,
    'at-rule-empty-line-before': null,
    'media-feature-range-notation': null,
    'length-zero-no-unit': null
  }
};
