/**
 * Background Task Labels
 *
 * Utilities for deriving human-readable titles from background task session IDs.
 * Background tasks (meeting analysis, memory updates, automations) use prefixed
 * session IDs that encode the task type.
 */
import { classifySessionKind } from '@shared/sessionKind';

/** Curated labels for known automation system types */
const AUTOMATION_TYPE_LABELS: Record<string, string> = {
  'wins-learnings-uncover': 'Wins & learnings',
  'community-highlights': 'Community highlights',
  'calendar-sync': 'Calendar sync',
  'source-capture': 'Source capture',
  'transcript-analysis': 'Transcript analysis',
  'community-video-recs': 'Video picks',
};

/**
 * Humanize an automation system type slug.
 * Uses curated labels for known types, falls back to basic title-casing.
 *
 * @example humanizeAutomationType('wins-learnings-uncover') // "Wins & learnings"
 * @example humanizeAutomationType('custom-report')          // "Custom report"
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function humanizeAutomationType(typeSlug: string): string {
  if (AUTOMATION_TYPE_LABELS[typeSlug]) return AUTOMATION_TYPE_LABELS[typeSlug];
  if (UUID_RE.test(typeSlug)) return 'Automation';
  return typeSlug.replace(/[-_]+/g, ' ').replace(/^./, c => c.toUpperCase());
}

/**
 * Parse a background task type from a session ID prefix.
 *
 * Session ID formats:
 * - `meeting-analysis-{uuid}`
 * - `memory-update-{turnId}`
 * - `automation-{type}--{uuid}` (note the double-dash before uuid)
 *
 * @returns Human-readable label, or null if not a recognised background task
 */
export function parseBackgroundTaskType(sessionId: string): string | null {
  const sessionKind = classifySessionKind(sessionId);
  if (sessionKind === 'error-eval') {
    return 'Error evaluation';
  }
  if (sessionKind === 'meeting-analysis') {
    return 'Meeting analysis';
  }
  if (sessionKind === 'memory-update') {
    return 'Memory update';
  }
  if (sessionKind === 'meeting-qa') {
    return 'Meeting Q&A';
  }
  if (sessionKind === 'calendar-sync') {
    return 'Calendar sync';
  }
  if (sessionKind === 'use-case-discovery') {
    return 'Suggested';
  }
  if (sessionKind !== 'automation') {
    return null;
  }

  const match = /^automation-(.+?)(?:--|$)/.exec(sessionId);
  const typeSlug = match?.[1] ?? '';
  if (typeSlug) {
    return humanizeAutomationType(typeSlug);
  }
  return 'Automation';
}

/**
 * Short *category* badge label for the conversation sidebar, signalling that a
 * conversation was generated by Rebel (a background/agent run) rather than
 * started by the user. Distinct from `parseBackgroundTaskType`, which returns a
 * specific name (e.g. an automation's title) for the approvals drawer — here we
 * want a stable one-word category that pairs with the row's own title.
 *
 * Returns `null` for user-started conversations (`conversation`, `cli-chat`) and
 * for `meeting-companion` (which already carries its own video badge), so those
 * rows show no extra badge.
 *
 * @example sessionKindBadgeLabel('use-case-discovery-abc') // "Suggested"
 * @example sessionKindBadgeLabel('automation-wins--abc')   // "Automation"
 */
export function sessionKindBadgeLabel(sessionId: string): string | null {
  switch (classifySessionKind(sessionId)) {
    case 'automation':
    case 'automation-insight':
      return 'Automation';
    case 'use-case-discovery':
      return 'Suggested';
    case 'meeting-analysis':
      return 'Meeting';
    default:
      // conversation / cli-chat / meeting-companion + sidebar-hidden kinds
      // (memory-update, meeting-qa, error-eval, calendar-sync) → no badge.
      return null;
  }
}
