import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import inventory from './manifests/ui_component_token_inventory.json';
import manifest from './manifests/storybook_component_manifest.json';
import {
  STORYBOOK_STATUS_LANGUAGE,
  type StorybookStatusKey,
  type StorybookStatusPresentation,
} from './storybookStatusLanguage';

/**
 * FOX-3131 Stage 1 — the Registry renders the machine status enum
 * (`shared` / `app-pattern` / `missing`) using friendlier, browser-
 * facing labels. The machine values stay intact in the manifest and
 * JSON; this page just translates them for non-engineer readers.
 *
 * Status language is shared with `Overview.stories.tsx` through
 * `storybookStatusLanguage.ts` so the browser-facing labels stay in
 * sync without expanding the manifest schema.
 */
type ManifestStatus = StorybookStatusKey;
type StatusPresentation = StorybookStatusPresentation;

const STATUS_PRESENTATION: Record<ManifestStatus, StatusPresentation> = STORYBOOK_STATUS_LANGUAGE;

const meta = {
  title: 'Design System/Registry',
  parameters: {
    layout: 'fullscreen',
    controls: { disable: true },
    docs: {
      description: {
        component:
          'Autogenerated inventory sourced from the codebase. This page is regenerated whenever Storybook starts or builds via `prestorybook` / `prebuild-storybook`.',
      },
    },
  },
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

const ORDERED_STATUSES: ManifestStatus[] = ['shared', 'app-pattern', 'missing'];
const STORY_TITLE_TO_EXPORT_NAME: Record<string, string> = {
  'Design System/Atoms/Buttons': 'Gallery',
  'Design System/Atoms/Buttons/Icon Button': 'CurrentReality',
  'Design System/Atoms/Icon Tile': 'Gallery',
  'Design System/Atoms/Inputs': 'Gallery',
  'Design System/Atoms/Inputs/Select Family': 'CurrentReality',
  'Design System/Atoms/Tabs': 'Gallery',
  'Design System/Atoms/Toggles': 'CurrentReality',
  'Design System/Mixed/Chips & Pills': 'ChipsAndPills',
  'Design System/Mixed/Dialogs & Feedback': 'OverlayAndStatus',
  'Design System/Molecules/Composer Suggestion Chips': 'CurrentReality',
  'Design System/Molecules/Connector Chips': 'CurrentReality',
  'Design System/Molecules/Conversation Pill': 'Gallery',
  'Design System/Molecules/Decision Card Group': 'CurrentReality',
  'Design System/Molecules/Headers': 'Gallery',
  'Design System/Molecules/Hero Input': 'CurrentReality',
  'Design System/Molecules/Navigation Controls': 'Gallery',
  'Design System/Molecules/Settings Rows': 'CurrentReality',
  'Design System/Organisms/Dashboard Patterns': 'Gallery',
  'Design System/Registry': 'Inventory',
};

function toStoryIdPart(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function getStoryHref(storyTitle: string): string | undefined {
  const exportName = STORY_TITLE_TO_EXPORT_NAME[storyTitle];
  if (!exportName || typeof window === 'undefined') {
    return undefined;
  }

  const managerPath = window.top?.location.pathname ?? '/';
  const titleId = toStoryIdPart(storyTitle);
  const exportId = toStoryIdPart(exportName);

  return `${managerPath}?path=/story/${titleId}--${exportId}`;
}

export const Inventory: Story = {
  render: () => (
    <div style={{ display: 'grid', gap: 28, padding: 24, maxWidth: 1120 }}>
      <section style={{ display: 'grid', gap: 10 }}>
        <h1 style={{ margin: 0, fontSize: 28 }}>Registry</h1>
        <p style={{ margin: 0, color: 'var(--color-text-secondary)', maxWidth: 820, lineHeight: 1.55 }}>
          The map of every family currently registered in this browser. It combines the curated
          family manifest with generated inventory from the real Rebel UI code, and refreshes when
          Storybook starts or builds.
        </p>
        <p style={{ margin: 0, color: 'var(--color-text-secondary)', maxWidth: 820, lineHeight: 1.55 }}>
          New to the browser? Read the <strong>Start Here</strong> page first — it explains what this
          is and how to read the three status labels.
        </p>
      </section>

      <section style={{ display: 'grid', gap: 12 }}>
        <h2
          style={{
            margin: 0,
            fontSize: 12,
            letterSpacing: '0.18em',
            textTransform: 'uppercase',
            color: 'var(--color-text-secondary)',
          }}
        >
          Status legend
        </h2>
        <div
          style={{
            display: 'grid',
            gap: 10,
            gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
          }}
        >
          {ORDERED_STATUSES.map((status) => {
            const presentation = STATUS_PRESENTATION[status];
            return (
              <div
                key={status}
                style={{
                  padding: 14,
                  borderRadius: 14,
                  border: '1px solid var(--color-border-soft, rgba(148,163,184,0.18))',
                  background: 'rgba(148,163,184,0.04)',
                  display: 'grid',
                  gap: 8,
                }}
              >
                <span
                  style={{
                    alignSelf: 'start',
                    padding: '4px 10px',
                    borderRadius: 999,
                    background: presentation.pillBackground,
                    color: presentation.pillColor,
                    fontSize: 12,
                    fontWeight: 600,
                  }}
                >
                  {presentation.label}
                </span>
                <div style={{ color: 'var(--color-text-secondary)', lineHeight: 1.5 }}>
                  {presentation.blurb}
                </div>
                <div
                  style={{
                    color: 'var(--color-text-secondary)',
                    fontSize: 12,
                    fontFamily: 'monospace',
                  }}
                >
                  internal value: {status}
                </div>
              </div>
            );
          })}
        </div>
      </section>

      <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 12 }}>
        <div style={{ padding: 16, borderRadius: 16, background: 'rgba(255,255,255,0.04)' }}>
          <div style={{ color: 'var(--color-text-secondary)', fontSize: 13 }}>Components scanned</div>
          <div style={{ fontSize: 28, fontWeight: 600 }}>{inventory.summary.componentCount}</div>
        </div>
        <div style={{ padding: 16, borderRadius: 16, background: 'rgba(255,255,255,0.04)' }}>
          <div style={{ color: 'var(--color-text-secondary)', fontSize: 13 }}>Unique CSS tokens used</div>
          <div style={{ fontSize: 28, fontWeight: 600 }}>{inventory.summary.uniqueCssTokensUsed}</div>
        </div>
        <div style={{ padding: 16, borderRadius: 16, background: 'rgba(255,255,255,0.04)' }}>
          <div style={{ color: 'var(--color-text-secondary)', fontSize: 13 }}>Undefined tokens</div>
          <div style={{ fontSize: 28, fontWeight: 600 }}>{inventory.summary.undefinedCssTokensCount}</div>
        </div>
      </section>

      <section style={{ display: 'grid', gap: 12 }}>
        <h2 style={{ margin: 0, fontSize: 20 }}>Design system families</h2>
        <p style={{ margin: 0, color: 'var(--color-text-secondary)', maxWidth: 820, lineHeight: 1.55 }}>
          Each card includes a status label and an atomic review level. Story titles below the cards
          show the family&apos;s current Storybook path.
        </p>
        <div style={{ display: 'grid', gap: 12 }}>
          {manifest.families.map((family) => {
            const presentation =
              STATUS_PRESENTATION[family.status as ManifestStatus] ?? {
                label: family.status,
                blurb: '',
                pillBackground: 'rgba(148,163,184,0.16)',
                pillColor: 'var(--color-text-secondary)',
              };
            const href = getStoryHref(family.storyTitle);

            return (
              <a
                key={family.id}
                href={href}
                target="_top"
                style={{
                  padding: 16,
                  borderRadius: 16,
                  background: 'rgba(255,255,255,0.03)',
                  border: '1px solid rgba(255,255,255,0.06)',
                  display: 'grid',
                  gap: 8,
                  color: 'inherit',
                  textDecoration: 'none',
                  cursor: href ? 'pointer' : 'default',
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }}>
                  <div style={{ fontWeight: 600 }}>{family.title}</div>
                  <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', justifyContent: 'flex-end' }}>
                    <span
                      title={`internal status value: ${family.status}`}
                      style={{
                        fontSize: 12,
                        padding: '4px 10px',
                        borderRadius: 999,
                        fontWeight: 600,
                        background: presentation.pillBackground,
                        color: presentation.pillColor,
                      }}
                    >
                      {presentation.label}
                    </span>
                    <span
                      title={`atomic review level: ${family.atomicLevel}`}
                      style={{
                        fontSize: 12,
                        padding: '4px 10px',
                        borderRadius: 999,
                        fontWeight: 600,
                        background: 'rgba(148,163,184,0.12)',
                        color: 'var(--color-text-secondary)',
                      }}
                    >
                      {family.atomicLevel}
                    </span>
                  </div>
                </div>
                <div style={{ color: 'var(--color-text-secondary)', lineHeight: 1.5 }}>{family.summary}</div>
                <div
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    gap: 12,
                    alignItems: 'center',
                    flexWrap: 'wrap',
                  }}
                >
                  <div style={{ color: 'var(--color-text-secondary)', fontSize: 12, fontFamily: 'monospace' }}>
                    {family.storyTitle}
                  </div>
                  <div
                    style={{
                      fontSize: 12,
                      fontWeight: 600,
                      color: href ? 'var(--color-text-primary)' : 'var(--color-text-secondary)',
                    }}
                  >
                    {href ? 'Open story ->' : 'Story link unavailable'}
                  </div>
                </div>
              </a>
            );
          })}
        </div>
      </section>

      <section style={{ display: 'grid', gap: 12 }}>
        <h2 style={{ margin: 0, fontSize: 20 }}>Component inventory</h2>
        <div style={{ overflowX: 'auto', borderRadius: 16, background: 'rgba(255,255,255,0.03)' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: 900 }}>
            <thead>
              <tr style={{ textAlign: 'left', color: 'var(--color-text-secondary)' }}>
                <th style={{ padding: '12px 16px' }}>Component</th>
                <th style={{ padding: '12px 16px' }}>Source</th>
                <th style={{ padding: '12px 16px' }}>Variants / sizes</th>
                <th style={{ padding: '12px 16px' }}>Tokens</th>
                <th style={{ padding: '12px 16px' }}>Undefined</th>
              </tr>
            </thead>
            <tbody>
              {inventory.components.map((component) => {
                const variantSummary = [
                  ...Object.entries(component.cvaVariants).map(([key, values]) => `${key}: ${values.join(', ')}`),
                  ...Object.entries(component.unionProps)
                    .filter(([key]) => !(key in component.cvaVariants))
                    .map(([key, values]) => `${key}: ${values.join(', ')}`),
                ].join(' | ');

                return (
                  <tr key={component.component} style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                    <td style={{ padding: '14px 16px', fontWeight: 600 }}>{component.component}</td>
                    <td style={{ padding: '14px 16px', color: 'var(--color-text-secondary)', fontFamily: 'monospace', fontSize: 12 }}>
                      {component.sourceFile}
                    </td>
                    <td style={{ padding: '14px 16px', color: 'var(--color-text-secondary)' }}>
                      {variantSummary || 'n/a'}
                    </td>
                    <td style={{ padding: '14px 16px', color: 'var(--color-text-secondary)' }}>
                      {component.cssTokens.length}
                    </td>
                    <td style={{ padding: '14px 16px', color: component.undefinedCssTokens.length ? '#fbbf24' : 'var(--color-text-secondary)' }}>
                      {component.undefinedCssTokens.length
                        ? component.undefinedCssTokens.join(', ')
                        : 'none'}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  ),
};
