export const CHIEF_OF_STAFF_DISTILLATION_PROMPT_VERSION = 'chief-of-staff-distillation-v1';

export interface ChiefOfStaffDistillationRequest {
  heading: string;
  originalText: string;
  relativeTopicPath: string;
  currentDate: string;
}

export interface ChiefOfStaffDistillationOutput {
  bullets: string[];
  promptVersion: typeof CHIEF_OF_STAFF_DISTILLATION_PROMPT_VERSION;
}

export interface ChiefOfStaffDistillationValidationResult {
  ok: boolean;
  bullets: string[];
  failures: string[];
}

export type ChiefOfStaffHygieneDistiller = (
  request: ChiefOfStaffDistillationRequest,
) => Promise<ChiefOfStaffDistillationOutput | null>;

export const CHIEF_OF_STAFF_DISTILLATION_SYSTEM_PROMPT = `You compress private Chief-of-Staff work context into compact README briefing bullets.

Non-negotiable rules:
- The full original text has already been preserved in a private Chief-of-Staff topic. Your output is only a compact signpost layer.
- Return JSON only.
- Write 1-5 bullets.
- Each bullet must preserve active-work essentials when present: status/current priority, owner/collaborator, next action, and key risk/blocker.
- Do not rewrite stable identity, profile, preference, goal, personal, security, credential, secret, password, token, or API-key facts. If the input is mostly those facts, return an empty bullets array.
- Do not mention private/shared movement, publishing, deletion, or approval.
- Keep each bullet under 220 characters. The app will append the private retrieval link.`;

export const CHIEF_OF_STAFF_DISTILLATION_OUTPUT_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    bullets: {
      type: 'array',
      minItems: 0,
      maxItems: 5,
      items: {
        type: 'string',
        minLength: 1,
        maxLength: 220,
      },
    },
  },
  required: ['bullets'],
};

const HARD_PIN_OUTPUT_RE =
  /\b(identity|profile|bio|about me|personal|preference|preferences|goal|goals|objective|objectives|secret|secrets|credential|credentials|token|tokens|password|passwords|api[- ]keys?|salary|equity|health|hr|visa|do not share|don't share|never share)\b/i;
const FORBIDDEN_ACTION_RE = /\b(delete|deleted|publish|published|public|shared space|approval|approve|ask the user)\b/i;
const AUTOGENERATED_LINK_RE = /(?:^|\s)(?:see|details moved to)\s+`?memory\/topics\/auto-hygiene\//i;
const OWNER_SIGNAL_RE = /\b(owner|owns|owned by|responsible|lead|dri)\b/i;
const NEXT_ACTION_SIGNAL_RE = /\b(next action|next step|follow up|follow-up|todo|to do|due|send|ship|complete|finish|finalise|finalize)\b/i;
const RISK_SIGNAL_RE = /\b(risk|blocker|blocked|blocking|concern|slipping|delay|delayed|stuck)\b/i;
const STATUS_SIGNAL_RE = /\b(status|active|current priority|priority|in progress|blocked|done|complete|paused)\b/i;
const DATE_RE = /\b(?:20\d{2}-\d{2}-\d{2}|\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)[a-z]*\s+20\d{2})\b/i;
const STOPWORD_TOKENS = new Set([
  'action',
  'active',
  'additional',
  'context',
  'current',
  'detail',
  'details',
  'follow',
  'notes',
  'private',
  'product',
  'project',
  'status',
  'team',
  'work',
]);

export function buildChiefOfStaffDistillationPrompt(request: ChiefOfStaffDistillationRequest): string {
  return [
    `Current date: ${request.currentDate}`,
    `README heading: ${request.heading}`,
    `Private preserved topic path that the app will link to: ${request.relativeTopicPath}`,
    '',
    'Compress this private work-context text into compact README bullets.',
    'Return JSON matching: {"bullets":["..."]}.',
    '',
    '<original_work_context>',
    request.originalText.trim(),
    '</original_work_context>',
  ].join('\n');
}

export function validateChiefOfStaffDistillationOutput(
  output: unknown,
  request: ChiefOfStaffDistillationRequest,
): ChiefOfStaffDistillationValidationResult {
  const failures: string[] = [];
  const rawBullets = extractBulletArray(output);
  if (!rawBullets) {
    return {
      ok: false,
      bullets: [],
      failures: ['distillation_output_not_bullet_array'],
    };
  }
  if (rawBullets.length === 0) {
    return {
      ok: false,
      bullets: [],
      failures: ['distillation_output_empty'],
    };
  }
  if (rawBullets.length > 5) {
    failures.push('distillation_output_too_many_bullets');
  }

  const bullets = rawBullets.map((bullet) => normalizeBullet(bullet));
  for (const bullet of bullets) {
    if (bullet.length > 220) {
      failures.push('distillation_output_bullet_too_long');
    }
    if (HARD_PIN_OUTPUT_RE.test(bullet)) {
      failures.push('distillation_output_contains_hard_pinned_fact');
    }
    if (FORBIDDEN_ACTION_RE.test(bullet)) {
      failures.push('distillation_output_contains_forbidden_action');
    }
    if (AUTOGENERATED_LINK_RE.test(bullet)) {
      failures.push('distillation_output_should_not_include_link');
    }
  }

  const combinedLower = bullets.join('\n').toLowerCase();
  requireSignalIfPresent(request.originalText, combinedLower, OWNER_SIGNAL_RE, 'distillation_output_missing_owner_signal', failures);
  requireSignalIfPresent(request.originalText, combinedLower, NEXT_ACTION_SIGNAL_RE, 'distillation_output_missing_next_action_signal', failures);
  requireSignalIfPresent(request.originalText, combinedLower, RISK_SIGNAL_RE, 'distillation_output_missing_risk_signal', failures);
  requireSignalIfPresent(request.originalText, combinedLower, STATUS_SIGNAL_RE, 'distillation_output_missing_status_signal', failures);
  for (const owner of extractOwnerNames(request.originalText)) {
    if (!includesCaseInsensitive(combinedLower, owner)) {
      failures.push('distillation_output_missing_owner_name');
    }
  }
  requireSalientOverlap(
    extractSignalPhrase(request.originalText, /\bnext action is\s+(?:to\s+)?([^.\n]+)/i),
    combinedLower,
    'distillation_output_missing_next_action_detail',
    failures,
  );
  requireSalientOverlap(
    extractSignalPhrase(request.originalText, /\b(?:key|main)?\s*risk is\s+([^.\n]+)/i),
    combinedLower,
    'distillation_output_missing_risk_detail',
    failures,
  );
  for (const date of extractActionableDates(request.originalText)) {
    if (!combinedLower.includes(date.toLowerCase())) {
      failures.push('distillation_output_missing_due_date');
    }
  }

  return {
    ok: failures.length === 0,
    bullets,
    failures: [...new Set(failures)],
  };
}

function extractOwnerNames(value: string): string[] {
  const names = new Set<string>();
  for (const match of value.matchAll(/\b([A-Z][a-z]{2,})\s+owns\b/g)) {
    names.add(match[1]);
  }
  for (const match of value.matchAll(/\b([A-Z][a-z]{2,})\s+(?:is|was)\s+(?:the\s+)?(?:owner|lead|dri|responsible)\b/gi)) {
    names.add(match[1]);
  }
  return [...names];
}

function extractSignalPhrase(value: string, pattern: RegExp): string | null {
  return value.match(pattern)?.[1]?.trim() ?? null;
}

function requireSalientOverlap(
  phrase: string | null,
  distilledTextLower: string,
  failure: string,
  failures: string[],
): void {
  if (!phrase) {
    return;
  }
  const tokens = extractSalientTokens(phrase);
  if (tokens.length === 0) {
    return;
  }
  const requiredOverlap = Math.min(2, tokens.length);
  const overlap = tokens.filter((token) => distilledTextLower.includes(token.toLowerCase())).length;
  if (overlap < requiredOverlap) {
    failures.push(failure);
  }
}

function extractSalientTokens(value: string): string[] {
  return [...new Set(value
    .replace(/20\d{2}-\d{2}-\d{2}/g, ' ')
    .split(/[^A-Za-z0-9]+/)
    .map((token) => token.trim())
    .filter((token) => token.length >= 4)
    .filter((token) => !STOPWORD_TOKENS.has(token.toLowerCase())))];
}

function includesCaseInsensitive(haystackLower: string, needle: string): boolean {
  return haystackLower.includes(needle.toLowerCase());
}

function requireSignalIfPresent(
  originalText: string,
  distilledTextLower: string,
  signal: RegExp,
  failure: string,
  failures: string[],
): void {
  if (signal.test(originalText) && !signal.test(distilledTextLower)) {
    failures.push(failure);
  }
}

function extractActionableDates(value: string): string[] {
  const dates = new Set<string>();
  for (const sentence of value.split(/(?<=[.!?])\s+|\n+/)) {
    if (!/\b(next action|next step|follow up|follow-up|todo|to do|due|deadline|by|before|ship|complete|finish|finalise|finalize)\b/i.test(sentence)) {
      continue;
    }
    for (const match of sentence.matchAll(new RegExp(DATE_RE.source, 'gi'))) {
      dates.add(match[0]);
    }
  }
  return [...dates];
}

export function formatDistilledReadmeBullets(
  bullets: string[],
  relativeTopicPath: string,
): string[] {
  return bullets.map((bullet) => `- ${normalizeBullet(bullet)} See \`${relativeTopicPath}\`.`);
}

function extractBulletArray(output: unknown): string[] | null {
  if (!output || typeof output !== 'object') {
    return null;
  }
  const bullets = (output as { bullets?: unknown }).bullets;
  if (!Array.isArray(bullets) || bullets.some((item) => typeof item !== 'string')) {
    return null;
  }
  return bullets;
}

function normalizeBullet(value: string): string {
  return value
    .replace(/^\s*[-*]\s+/, '')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[.。]\s*$/, '');
}
