/**
 * AUTO-GENERATED — Stage 1 (super-mcp version single source of truth).
 *
 * Source: super-mcp/package.json (`version`, with `name` asserted as `super-mcp-router`).
 * Generator: scripts/generate-super-mcp-version.ts
 *
 * Updating super-mcp: bump super-mcp/package.json and rerun
 * `npm run generate:super-mcp-version` (or let validate:fast catch the drift).
 * DO NOT edit this file directly — your edits will be overwritten.
 */

export const GENERATED_SUPER_MCP_ROUTER_VERSION = "2.7.0" as const;
