/**
 * Re-export shim — canonical implementation lives in @core/constants.
 * This file remains so that existing src/main/ consumers continue to resolve
 * without updating their import paths. Remove once all consumers are migrated.
 */
export {
  MAX_FILE_DEPTH,
  MAX_CHILDREN_PER_DIRECTORY,
  MAX_PERSISTED_SESSIONS,
  MAX_DRAFT_ONLY_SESSIONS,
  AGENT_SESSION_HISTORY_VERSION,
  INBOX_STORE_VERSION,
  MAX_INBOX_HISTORY_ENTRIES,
  TASK_QUEUE_STORE_VERSION,
  MAX_TASK_HISTORY_ENTRIES,
  AUTOMATION_STORE_VERSION,
  MAX_AUTOMATION_RUN_HISTORY,
  MEMORY_HISTORY_STORE_VERSION,
  MAX_MEMORY_HISTORY_ENTRIES,
  MEMORY_HISTORY_MAX_AGE_DAYS,
  TOOL_USAGE_STORE_VERSION,
  MAX_TRACKED_TOOLS,
  FREQUENT_TOOLS_LIMIT,
  TOOL_STALENESS_DAYS,
  SKILL_USAGE_STORE_VERSION,
  MAX_TRACKED_SKILLS,
  SKILL_STALENESS_DAYS,
  SKILL_NUDGE_COOLDOWN_DAYS,
  USE_CASE_LIBRARY_STORE_VERSION,
  MAX_USE_CASES,
  USE_CASE_SIMILARITY_THRESHOLD,
  USE_CASE_QUALITY_THRESHOLD,
  USE_CASE_NEW_BADGE_DAYS,
  KNOWLEDGE_WORKER_AGENT_NAME,
  KNOWLEDGE_WORKER_AGENT_DESCRIPTION,
} from '@core/constants';
