import { unsafeAssertRoutingModelId } from '@shared/utils/modelChoiceCodec';
import { describe, expect, it, vi } from 'vitest';
import {
  runAgentLoop,
  compactMessageHistory,
  ContextOverflowError,
  APPROX_CHARS_PER_TOKEN,
  IMAGE_BLOCK_TOKEN_COST,
  estimatePromptTokensForPreflight,
} from '../agentLoop';
import { ModelError } from '../modelErrors';
import type { RebelCoreConfig, RebelCoreEvent, ExecuteToolFn } from '../types';
import type { ModelClient, StreamResult } from '../modelClient';
import type { ProviderCapabilities } from '../contextPolicy';
import type { ChatMessage, ContentBlock, ToolResultBlock, ToolResultContentBlock } from '../modelTypes';

const TEST_CAPABILITIES: ProviderCapabilities = {
  hasNativeContextEditing: false,
  hasNativeCompaction: false,
  cacheStrategy: 'none',
  cacheHeuristicTtlMs: 0,
  supportsImageContent: () => false,
};

const USAGE_50K = { inputTokens: 50_000, outputTokens: 1_000, cacheCreationTokens: 0, cacheReadTokens: 0 };
const USAGE_180K = { inputTokens: 160_000, outputTokens: 1_000, cacheCreationTokens: 10_000, cacheReadTokens: 10_000 };
const USAGE_LOW = { inputTokens: 10_000, outputTokens: 500, cacheCreationTokens: 0, cacheReadTokens: 0 };
const COMPACTED_IMAGE_PLACEHOLDER =
  '[Image dropped during compaction — generated by tool; ask to regenerate if needed.]';
const COMPACTED_TEXT_PLACEHOLDER =
  '[Tool output truncated during compaction — earlier in the conversation.]';

const END_TURN_RESULT: StreamResult = {
  content: [{ type: 'text', text: 'Done' }],
  stopReason: 'end_turn',
  usage: USAGE_LOW,
};

function createConfig(client: ModelClient, overrides?: Partial<RebelCoreConfig>): RebelCoreConfig {
  return {
    client,
    model: unsafeAssertRoutingModelId('test-model'),
    systemPrompt: 'Test.',
    messages: [{ role: 'user', content: 'test' }],
    tools: [{ name: 'Read', description: 'Read', input_schema: { type: 'object' as const, properties: {} } }],
    maxTokens: 1024,
    ...overrides,
  };
}

const noopExecuteTool: ExecuteToolFn = async () => ({ output: 'ok', isError: false });

// --- compactMessageHistory tests ---

describe('compactMessageHistory', () => {
  it('preserves recent turns and truncates older large tool outputs', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'msg1' },
      { role: 'assistant', content: [{ type: 'text', text: 'resp1' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'old', content: 'x'.repeat(10_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'resp2' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'old2', content: 'y'.repeat(8_000), is_error: false }] },
      // Recent turns (preserved)
      { role: 'assistant', content: [{ type: 'text', text: 'resp3' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'recent1', content: 'z'.repeat(20_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'resp4' }] },
      { role: 'user', content: 'follow up' },
      { role: 'assistant', content: [{ type: 'text', text: 'resp5' }] },
      { role: 'user', content: 'question' },
    ];

    const { compacted, removedChars } = compactMessageHistory(messages, 3);

    expect(removedChars).toBeGreaterThan(0);
    expect(compacted.length).toBe(messages.length);

    // Old tool outputs should be truncated
    const oldResult = compacted[2];
    expect(Array.isArray(oldResult.content)).toBe(true);
    const oldToolResult = (oldResult.content as ContentBlock[])[0] as ToolResultBlock;
    expect(Array.isArray(oldToolResult.content)).toBe(true);
    expect(oldToolResult.content).toEqual([{ type: 'text', text: COMPACTED_TEXT_PLACEHOLDER }]);

    // Recent tool output preserved
    const recentResult = compacted[6];
    const recentBlock = (recentResult.content as Array<{ type: string; content?: string }>)[0];
    expect(recentBlock.content).toBe('z'.repeat(20_000));
  });

  it('returns 0 removedChars when no large tool outputs exist', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'msg1' },
      { role: 'assistant', content: [{ type: 'text', text: 'resp1' }] },
    ];
    const { removedChars } = compactMessageHistory(messages, 3);
    expect(removedChars).toBe(0);
  });

  it('handles empty message array', () => {
    const { compacted, removedChars } = compactMessageHistory([], 3);
    expect(compacted).toEqual([]);
    expect(removedChars).toBe(0);
  });

  it('handles fewer turns than preserve count', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1', content: 'x'.repeat(10_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'done' }] },
    ];
    const { compacted, removedChars } = compactMessageHistory(messages, 5);
    // With only 1 turn and preserve=5, everything is preserved
    expect(removedChars).toBe(0);
    expect(compacted).toEqual(messages);
  });

  it('drops image blocks from older tool_result with short text (image-presence trigger)', () => {
    const shortText = 'Saved image at .rebel/screenshots/capture.png';
    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old turn' }] },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 'tool-with-image',
          is_error: false,
          content: [
            { type: 'text', text: shortText },
            { type: 'image', data: 'img-1', mimeType: 'image/png' },
            { type: 'image', data: 'img-2', mimeType: 'image/png' },
          ],
        }],
      },
      // Recent turns (preserved)
      { role: 'assistant', content: [{ type: 'text', text: 'recent-1' }] },
      { role: 'user', content: 'middle' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-2' }] },
      { role: 'user', content: 'middle-2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-3' }] },
      { role: 'user', content: 'end' },
    ];

    const { compacted, removedChars } = compactMessageHistory(messages, 3);
    expect(removedChars).toBe(2 * IMAGE_BLOCK_TOKEN_COST * APPROX_CHARS_PER_TOKEN);

    const compactedToolResult = ((compacted[2].content as ContentBlock[])[0] as ToolResultBlock).content;
    expect(Array.isArray(compactedToolResult)).toBe(true);

    const compactedParts = compactedToolResult as ToolResultContentBlock[];
    expect(compactedParts.filter((part) => part.type === 'image')).toHaveLength(0);
    expect(
      compactedParts
        .filter((part): part is Extract<ToolResultContentBlock, { type: 'text' }> => part.type === 'text')
        .map((part) => part.text),
    ).toEqual([
      shortText,
      COMPACTED_IMAGE_PLACEHOLDER,
      COMPACTED_IMAGE_PLACEHOLDER,
    ]);
  });

  it('drops image blocks AND truncates text in older tool_result with long text + images', () => {
    const longText = 'x'.repeat(6_000);
    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old turn' }] },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 'tool-with-image',
          is_error: false,
          content: [
            { type: 'text', text: longText },
            { type: 'image', data: 'img-1', mimeType: 'image/png' },
            { type: 'image', data: 'img-2', mimeType: 'image/png' },
            { type: 'image', data: 'img-3', mimeType: 'image/png' },
            { type: 'image', data: 'img-4', mimeType: 'image/png' },
          ],
        }],
      },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-1' }] },
      { role: 'user', content: 'middle' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-2' }] },
      { role: 'user', content: 'middle-2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-3' }] },
      { role: 'user', content: 'end' },
    ];

    const { compacted, removedChars } = compactMessageHistory(messages, 3);
    expect(removedChars).toBe(
      longText.length + (4 * IMAGE_BLOCK_TOKEN_COST * APPROX_CHARS_PER_TOKEN),
    );

    const compactedToolResult = ((compacted[2].content as ContentBlock[])[0] as ToolResultBlock).content;
    expect(Array.isArray(compactedToolResult)).toBe(true);

    const compactedParts = compactedToolResult as ToolResultContentBlock[];
    expect(compactedParts.filter((part) => part.type === 'image')).toHaveLength(0);
    expect(
      compactedParts
        .filter((part): part is Extract<ToolResultContentBlock, { type: 'text' }> => part.type === 'text')
        .map((part) => part.text),
    ).toEqual([
      COMPACTED_TEXT_PLACEHOLDER,
      COMPACTED_IMAGE_PLACEHOLDER,
      COMPACTED_IMAGE_PLACEHOLDER,
      COMPACTED_IMAGE_PLACEHOLDER,
      COMPACTED_IMAGE_PLACEHOLDER,
    ]);
  });

  it('preserves images in recent-window tool_result regardless of text size', () => {
    const recentToolResultContent: ToolResultContentBlock[] = [
      { type: 'text', text: 'x'.repeat(6_000) },
      { type: 'image', data: 'recent-img-1', mimeType: 'image/png' },
      { type: 'image', data: 'recent-img-2', mimeType: 'image/png' },
    ];

    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old turn' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'old-tool', content: 'x'.repeat(10_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-1' }] },
      { role: 'user', content: 'middle' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-2' }] },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 'recent-tool',
          is_error: false,
          content: recentToolResultContent,
        }],
      },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-3' }] },
      { role: 'user', content: 'end' },
    ];

    const { compacted } = compactMessageHistory(messages, 3);
    const recentToolResult = ((compacted[6].content as ContentBlock[])[0] as ToolResultBlock).content;
    expect(recentToolResult).toEqual(recentToolResultContent);
  });

  it('returns null for older tool_result with short text and no images', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old turn' }] },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 'short-text-only',
          is_error: false,
          content: [{ type: 'text', text: 'short text only' }],
        }],
      },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-1' }] },
      { role: 'user', content: 'middle' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-2' }] },
      { role: 'user', content: 'middle-2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-3' }] },
      { role: 'user', content: 'end' },
    ];

    const { compacted, removedChars } = compactMessageHistory(messages, 3);
    expect(removedChars).toBe(0);
    expect(compacted).toEqual(messages);
  });

  it('drops images and emits one placeholder per image when older tool_result has zero text', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old turn' }] },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 'image-only-result',
          is_error: false,
          content: [
            { type: 'image', data: 'img-1', mimeType: 'image/png' },
            { type: 'image', data: 'img-2', mimeType: 'image/png' },
          ],
        }],
      },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-1' }] },
      { role: 'user', content: 'middle' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-2' }] },
      { role: 'user', content: 'middle-2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-3' }] },
      { role: 'user', content: 'end' },
    ];

    const { compacted, removedChars } = compactMessageHistory(messages, 3);
    expect(removedChars).toBe(2 * IMAGE_BLOCK_TOKEN_COST * APPROX_CHARS_PER_TOKEN);

    const compactedToolResult = ((compacted[2].content as ContentBlock[])[0] as ToolResultBlock).content;
    const compactedParts = compactedToolResult as ToolResultContentBlock[];
    expect(compactedParts.filter((part) => part.type === 'image')).toHaveLength(0);
    expect(
      compactedParts
        .filter((part): part is Extract<ToolResultContentBlock, { type: 'text' }> => part.type === 'text')
        .map((part) => part.text),
    ).toEqual([
      COMPACTED_IMAGE_PLACEHOLDER,
      COMPACTED_IMAGE_PLACEHOLDER,
    ]);
  });

  it('is idempotent: running compaction twice on already-compacted history is a no-op', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old turn' }] },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 'with-images',
          is_error: false,
          content: [
            { type: 'text', text: 'short text' },
            { type: 'image', data: 'img-1', mimeType: 'image/png' },
          ],
        }],
      },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-1' }] },
      { role: 'user', content: 'middle' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-2' }] },
      { role: 'user', content: 'middle-2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-3' }] },
      { role: 'user', content: 'end' },
    ];

    const firstPass = compactMessageHistory(messages, 3);
    const secondPass = compactMessageHistory(firstPass.compacted, 3);
    expect(secondPass.removedChars).toBe(0);
    expect(secondPass.compacted).toEqual(firstPass.compacted);
  });

  it('handles malformed tool_result content (null / empty array) without throwing', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old turn' }] },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 'empty-array',
          is_error: false,
          content: [] as ToolResultContentBlock[],
        }],
      },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-1' }] },
      { role: 'user', content: 'middle' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-2' }] },
      { role: 'user', content: 'middle-2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-3' }] },
      { role: 'user', content: 'end' },
    ];

    expect(() => compactMessageHistory(messages, 3)).not.toThrow();
    const { removedChars, compacted } = compactMessageHistory(messages, 3);
    expect(removedChars).toBe(0);
    expect(compacted).toEqual(messages);
  });

  it('reports progress when only images are removed', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old turn' }] },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 'images-only-removal',
          is_error: false,
          content: [
            { type: 'text', text: 'short text' },
            { type: 'image', data: 'img-1', mimeType: 'image/png' },
            { type: 'image', data: 'img-2', mimeType: 'image/png' },
            { type: 'image', data: 'img-3', mimeType: 'image/png' },
          ],
        }],
      },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-1' }] },
      { role: 'user', content: 'middle' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-2' }] },
      { role: 'user', content: 'middle-2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent-3' }] },
      { role: 'user', content: 'end' },
    ];

    const { removedChars } = compactMessageHistory(messages, 3);
    expect(removedChars).toBe(3 * IMAGE_BLOCK_TOKEN_COST * APPROX_CHARS_PER_TOKEN);
  });
});

describe('estimatePromptTokensForPreflight', () => {
  it('returns a value below runaway hard cap when tool_result contains two large base64 images and small text', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'Generate images for the campaign.' },
      {
        role: 'assistant',
        content: [{ type: 'text', text: 'Done. Generated two images.' }],
      },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 'image-result',
          is_error: false,
          content: [
            { type: 'text', text: 'Saved two images at /tmp/image-1.png and /tmp/image-2.png' },
            { type: 'image', data: 'A'.repeat(3_000_000), mimeType: 'image/png' },
            { type: 'image', data: 'B'.repeat(3_000_000), mimeType: 'image/png' },
          ],
        }],
      },
    ];

    const estimate = estimatePromptTokensForPreflight({
      systemPrompt: 'You are Rebel.',
      messages,
      tools: [],
    });

    expect(Number.isFinite(estimate)).toBe(true);
    expect(estimate).toBeLessThan(1_000_000);
  });
});

// --- Context overflow recovery tests ---

describe('agentLoop context overflow recovery', () => {
  it('compacts before sending when estimated prompt exceeds the context window', async () => {
    const client: ModelClient = {
      stream: vi.fn(async () => END_TURN_RESULT),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };
    const messagesWithLargeOutput: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old1' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1', content: 'x'.repeat(20_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'old2' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't2', content: 'y'.repeat(20_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'recent1' }] },
      { role: 'user', content: 'msg' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent2' }] },
      { role: 'user', content: 'msg2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent3' }] },
      { role: 'user', content: 'continue' },
    ];

    const events: RebelCoreEvent[] = [];
    await runAgentLoop(
      createConfig(client, {
        messages: messagesWithLargeOutput,
        contextWindow: 8_000,
        maxTokens: 1024,
      }),
      noopExecuteTool,
      (e) => events.push(e),
    );

    expect(events.some(e => e.type === 'recovery:compaction')).toBe(true);
    expect(client.stream).toHaveBeenCalledTimes(1);
  });

  it('refuses runaway prompts before sending any provider request', async () => {
    const client: ModelClient = {
      stream: vi.fn(async () => END_TURN_RESULT),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    await expect(
      runAgentLoop(
        createConfig(client, {
          messages: [{ role: 'user', content: 'x'.repeat(10_000) }],
          contextWindow: 1_000,
          maxTokens: 1024,
        }),
        noopExecuteTool,
        () => {},
      ),
    ).rejects.toMatchObject({ kind: 'context_overflow' });
    expect(client.stream).not.toHaveBeenCalled();
  });

  it('recovers from context_overflow by compacting and retrying', async () => {
    let callCount = 0;
    const client: ModelClient = {
      stream: vi.fn(async () => {
        callCount++;
        if (callCount === 1) {
          throw new ModelError('context_overflow', 'Context too long', 400);
        }
        return END_TURN_RESULT;
      }),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    // Need enough turns (>3) with large tool outputs in the OLD region so compaction
    // can truncate them. With preserveLastNTurns=3, the 4th+ assistant from the end
    // defines the compact boundary.
    const messagesWithLargeOutput: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old1' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1', content: 'x'.repeat(10_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'old2' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't2', content: 'y'.repeat(10_000), is_error: false }] },
      // Recent 3 turns (preserved by compaction)
      { role: 'assistant', content: [{ type: 'text', text: 'recent1' }] },
      { role: 'user', content: 'msg' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent2' }] },
      { role: 'user', content: 'msg2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent3' }] },
      { role: 'user', content: 'continue' },
    ];

    const events: RebelCoreEvent[] = [];
    const result = await runAgentLoop(
      createConfig(client, { messages: messagesWithLargeOutput }),
      noopExecuteTool,
      (e) => events.push(e),
    );

    expect(result.turns).toBeGreaterThanOrEqual(1);
    expect(events.some(e => e.type === 'recovery:compaction')).toBe(true);
    expect(client.stream).toHaveBeenCalledTimes(2);
  });

  it('does not escalate when overflow compaction removes only images', async () => {
    let callCount = 0;
    const client: ModelClient = {
      stream: vi.fn(async () => {
        callCount++;
        if (callCount === 1) {
          throw new ModelError('context_overflow', 'Context too long', 400);
        }
        return END_TURN_RESULT;
      }),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    const messagesWithOlderImagesOnly: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old1' }] },
      {
        role: 'user',
        content: [{
          type: 'tool_result',
          tool_use_id: 't-images',
          is_error: false,
          content: [
            { type: 'text', text: 'Saved image at .rebel/screenshots/old.png' },
            { type: 'image', data: 'img-1', mimeType: 'image/png' },
            { type: 'image', data: 'img-2', mimeType: 'image/png' },
          ],
        }],
      },
      { role: 'assistant', content: [{ type: 'text', text: 'old2' }] },
      { role: 'user', content: 'old user turn' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent1' }] },
      { role: 'user', content: 'recent user turn 1' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent2' }] },
      { role: 'user', content: 'recent user turn 2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent3' }] },
      { role: 'user', content: 'continue' },
    ];

    const events: RebelCoreEvent[] = [];
    const result = await runAgentLoop(
      createConfig(client, { messages: messagesWithOlderImagesOnly }),
      noopExecuteTool,
      (e) => events.push(e),
    );

    expect(result.turns).toBeGreaterThanOrEqual(1);
    expect(events.some((e) => e.type === 'recovery:compaction')).toBe(true);
    expect(client.stream).toHaveBeenCalledTimes(2);
  });

  it('throws ContextOverflowError after MAX_COMPACTION_ATTEMPTS with no-op compaction', async () => {
    const client: ModelClient = {
      stream: vi.fn(async () => {
        throw new ModelError('context_overflow', 'Context too long', 400);
      }),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    // Messages with no large tool outputs → compaction is no-op
    const events: RebelCoreEvent[] = [];
    await expect(
      runAgentLoop(
        createConfig(client, { messages: [{ role: 'user', content: 'short' }] }),
        noopExecuteTool,
        (e) => events.push(e),
      ),
    ).rejects.toThrow(ContextOverflowError);

    // No-op compaction should escalate immediately
    expect(client.stream).toHaveBeenCalledTimes(1);
    // ContextOverflowError does NOT emit turn:error — the orchestrator handles it
    expect(events.filter(e => e.type === 'turn:error').length).toBe(0);
  });

  it('fires onContextOverflow callback with lastKnownInputTokens on overflow', async () => {
    let callCount = 0;
    const client: ModelClient = {
      stream: vi.fn(async () => {
        callCount++;
        if (callCount === 1) {
          return {
            content: [{ type: 'tool_use', id: 't1', name: 'Read', input: {} }] as ContentBlock[],
            stopReason: 'tool_use',
            usage: USAGE_50K,
          };
        }
        if (callCount === 2) {
          throw new ModelError('context_overflow', 'Context too long', 400);
        }
        return END_TURN_RESULT;
      }),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    const overflowSpy = vi.fn();
    // Need 4+ turns with large tool outputs so compaction can remove from the old region
    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old1' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'old1', content: 'x'.repeat(10_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'old2' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'old2', content: 'x'.repeat(10_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'recent1' }] },
      { role: 'user', content: 'msg' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent2' }] },
      { role: 'user', content: 'msg2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent3' }] },
    ];

    const events: RebelCoreEvent[] = [];
    await runAgentLoop(
      createConfig(client, { messages, onContextOverflow: overflowSpy }),
      async () => ({ output: 'y'.repeat(10_000), isError: false }),
      (e) => events.push(e),
    );

    expect(overflowSpy).toHaveBeenCalledWith({
      model: expect.any(String),
      profileId: null,
      lastKnownInputTokens: 50_000,
    });
  });

  it('does not recover from auth errors', async () => {
    const client: ModelClient = {
      stream: vi.fn(async () => {
        throw new ModelError('auth', 'Invalid API key', 401);
      }),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    await expect(
      runAgentLoop(createConfig(client), noopExecuteTool, () => {}),
    ).rejects.toThrow('Invalid API key');
  });

  it('does not recover from abort', async () => {
    const client: ModelClient = {
      stream: vi.fn(async () => {
        throw new ModelError('abort', 'Aborted', undefined);
      }),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    await expect(
      runAgentLoop(createConfig(client), noopExecuteTool, () => {}),
    ).rejects.toThrow();
    expect(client.stream).toHaveBeenCalledTimes(1);
  });
});

// --- Context budget tracking tests ---

describe('agentLoop context budget tracking', () => {
  it('emits context:warning at 70%+ utilization (once)', async () => {
    const client: ModelClient = {
      stream: vi.fn(async () => ({
        content: [{ type: 'text', text: 'Done' }] as ContentBlock[],
        stopReason: 'end_turn',
        usage: { inputTokens: 150_000, outputTokens: 1_000, cacheCreationTokens: 0, cacheReadTokens: 0 },
      })),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    const events: RebelCoreEvent[] = [];
    await runAgentLoop(
      createConfig(client, { contextWindow: 200_000 }),
      noopExecuteTool,
      (e) => events.push(e),
    );

    const warnings = events.filter(e => e.type === 'context:warning');
    expect(warnings.length).toBe(1);
    expect((warnings[0] as { utilization: number }).utilization).toBeCloseTo(0.75);
  });

  it('does not emit warnings below 70% utilization', async () => {
    const client: ModelClient = {
      stream: vi.fn(async () => ({
        content: [{ type: 'text', text: 'Done' }] as ContentBlock[],
        stopReason: 'end_turn',
        usage: USAGE_LOW,
      })),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    const events: RebelCoreEvent[] = [];
    await runAgentLoop(
      createConfig(client, { contextWindow: 200_000 }),
      noopExecuteTool,
      (e) => events.push(e),
    );

    expect(events.filter(e => e.type === 'context:warning').length).toBe(0);
  });

  it('fires proactive compaction at 85%+ utilization (once)', async () => {
    let callCount = 0;
    const client: ModelClient = {
      stream: vi.fn(async () => {
        callCount++;
        const content: ContentBlock[] = callCount === 1
          ? [{ type: 'tool_use', id: 't1', name: 'Read', input: {} }]
          : [{ type: 'text', text: 'Done' }];
        return {
          content,
          stopReason: callCount === 1 ? 'tool_use' : 'end_turn',
          usage: USAGE_180K,
        };
      }),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    const events: RebelCoreEvent[] = [];
    // Need 4+ assistant turns with large tool outputs in the old region
    const messages: ChatMessage[] = [
      { role: 'user', content: 'start' },
      { role: 'assistant', content: [{ type: 'text', text: 'old1' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'old', content: 'x'.repeat(10_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'old2' }] },
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'old2', content: 'x'.repeat(10_000), is_error: false }] },
      { role: 'assistant', content: [{ type: 'text', text: 'recent1' }] },
      { role: 'user', content: 'msg' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent2' }] },
      { role: 'user', content: 'msg2' },
      { role: 'assistant', content: [{ type: 'text', text: 'recent3' }] },
    ];

    await runAgentLoop(
      createConfig(client, { contextWindow: 200_000, messages }),
      async () => ({ output: 'ok', isError: false }),
      (e) => events.push(e),
    );

    const compactions = events.filter(e => e.type === 'recovery:compaction');
    expect(compactions.length).toBe(1);
  });

  it('includes contextUtilization in turn:complete event when contextWindow set', async () => {
    const client: ModelClient = {
      stream: vi.fn(async () => ({
        content: [{ type: 'text', text: 'Done' }] as ContentBlock[],
        stopReason: 'end_turn',
        usage: USAGE_50K,
      })),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    const events: RebelCoreEvent[] = [];
    await runAgentLoop(
      createConfig(client, { contextWindow: 200_000 }),
      noopExecuteTool,
      (e) => events.push(e),
    );

    const turnComplete = events.find(e => e.type === 'turn:complete') as { contextUtilization?: number };
    expect(turnComplete.contextUtilization).toBeCloseTo(0.25);
  });

  it('omits contextUtilization when contextWindow is not set', async () => {
    const client: ModelClient = {
      stream: vi.fn(async () => END_TURN_RESULT),
      create: vi.fn(),
      capabilities: TEST_CAPABILITIES,
    };

    const events: RebelCoreEvent[] = [];
    await runAgentLoop(
      createConfig(client),
      noopExecuteTool,
      (e) => events.push(e),
    );

    const turnComplete = events.find(e => e.type === 'turn:complete') as { contextUtilization?: number };
    expect(turnComplete.contextUtilization).toBeUndefined();
  });
});
