/* eslint-disable -- generated file; do not hand-edit. Run `npx tsx scripts/generate-event-envelope-validator.ts` to refresh. */
/**
 * AUTO-GENERATED — Stage 0.B (cross-surface centralization).
 *
 * Source: src/shared/ipc/schemas/agent.ts (`AgentEventSchema` discriminator literals).
 * Generator: scripts/generate-event-envelope-validator.ts
 *
 * Adding new event types: add the variant to AgentEventSchema and rerun the
 * generator (or let validate:fast catch the drift). DO NOT edit this file
 * directly — your edits will be overwritten.
 */

export const GENERATED_KNOWN_AGENT_EVENT_TYPES: ReadonlySet<string> = new Set([
  "answer_phase_started",
  "assistant",
  "assistant_delta",
  "compaction_completed",
  "compaction_failed",
  "compaction_retrying",
  "compaction_started",
  "compaction_summary_ready",
  "context_overflow",
  "error",
  "recovery:compacting",
  "recovery:depth4_attempting",
  "recovery:failed",
  "recovery:fallback_attempting",
  "recovery:fallback_succeeded",
  "recovery:last_resort_skipped",
  "recovery:retrying",
  "recovery:skeleton_attempting",
  "recovery:started",
  "recovery:succeeded",
  "recovery:summary_ready",
  "result",
  "status",
  "thinking_delta",
  "tool",
  "turn_started",
  "turn_superseded",
  "user_message",
  "user_question",
  "user_question_answered",
  "warning",
]);
