import { describe, expect, it } from 'vitest';
import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const SCRIPT_PATH = path.join(REPO_ROOT, 'scripts/generate-event-envelope-validator.ts');
const GENERATED_PATH = path.join(REPO_ROOT, 'cloud-client/src/utils/eventEnvelopeValidator.generated.ts');

/** Run the script in --check mode and return its exit code + stderr. */
function runCheck(): { status: number; stderr: string; stdout: string } {
  const result = spawnSync('npx', ['tsx', SCRIPT_PATH, '--check'], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
  });
  return {
    status: result.status ?? -1,
    stderr: result.stderr ?? '',
    stdout: result.stdout ?? '',
  };
}

describe('generate-event-envelope-validator (Stage 0.B codegen)', () => {
  it('is in sync with src/shared/ipc/schemas/agent.ts (--check mode passes)', () => {
    const { status, stdout, stderr } = runCheck();
    expect(status, `stdout: ${stdout}\nstderr: ${stderr}`).toBe(0);
    expect(stdout).toMatch(/event type\(s\) in sync/);
  });

  it('flags staleness when the generated file is mutated (drift simulation)', () => {
    const original = fs.readFileSync(GENERATED_PATH, 'utf8');
    try {
      fs.writeFileSync(
        GENERATED_PATH,
        original.replace(
          'GENERATED_KNOWN_AGENT_EVENT_TYPES: ReadonlySet<string> = new Set([',
          'GENERATED_KNOWN_AGENT_EVENT_TYPES: ReadonlySet<string> = new Set([\n  "drift-injected-event",',
        ),
        'utf8',
      );
      const { status, stderr } = runCheck();
      expect(status).not.toBe(0);
      expect(stderr).toMatch(/stale/i);
    } finally {
      fs.writeFileSync(GENERATED_PATH, original, 'utf8');
    }
  });

  it('emits the documented header marker so the generated file is unambiguous', () => {
    const content = fs.readFileSync(GENERATED_PATH, 'utf8');
    expect(content).toMatch(/AUTO-GENERATED — Stage 0\.B/);
    expect(content).toMatch(/DO NOT edit this file/);
  });

  it('fails closed when a union member is refactored into a named schema (reviewer-MAJOR closure)', () => {
    const SCHEMA_PATH = path.join(REPO_ROOT, 'src/shared/ipc/schemas/agent.ts');
    const originalSource = fs.readFileSync(SCHEMA_PATH, 'utf8');
    const originalGenerated = fs.readFileSync(GENERATED_PATH, 'utf8');

    // Replace one inline `z.object({ type: z.literal('status'), ... })` with a
    // named-schema reference. The generator must fail-closed because it cannot
    // statically introspect what literal that reference resolves to.
    const namedSchemaInsertion = `\nconst StatusEventSchema = z.object({ type: z.literal('status'), message: z.string(), timestamp: z.number() });\n`;
    // Field-agnostic: matches the whole inline status member up to its closing
    // `}),` so legitimate schema evolution (new fields, comments) can't silently
    // turn this mutation into a no-op. Holds as long as the member has no nested
    // `}),` (flat scalar fields).
    const inlineStatusBlock = /  z\.object\(\{\s*type: z\.literal\('status'\),[\s\S]*?\}\),/;
    expect(
      inlineStatusBlock.test(originalSource),
      'sentinel inline status block must exist in the schema (update inlineStatusBlock if the member moved or gained nested objects)',
    ).toBe(true);
    const patchedSource = originalSource
      .replace(/^export const AgentEventSchema/m, `${namedSchemaInsertion}export const AgentEventSchema`)
      .replace(inlineStatusBlock, '  StatusEventSchema,');

    expect(patchedSource, 'sentinel inline status block must exist in the schema').not.toBe(originalSource);

    try {
      fs.writeFileSync(SCHEMA_PATH, patchedSource, 'utf8');
      const result = spawnSync('npx', ['tsx', SCRIPT_PATH, '--check'], {
        cwd: REPO_ROOT,
        encoding: 'utf8',
      });
      expect(result.status, `stderr: ${result.stderr}\nstdout: ${result.stdout}`).not.toBe(0);
      expect(result.stderr).toMatch(/(union-member count|named schema|generator)/i);
    } finally {
      fs.writeFileSync(SCHEMA_PATH, originalSource, 'utf8');
      fs.writeFileSync(GENERATED_PATH, originalGenerated, 'utf8');
    }
  });
});
