import { describe, expect, it } from 'vitest';
import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const SCRIPT_PATH = path.join(REPO_ROOT, 'scripts/generate-super-mcp-version.ts');
const GENERATED_PATH = path.join(REPO_ROOT, 'src/core/services/superMcpVersion.generated.ts');
const SUPER_MCP_PACKAGE_PATH = path.join(REPO_ROOT, 'super-mcp/package.json');

function runGenerator(args: readonly string[] = []): { status: number; stderr: string; stdout: string } {
  const result = spawnSync(process.execPath, ['--import', 'tsx', SCRIPT_PATH, ...args], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
  });
  return {
    status: result.status ?? -1,
    stderr: result.stderr ?? '',
    stdout: result.stdout ?? '',
  };
}

function readSuperMcpPackageVersion(): string {
  const packageJson = JSON.parse(fs.readFileSync(SUPER_MCP_PACKAGE_PATH, 'utf8')) as {
    readonly version: string;
  };
  return packageJson.version;
}

describe('generate-super-mcp-version (Stage 1 codegen)', () => {
  it('is in sync with super-mcp/package.json (--check mode passes)', () => {
    const { status, stdout, stderr } = runGenerator(['--check']);
    expect(status, `stdout: ${stdout}\nstderr: ${stderr}`).toBe(0);
    expect(stdout).toMatch(/super-mcp-router@.+ in sync/);
  });

  it('fails when the generated file is missing', () => {
    const original = fs.readFileSync(GENERATED_PATH, 'utf8');
    try {
      fs.unlinkSync(GENERATED_PATH);
      const { status, stderr } = runGenerator(['--check']);
      expect(status).not.toBe(0);
      expect(stderr).toMatch(/generated file missing/i);
    } finally {
      fs.writeFileSync(GENERATED_PATH, original, 'utf8');
    }
  });

  it('fails when the generated file is mutated with a stale version', () => {
    const original = fs.readFileSync(GENERATED_PATH, 'utf8');
    try {
      fs.writeFileSync(
        GENERATED_PATH,
        original.replace(
          /GENERATED_SUPER_MCP_ROUTER_VERSION = "[^"]+"/,
          'GENERATED_SUPER_MCP_ROUTER_VERSION = "0.0.0-stale"',
        ),
        'utf8',
      );
      const { status, stderr } = runGenerator(['--check']);
      expect(status).not.toBe(0);
      expect(stderr).toMatch(/stale/i);
    } finally {
      fs.writeFileSync(GENERATED_PATH, original, 'utf8');
    }
  });

  it('writes generated content matching super-mcp/package.json version', () => {
    const original = fs.readFileSync(GENERATED_PATH, 'utf8');
    try {
      const { status, stdout, stderr } = runGenerator();
      expect(status, `stdout: ${stdout}\nstderr: ${stderr}`).toBe(0);

      const version = readSuperMcpPackageVersion();
      const content = fs.readFileSync(GENERATED_PATH, 'utf8');
      expect(content).toContain(`GENERATED_SUPER_MCP_ROUTER_VERSION = ${JSON.stringify(version)} as const;`);
      expect(content).toMatch(/DO NOT edit this file/);
      expect(content).toMatch(/Generator: scripts\/generate-super-mcp-version\.ts/);
    } finally {
      fs.writeFileSync(GENERATED_PATH, original, 'utf8');
    }
  });
});
