import { createScopedLogger } from '@core/logger';
import { getAssetStore } from '@core/assetStore';
import { getContentStore } from '@core/contentStore';
import { appendDiagnosticEvent } from '@core/services/diagnosticEventsLedger';
import { hashToolName } from '@core/services/diagnostics/eventHashing';
import { MAX_TOOL_CALL_ERROR_EMITS_PER_TURN, bucketAbortDurationMs } from '@core/services/diagnostics/manifest';
import { materializeImageRefsForEvent } from '@core/services/imageAssetMaterialization';
import { materializeContentRefsForEvent } from '@core/services/contentMaterialization';
import { CONTENT_REF_THRESHOLD_BYTES } from '@core/contentStore';
import {
  UNIVERSAL_TOOL_OUTPUT_CAP_BYTES,
  boundToolOutputForSafety,
  type BoundedToolOutput,
} from '@core/services/contentTruncation';
import { peekCloudCapabilities } from '@core/cloudCapabilityProbe';
import {
  checkInlineImageWithinLimits,
  buildOversizedImagePlaceholder,
  VISION_UNSUPPORTED_REPORT_INSTRUCTION,
} from '@core/utils/fileTypeDetection';
import { MAX_COMPACTION_ATTEMPTS } from '@core/utils/compactionUtils';
import { getThinkingRetentionTurns } from '@shared/utils/reasoningCapability';
import type {
  ChatMessage,
  ContentBlock,
  ToolResultContentBlock,
  ToolResultBlock,
  ToolUseBlock,
  ToolDefinition,
  SystemPrompt,
} from './modelTypes';
import type {
  EventHandler,
  ExecuteToolFn,
  RebelCoreConfig,
  TokenUsage,
  ToolExecutionResult,
} from './types';
import { ZERO_TOKEN_USAGE, addUsage, getEffectiveInputTokens } from './types';
import { ModelError } from './modelErrors';
import { ToolFailureTracker } from './toolFailureTracker';
import {
  APPROX_CHARS_PER_TOKEN,
  IMAGE_BLOCK_TOKEN_COST,
  estimatePromptTokens,
  estimateTokensFromUnknown,
} from './tokenEstimation';
import {
  SKELETON_FALLBACK_USER_TEXT,
  stripBlocksForSkeleton,
  type SkeletonStripResult,
} from './skeletonStripping';
import { PARALLEL_AGENT_CAP } from './constants/limits';
import { SUB_AGENT_TOOL_NAMES, isSubAgentToolName } from './constants/toolNames';
import { runWithLimit } from './util/pLimit';
import { isAgentToolTimeoutError } from './agentToolErrors';
import { ToolKilledByWatchdogError } from './toolErrors';

import { TurnScopedHydrationCache } from '@core/services/imageHydrationCache';
import { TurnScopedContentHydrationCache } from '@core/services/contentHydrationCache';

export {
  APPROX_CHARS_PER_TOKEN,
  IMAGE_BLOCK_TOKEN_COST,
  estimatePromptTokens,
  estimateTokensFromUnknown,
};

const log = createScopedLogger({ service: 'agentLoop' });

const DEFAULT_MAX_TOKENS = 4_096;
const PRESERVE_LAST_N_TURNS = 3;
const TOOL_OUTPUT_TRUNCATION_THRESHOLD = 5_000;
const COMPACTED_IMAGE_PLACEHOLDER =
  '[Image dropped during compaction — generated by tool; ask to regenerate if needed.]';
const COMPACTED_TEXT_PLACEHOLDER =
  '[Tool output truncated during compaction — earlier in the conversation.]';
const PREFLIGHT_CONTEXT_HEADROOM = 0.98;
const RUNAWAY_PROMPT_HARD_CAP_TOKENS = 1_000_000;
const CHARS_PER_TOKEN_ESTIMATE = 4;
const PARALLEL_SUBAGENTS_START_PREFIX = 'parallel:subagents:start:';
const PARALLEL_SUBAGENTS_PROGRESS_PREFIX = 'parallel:subagents:progress:';
const PARALLEL_SUBAGENTS_COMPLETE_PREFIX = 'parallel:subagents:complete:';

const emitParallelSubagentsStatus = (
  onEvent: EventHandler,
  prefix: string,
  payload: Record<string, number>,
): void => {
  onEvent({
    type: 'status',
    message: `${prefix}${JSON.stringify(payload)}`,
  });
};

const createAbortError = (message = 'Operation was aborted'): Error => {
  const error = new Error(message);
  error.name = 'AbortError';
  return error;
};

const assertNotAborted = (signal?: AbortSignal): void => {
  if (signal?.aborted) {
    throw createAbortError();
  }
};

const isAbortError = (error: unknown): error is Error =>
  error instanceof Error && error.name === 'AbortError';

const isAbortOrTimeoutError = (error: unknown): error is Error =>
  isAbortError(error) || isAgentToolTimeoutError(error);

const resolveImageAssetSurface = (
  config: Pick<RebelCoreConfig, 'imageAssetSurface'>,
): 'desktop' | 'cloud' => {
  if (config.imageAssetSurface) return config.imageAssetSurface;
  return process.env.REBEL_SURFACE === 'cloud' ? 'cloud' : 'desktop';
};

const getToolUses = (content: ContentBlock[]): ToolUseBlock[] =>
  content.filter((block): block is ToolUseBlock => block.type === 'tool_use');

const toAssistantMessageParam = (content: ContentBlock[]): ChatMessage => ({
  role: 'assistant',
  content,
});

const toToolResultMessageParam = (toolResults: ToolResultBlock[]): ChatMessage => ({
  role: 'user',
  content: toolResults,
});

const extractScreenshotPathFromToolOutput = (output: string): string | undefined => {
  try {
    const parsed = JSON.parse(output) as unknown;
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      return undefined;
    }

    const path = (parsed as { path?: unknown }).path;
    return typeof path === 'string' && path.trim().length > 0 ? path : undefined;
  } catch {
    return undefined;
  }
};

const toToolResultText = (content: ToolResultBlock['content']): string => {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';

  return content
    .filter((block): block is Extract<ToolResultContentBlock, { type: 'text' }> => block.type === 'text')
    .map((block) => block.text)
    .join('\n');
};

export function estimatePromptTokensForPreflight(params: {
  systemPrompt: SystemPrompt;
  messages: ChatMessage[];
  tools?: ToolDefinition[];
}): number {
  return estimatePromptTokens({
    systemPrompt: params.systemPrompt,
    messages: params.messages,
    tools: params.tools,
  });
}

function getRunawayPromptHardCap(contextWindow?: number): number {
  if (!contextWindow || contextWindow <= 0) return RUNAWAY_PROMPT_HARD_CAP_TOKENS;
  return Math.min(RUNAWAY_PROMPT_HARD_CAP_TOKENS, contextWindow * 2);
}

/**
 * Stage 1 — Deterministic universal output cap (the guarantee).
 *
 * Every freshly executed tool result flows through `executeToolUse` → this
 * transform before BOTH the persisted/UI event emit AND the model-facing
 * tool_result build. If the raw output exceeds `CONTENT_REF_THRESHOLD_BYTES`
 * (200 KiB), we replace it with a byte-bounded head preview plus a clear
 * truncation note. This is the class-eliminating safety net that guarantees no
 * tool_result exceeds the byte cap when sent to the model or persisted, so an
 * oversized output (e.g. raw image bytes decoded as UTF-8 by `Read`) can never
 * overflow context or re-enter `config.messages` on a later turn.
 *
 * Invariants:
 * - Unconditional and self-contained: works with NO workspace/cwd; NEVER falls
 *   back to emitting raw inline output. (File materialisation is Stage 3.)
 * - Byte-based: caps by `Buffer.byteLength(output, 'utf8')`, not char count.
 * - UTF-8-safe: the preview never splits a multi-byte character.
 * - Idempotent w.r.t. already-materialised output (`result.materialized ===
 *   true`, e.g. Bash's ~2 KB preview): such output is passed through untouched,
 *   never re-wrapped. We use the structured flag, not prose sniffing.
 * - Original size accounting (`outputChars`/originalBytes) is preserved by the
 *   caller; only the emitted/model-facing `output` string is shrunk.
 *
 * See docs/plans/260529_guard-large-tool-outputs/PLAN.md § Stage 1.
 */
// The truncation transform itself now lives in the shared, pure
// `@core/services/contentTruncation` module so Stage 1 (this funnel) and Stage 2
// (the provider translators) use ONE implementation. Re-exported here to keep
// the Stage 1 public surface (and its tests) stable.
export {
  UNIVERSAL_TOOL_OUTPUT_CAP_BYTES,
  boundToolOutputForSafety,
  type BoundedToolOutput,
};

/**
 * Screenshot variants of the vision-unsupported placeholder. Both branches end
 * with the shared `VISION_UNSUPPORTED_REPORT_INSTRUCTION` so the model reports
 * the limitation to its caller instead of silently working around it (the
 * historical failure mode: a non-vision model guesses the screenshot's
 * contents or quietly presses on without mentioning it couldn't look).
 */
const buildVisionUnsupportedPlaceholder = (index: number, screenshotPath?: string): string => {
  // "model", not "provider": gating is per-MODEL (supportsImageContent(model)).
  if (screenshotPath) {
    return `[Screenshot ${index + 1} at ${screenshotPath} - vision not supported by the current model; `
      + `use Read with the saved path. ${VISION_UNSUPPORTED_REPORT_INSTRUCTION}]`;
  }
  return `[Screenshot ${index + 1} captured - vision not supported by the current model; `
    + `no path was provided in tool output. ${VISION_UNSUPPORTED_REPORT_INSTRUCTION}]`;
};

export const buildModelFacingToolResultContent = (
  result: ToolExecutionResult,
  supportsImageContent: boolean,
  screenshotPath?: string,
): ToolResultBlock['content'] => {
  // Keep image/tool-result handling aligned with docs/project/UI_CHIEF_DESIGNER_VISUAL_VERIFICATION.md.
  const imageContent = result.imageContent ?? [];
  if (imageContent.length === 0) {
    return result.output;
  }

  if (supportsImageContent) {
    // Universal inline-image backstop (Stage 4 #2): ANY image block — from Read,
    // Screenshot, an MCP tool, or a fallback — is checked against the provider's
    // encoded-size / dimension limits here, mirroring the universal text cap. An
    // oversized block is reduced to a text placeholder so it can never reach a
    // provider and trigger a rejection, regardless of which tool produced it.
    return [
      { type: 'text', text: result.output },
      ...imageContent.map((image, index) => {
        const verdict = checkInlineImageWithinLimits(image.data, image.mimeType);
        if (!verdict.ok) {
          return {
            type: 'text' as const,
            text: buildOversizedImagePlaceholder(index, verdict.reason),
          };
        }
        return {
          type: 'image' as const,
          data: image.data,
          mimeType: image.mimeType,
        };
      }),
    ];
  }

  return [
    { type: 'text', text: result.output },
    ...imageContent.map((_, index) => ({
      type: 'text' as const,
      text: buildVisionUnsupportedPlaceholder(index, screenshotPath),
    })),
  ];
};

const getCompactedToolResultContent = (
  content: ToolResultBlock['content'],
): { content: ToolResultBlock['content']; removedTextChars: number } | null => {
  if (typeof content === 'string') {
    if (content.length <= TOOL_OUTPUT_TRUNCATION_THRESHOLD) return null;
    return {
      content: [{ type: 'text', text: COMPACTED_TEXT_PLACEHOLDER }],
      removedTextChars: content.length,
    };
  }

  if (!Array.isArray(content)) return null;

  const textBlocks: Array<Extract<ToolResultContentBlock, { type: 'text' }>> = [];
  let totalTextChars = 0;
  let imageBlockCount = 0;

  for (const block of content) {
    if (block.type === 'text') {
      textBlocks.push(block);
      totalTextChars += block.text.length;
    } else if (block.type === 'image') {
      imageBlockCount += 1;
    }
  }

  const shouldTruncateText = totalTextChars > TOOL_OUTPUT_TRUNCATION_THRESHOLD;
  const hasImages = imageBlockCount > 0;
  if (!shouldTruncateText && !hasImages) return null;

  return {
    content: [
      ...(shouldTruncateText ? [{ type: 'text' as const, text: COMPACTED_TEXT_PLACEHOLDER }] : textBlocks),
      ...Array.from({ length: imageBlockCount }, () => ({ type: 'text' as const, text: COMPACTED_IMAGE_PLACEHOLDER })),
    ],
    removedTextChars: shouldTruncateText ? totalTextChars : 0,
  };
};

const countImageBlocks = (content: ToolResultBlock['content']): number => {
  if (!Array.isArray(content)) return 0;

  return content.reduce((count, block) => count + (block.type === 'image' ? 1 : 0), 0);
};

/**
 * Error subclass that carries the compacted message history after overflow recovery
 * was exhausted. Allows the orchestrator to retry with a fallback model using
 * the already-compacted context.
 */
export class ContextOverflowError extends ModelError {
  readonly compactedMessages: ChatMessage[];
  constructor(original: ModelError, compactedMessages: ChatMessage[]) {
    super(original.kind, original.message, original.status, original.provider);
    this.compactedMessages = compactedMessages;
    this.stack = original.stack;
  }
}

/**
 * Compact message history by truncating large tool_result outputs in older messages.
 * Keeps the last N turn pairs verbatim to preserve recent context.
 * Pure function — returns a new array, does not mutate input.
 */
export function compactMessageHistory(
  messages: ChatMessage[],
  preserveLastNTurns: number = PRESERVE_LAST_N_TURNS,
  forceCompactCurrentTurn = false,
): { compacted: ChatMessage[]; removedChars: number } {
  // Count turn pairs (assistant + user response). Walk backward to find the
  // boundary between "preserve" and "compact" regions.
  let turnPairCount = 0;
  let preserveFromIndex = 0; // default: preserve everything (idx >= 0 for all)
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].role === 'assistant') {
      turnPairCount++;
      if (turnPairCount >= preserveLastNTurns) {
        preserveFromIndex = i;
        break;
      }
    }
  }

  let latestToolResultMessageIndex = -1;
  if (forceCompactCurrentTurn) {
    for (let i = messages.length - 1; i >= 0; i -= 1) {
      const message = messages[i];
      if (
        message.role === 'user'
        && Array.isArray(message.content)
        && message.content.some((block) => block.type === 'tool_result')
      ) {
        latestToolResultMessageIndex = i;
        break;
      }
    }
  }

  let removedTextChars = 0;
  let removedImageBlocks = 0;
  const compacted = messages.map((msg, idx) => {
    if (idx >= preserveFromIndex && idx !== latestToolResultMessageIndex) return msg;
    if (!Array.isArray(msg.content)) return msg;

    const hasLargeToolResult = msg.content.some(
      (block) => block.type === 'tool_result'
        && getCompactedToolResultContent((block as ToolResultBlock).content) !== null,
    );
    if (!hasLargeToolResult) return msg;

    const newContent = msg.content.map((block) => {
      if (block.type !== 'tool_result') return block;
      const tb = block as ToolResultBlock;
      const compactedToolResult = getCompactedToolResultContent(tb.content);
      if (!compactedToolResult) return block;
      removedTextChars += compactedToolResult.removedTextChars;
      removedImageBlocks += Math.max(
        countImageBlocks(tb.content) - countImageBlocks(compactedToolResult.content),
        0,
      );
      return {
        ...tb,
        content: compactedToolResult.content,
      };
    });
    return { ...msg, content: newContent };
  });

  const removedChars =
    removedTextChars + (removedImageBlocks * IMAGE_BLOCK_TOKEN_COST * APPROX_CHARS_PER_TOKEN);
  return { compacted, removedChars };
}

export type SkeletonResult = SkeletonStripResult<ChatMessage>;

export function buildSkeletonMessages(messages: ChatMessage[]): SkeletonResult {
  return stripBlocksForSkeleton<ChatMessage, ContentBlock>(messages, {
    getRole: (message) => message.role,
    getContent: (message) => message.content,
    buildMessage: (message, content) => ({ ...message, content }),
    buildSentinelMessage: () => ({
      role: 'user',
      content: SKELETON_FALLBACK_USER_TEXT,
    }),
  });
}

const normalizeLoopError = (error: unknown, signal?: AbortSignal): Error => {
  if (signal?.aborted) {
    return createAbortError();
  }

  if (error instanceof ModelError && error.isAbort) {
    return error;
  }

  if (error instanceof Error) {
    if (error.name === 'AbortError') {
      return createAbortError();
    }
    return error;
  }

  return new Error(String(error));
};

const isThinkingLikeBlock = (block: unknown): boolean => {
  if (!block || typeof block !== 'object') return false;
  const type = (block as { type?: unknown }).type;
  return type === 'thinking' || type === 'redacted_thinking';
};

/**
 * Removes thinking/redacted_thinking blocks from older assistant turns while
 * preserving the most recent N assistant turns.
 */
export function stripOldThinkingBlocks(messages: ChatMessage[], keepRecentTurns: number): void {
  if (messages.length === 0) return;

  const assistantIndexes: number[] = [];
  for (let i = 0; i < messages.length; i += 1) {
    const message = messages[i];
    if (message.role === 'assistant' && Array.isArray(message.content)) {
      assistantIndexes.push(i);
    }
  }

  const keepCount = Math.max(keepRecentTurns, 0);
  const stripCount = Math.max(assistantIndexes.length - keepCount, 0);
  if (stripCount === 0) return;

  for (let i = 0; i < stripCount; i += 1) {
    const idx = assistantIndexes[i];
    const message = messages[idx];
    if (!Array.isArray(message.content)) continue;

    const filtered = message.content.filter((block) => !isThinkingLikeBlock(block));
    // Preserve original content when stripping would leave an empty message.
    if (filtered.length > 0) {
      message.content = filtered;
    }
  }
}

export async function runAgentLoop(
  config: RebelCoreConfig,
  executeTool: ExecuteToolFn,
  onEvent: EventHandler,
  opts?: { supportsReasoningReplay?: boolean },
): Promise<{ totalUsage: TokenUsage; turns: number; messageHistory: ChatMessage[] }> {
  let messageHistory: ChatMessage[] = [...config.messages];
  const maxTurns = config.maxTurns ?? Infinity;
  const supportsReasoningReplay = opts?.supportsReasoningReplay ?? false;

  let turns = 0;
  let totalUsage = { ...ZERO_TOKEN_USAGE };
  let compactionAttempts = 0;
  let lastIterationInputTokens = 0;
  let warningEmitted = false;
  let proactiveCompactionFired = false;
  const failureTracker = new ToolFailureTracker();
  const loopStartedAt = Date.now();
  const imageAssetSurface = resolveImageAssetSurface(config);
  let fallbackToolResultEventSeq = 0;
  const nextToolResultEventSeq = (): number =>
    config.nextToolResultEventSeq?.() ?? fallbackToolResultEventSeq++;
  // Stage 1a Item 4 (A3): local counter capping diagnostic-event emits per
  // runAgentLoop invocation. Distinct from failureTracker.getTotalToolCalls()
  // (which counts ALL tool calls); this only counts ERROR-emit budget.
  // turnCallIndex is 1-based for the first emitted error event (A12).
  let toolCallErrorEventsEmitted = 0;

  const hydrationCache = new TurnScopedHydrationCache();
  const contentHydrationCache = new TurnScopedContentHydrationCache();

  try {
    while (turns < maxTurns) {
      assertNotAborted(config.signal);

    try {
      const maxTokens = config.maxTokens ?? DEFAULT_MAX_TOKENS;
      const estimatedInputTokens = estimatePromptTokensForPreflight({
        systemPrompt: config.systemPrompt,
        messages: messageHistory,
        tools: config.tools,
      });
      const hardCapTokens = getRunawayPromptHardCap(config.contextWindow);
      if (estimatedInputTokens > hardCapTokens) {
        log.error(
          {
            estimatedInputTokens,
            hardCapTokens,
            contextWindow: config.contextWindow,
            model: config.model,
            messageCount: messageHistory.length,
          },
          'Runaway prompt preflight cap exceeded — refusing to send API request',
        );
        throw new ModelError(
          'context_overflow',
          `Prompt is too large to send safely (estimated ${estimatedInputTokens} tokens). Try starting a fresh conversation or narrowing the request.`,
          undefined,
        );
      }

      if (
        config.contextWindow
        && estimatedInputTokens + maxTokens > config.contextWindow * PREFLIGHT_CONTEXT_HEADROOM
      ) {
        onEvent({ type: 'recovery:compaction', message: 'Compacting context before sending...' });
        const { compacted, removedChars } = compactMessageHistory(messageHistory, PRESERVE_LAST_N_TURNS);
        if (removedChars > 0) {
          messageHistory = compacted;
          proactiveCompactionFired = false;
          warningEmitted = false;
          log.info(
            {
              estimatedInputTokens,
              maxTokens,
              contextWindow: config.contextWindow,
              removedChars,
              model: config.model,
            },
            'Preflight context check compacted history before provider request',
          );
          continue;
        }

        log.warn(
          {
            estimatedInputTokens,
            maxTokens,
            contextWindow: config.contextWindow,
            model: config.model,
            messageCount: messageHistory.length,
          },
          'Preflight context check exceeded model window and compaction removed nothing',
        );
        throw new ModelError(
          'context_overflow',
          `Prompt is too large for this model's context window (estimated ${estimatedInputTokens} input tokens plus ${maxTokens} output tokens). Try starting a fresh conversation or narrowing the request.`,
          undefined,
        );
      }

      const result = await config.client.stream(
        {
          model: config.model,
          maxTokens,
          systemPrompt: config.systemPrompt,
          messages: messageHistory,
          supportsReasoningReplay,
          ...(config.tools && config.tools.length > 0 ? { tools: config.tools } : {}),
          ...(config.thinking ? { thinking: config.thinking } : {}),
          ...(config.effort ? { effort: config.effort } : {}),
          signal: config.signal,
          ...(config.onRetry ? { onRetry: config.onRetry } : {}),
          ...(config.onStreamActivity ? { onStreamActivity: config.onStreamActivity } : {}),
          sessionId: config.sessionId,
          hydrationCache,
          contentHydrationCache,
        },
        (streamEvent) => {
          if (streamEvent.type === 'text_delta' && streamEvent.text) {
            onEvent({ type: 'assistant:text', text: streamEvent.text });
          }

          if (streamEvent.type === 'thinking_delta' && streamEvent.thinking) {
            onEvent({ type: 'assistant:thinking', thinking: streamEvent.thinking });
          }
        },
      );

      assertNotAborted(config.signal);

      const stopReason = result.stopReason ?? 'unknown';
      const content = result.content;

      // Track per-iteration input tokens for learned limits evidence
      const effectiveInputTokens = getEffectiveInputTokens(result.usage);
      lastIterationInputTokens = effectiveInputTokens;

      // Context budget tracking (zero-cost when contextWindow is undefined)
      const contextUtilization = config.contextWindow
        ? effectiveInputTokens / config.contextWindow
        : undefined;

      if (contextUtilization !== undefined) {
        if (contextUtilization >= 0.85 && !proactiveCompactionFired) {
          proactiveCompactionFired = true;
          onEvent({ type: 'recovery:compaction', message: 'Optimizing context for longer conversation...' });
          const { compacted, removedChars } = compactMessageHistory(messageHistory, PRESERVE_LAST_N_TURNS);
          if (removedChars > 0) {
            messageHistory = compacted;
            log.info({ utilization: contextUtilization, removedChars }, 'Proactive compaction at 85% utilization');
          }
        } else if (contextUtilization >= 0.70 && !warningEmitted) {
          warningEmitted = true;
          log.debug({ utilization: contextUtilization }, 'Context nearing capacity — warning emitted');
          onEvent({ type: 'context:warning', utilization: contextUtilization, message: 'Context nearing capacity' });
        }
      }

      onEvent({ type: 'assistant:message', content });

      turns += 1;
      totalUsage = addUsage(totalUsage, result.usage);
      onEvent({
        type: 'turn:complete',
        usage: result.usage,
        stopReason: result.stopReason,
        model: result.model || config.model,
        ...(result.contextManagementEdits ? { contextManagementEdits: result.contextManagementEdits } : {}),
        ...(contextUtilization !== undefined ? { contextUtilization } : {}),
      });

      messageHistory.push(toAssistantMessageParam(content));

      const toolUses = getToolUses(content);
      // Refusal terminality (Fable 5 Stage 6): when the provider's safety
      // classifier refuses a response (stop_reason: 'refusal', emitted by
      // always-on-thinking models like Fable 5), any tool_use blocks it
      // carries must NOT be executed — acting on refused content would
      // perform real side-effects on behalf of a response the provider
      // declined to stand behind. Exit BEFORE tool execution.
      if (stopReason === 'refusal') {
        log.warn(
          {
            stopReason,
            toolUseCount: toolUses.length,
            model: config.model,
            turns,
          },
          'Model response refused by provider safety classifier — exiting agent loop without executing tool calls',
        );
        break;
      }
      if (toolUses.length === 0 || stopReason === 'end_turn' || stopReason === 'max_tokens') {
        break;
      }

      assertNotAborted(config.signal);

      const toolResultCharsByIndex: Array<number | undefined> = Array.from({ length: toolUses.length });

      const executeToolUse = async (toolUse: ToolUseBlock, toolUseIndex: number): Promise<ToolResultBlock> => {
        onEvent({
          type: 'tool_use:start',
          toolUseId: toolUse.id,
          toolName: toolUse.name,
          input: toolUse.input,
        });

        const toolChildAC = new AbortController();
        const toolChildSignal = toolChildAC.signal;
        const propagateParentAbort = (): void => {
          if (!toolChildAC.signal.aborted) {
            toolChildAC.abort(config.signal?.reason);
          }
        };
        if (config.signal) {
          if (config.signal.aborted) {
            toolChildAC.abort(config.signal.reason);
          } else {
            config.signal.addEventListener('abort', propagateParentAbort, { once: true });
          }
        }
        config.onToolDispatch?.(toolUse.id, toolChildAC);

        let result: ToolExecutionResult;
        try {
          result = await executeTool(toolUse.name, toolUse.input, toolUse.id, toolChildSignal);
        } catch (error) {
          if (toolChildSignal.aborted && !config.signal?.aborted) {
            const reason = toolChildSignal.reason as Error | string | undefined;
            const reasonText = reason instanceof ToolKilledByWatchdogError
              ? reason.judgeReason
              : reason instanceof Error
                ? reason.message
              : (typeof reason === 'string' && reason.length > 0 ? reason : 'cancelled');
            result = {
              output: `Tool was stopped by the time check (${reasonText})`,
              isError: true,
            };
          } else if (isAgentToolTimeoutError(error) && !config.signal?.aborted) {
            result = {
              output: `Subagent ran out of time: ${error.message}. You can try a different approach or break the work into smaller steps.`,
              isError: true,
            };
          } else if (isAbortOrTimeoutError(error) || config.signal?.aborted) {
            throw error;
          } else {
            const messageText = error instanceof Error ? error.message : String(error);
            result = {
              output: `Tool execution failed: ${messageText}`,
              isError: true,
            };
          }
        } finally {
          if (config.signal && !config.signal.aborted) {
            config.signal.removeEventListener('abort', propagateParentAbort);
          }
          config.onToolSettle?.(toolUse.id);
        }

        assertNotAborted(config.signal);

        // Defensive: tool implementations should always return a string
        // `output`, but the type sometimes flows through `unknown` translators
        // (e.g. mock executors in tests) and a `null`/`undefined` here used to
        // crash on `.length`. Coerce to empty string so downstream logic keeps
        // working — the error path will surface through `isError`/structured
        // logs, not through a NPE. See Stage B1a § MEDIUM #5.
        if (typeof result.output !== 'string') {
          result.output = result.output == null ? '' : String(result.output);
        }

        const outputChars = typeof result.outputChars === 'number'
          ? result.outputChars
          : result.output.length;
        toolResultCharsByIndex[toolUseIndex] = outputChars;

        // Stage 1 — Deterministic universal output cap (the guarantee).
        // Apply ONE bounded-output transform here, before BOTH the persisted/UI
        // event emit (below) and the model-facing build (`buildModelFacing...`),
        // so an oversized output can never overflow context nor re-enter
        // `config.messages` on a later turn. Already-materialised output (e.g.
        // Bash's ~2 KB preview, `result.materialized === true`) is passed
        // through untouched. We preserve the ORIGINAL size in `outputChars`
        // (computed above) and in the emitted event so compaction/context-
        // warning accounting stays honest; only the `output` STRING is shrunk.
        // Truncation is unconditional and self-contained — no workspace/cwd is
        // required and we NEVER fall back to raw inline output. File
        // materialisation (recoverable) is Stage 3. See PLAN.md § Stage 1.
        const bounded = boundToolOutputForSafety(
          result.output,
          result.materialized === true,
        );
        if (bounded.truncated) {
          result.output = bounded.output;
          // Preserve original-size accounting: `outputChars` already reflects
          // the original (computed above). Ensure the persisted event also
          // carries the original byte size so downstream math is unaffected.
          if (typeof result.outputChars !== 'number') {
            result.outputChars = outputChars;
          }
          log.info(
            {
              toolUseId: toolUse.id,
              toolName: toolUse.name,
              originalBytes: bounded.originalBytes,
              boundedBytes: Buffer.byteLength(result.output, 'utf8'),
              capBytes: UNIVERSAL_TOOL_OUTPUT_CAP_BYTES,
            },
            'tool-output:universal-cap:truncated',
          );
        }

        const imageContent = result.imageContent;
        const hasImageContent = !!(imageContent && imageContent.length > 0);
        let imageRef = result.imageRef ?? [];
        if (
          hasImageContent
          && imageContent
          && imageRef.length === 0
          && config.sessionId
          && config.turnId
        ) {
          try {
            const materialization = await materializeImageRefsForEvent(
              {
                sessionId: config.sessionId,
                turnId: config.turnId,
                eventSeq: nextToolResultEventSeq(),
                imageContent,
                surface: imageAssetSurface,
              },
              getAssetStore(),
            );
            imageRef = materialization.refs;
            if (materialization.failures.length > 0) {
              log.warn(
                {
                  toolUseId: toolUse.id,
                  toolName: toolUse.name,
                  failureCount: materialization.failures.length,
                  failures: materialization.failures.map((failure) => ({
                    index: failure.index,
                    reason: failure.reason,
                  })),
                },
                'Image ref materialization had failures; continuing with legacy image payload',
              );
            }
          } catch (error) {
            log.warn(
              {
                toolUseId: toolUse.id,
                toolName: toolUse.name,
                err: error instanceof Error ? error.message : String(error),
              },
              'Image ref materialization setup failed; continuing with legacy image payload',
            );
            imageRef = [];
          }
        }

        // Stage B1a: offload large opaque text output to the session-scoped
        // ContentStore. Mirrors the image-ref materialization above; only
        // engaged for outputs above the 200 KB threshold so small tool
        // results stay inline. NEVER emit a contentRef pointing to nothing
        // — on any failure we fall through with the original output intact.
        // See docs/plans/260518_cloud_sync_reconciliation_hardening.md § B1a.
        let contentRef: import('@shared/types/agent').ContentRef[] | undefined;
        const isOversizedTextOutput = typeof result.output === 'string'
          && Buffer.byteLength(result.output, 'utf8') > CONTENT_REF_THRESHOLD_BYTES;
        // Capability gate (HIGH #5): refuse to offload when the cloud
        // counterpart has not advertised `session-content-refs`. We err on
        // the side of staying inline so a stale or unrecognised server can
        // never observe a contentRef pointing to content it cannot fetch.
        // `null` (no probe / pre-negotiation) is treated as "not
        // advertised": the safe fallback is to keep bytes inline until the
        // cloud has explicitly declared that it understands content refs.
        const cloudCapabilities = peekCloudCapabilities();
        const cloudSupportsContentRefs = cloudCapabilities !== null
          && cloudCapabilities.includes('session-content-refs');
        if (isOversizedTextOutput && !cloudSupportsContentRefs) {
          log.info(
            {
              toolUseId: toolUse.id,
              toolName: toolUse.name,
              outputBytes: Buffer.byteLength(result.output, 'utf8'),
              capability: 'session-content-refs',
            },
            'content-store:capability-not-advertised:fallback-inline',
          );
        }
        if (
          isOversizedTextOutput
          && cloudSupportsContentRefs
          && config.sessionId
          && config.turnId
        ) {
          try {
            const materialization = await materializeContentRefsForEvent(
              {
                sessionId: config.sessionId,
                turnId: config.turnId,
                eventSeq: nextToolResultEventSeq(),
                content: [{ type: 'text', text: result.output, mimeType: 'text/plain' }],
                surface: imageAssetSurface,
              },
              getContentStore(),
            );
            const refs = materialization.refs.filter(
              (ref): ref is NonNullable<typeof ref> => ref !== null,
            );
            if (refs.length > 0) {
              contentRef = refs;
            }
            if (materialization.failures.length > 0) {
              log.warn(
                {
                  toolUseId: toolUse.id,
                  toolName: toolUse.name,
                  failureCount: materialization.failures.length,
                  failures: materialization.failures.map((failure) => ({
                    index: failure.index,
                    reason: failure.reason,
                  })),
                },
                'Content ref materialization had failures; keeping inline tool output',
              );
            }
          } catch (error) {
            log.warn(
              {
                toolUseId: toolUse.id,
                toolName: toolUse.name,
                err: error instanceof Error ? error.message : String(error),
              },
              'Content ref materialization setup failed; keeping inline tool output',
            );
            contentRef = undefined;
          }
        }

        onEvent({
          type: 'tool_use:result',
          toolUseId: toolUse.id,
          output: result.output,
          isError: result.isError,
          ...(typeof result.outputChars === 'number' ? { outputChars: result.outputChars } : {}),
          ...(result.imageContent && result.imageContent.length > 0
            ? { imageContent: result.imageContent }
            : {}),
          ...(hasImageContent ? { imageRef } : {}),
          ...(contentRef && contentRef.length > 0 ? { contentRef } : {}),
          ...(result.meta !== undefined ? { meta: result.meta } : {}),
          ...(result.structuredContent !== undefined ? { structuredContent: result.structuredContent } : {}),
        });

        // EXPLICIT invocation with the per-request model (260610 incident): the
        // capability is a function — a bare (non-invoked) read is always truthy
        // and would silently bypass the gate.
        const supportsImageContent = config.client.capabilities.supportsImageContent(config.model);
        const screenshotPath = hasImageContent
          ? extractScreenshotPathFromToolOutput(result.output)
          : undefined;
        if (hasImageContent && !supportsImageContent) {
          log.warn(
            {
              toolUseId: toolUse.id,
              toolName: toolUse.name,
              imageBlockCount: result.imageContent?.length ?? 0,
              screenshotPath,
              model: config.model,
            },
            'Model does not support image content; substituting text placeholders',
          );
        }

        return {
          type: 'tool_result' as const,
          tool_use_id: toolUse.id,
          content: buildModelFacingToolResultContent(result, supportsImageContent, screenshotPath),
          is_error: result.isError,
        };
      };

      const toolResultsByIndex: Array<ToolResultBlock | undefined> = Array.from({ length: toolUses.length });
      const agentTaskIndexes: number[] = [];
      const agentTasks: Array<(signal: AbortSignal | undefined) => Promise<ToolResultBlock>> = [];
      const nonAgentExecutions: Array<Promise<void>> = [];
      const parallelRequested = toolUses.filter((toolUse) => isSubAgentToolName(toolUse.name)).length;
      const shouldEmitParallelStatus = parallelRequested >= 2;
      const parallelBatchStartedAt = shouldEmitParallelStatus ? Date.now() : null;
      let parallelRunning = 0;
      let progressSucceeded = 0;
      let progressFailed = 0;
      let progressAborted = 0;
      let parallelSucceeded = 0;
      let parallelFailed = 0;
      let parallelAborted = 0;
      let parallelSkipped = 0;
      const startedAgentIndexes = new Set<number>();

      if (shouldEmitParallelStatus) {
        emitParallelSubagentsStatus(onEvent, PARALLEL_SUBAGENTS_START_PREFIX, {
          requested: parallelRequested,
          cap: PARALLEL_AGENT_CAP,
        });
      }

      for (const [index, toolUse] of toolUses.entries()) {
        if (isSubAgentToolName(toolUse.name)) {
          agentTaskIndexes.push(index);
          // Intentionally ignore runWithLimit task signal here; executeToolUse
          // reads config.signal directly, and Agent tool execution still honors
          // abort through context.signal within executeTool.
          agentTasks.push(async () => {
            parallelRunning += 1;
            try {
              const toolResult = await executeToolUse(toolUse, index);
              if (toolResult.is_error) {
                progressFailed += 1;
              } else {
                progressSucceeded += 1;
              }
              return toolResult;
            } catch (error) {
              if (isAbortOrTimeoutError(error) || config.signal?.aborted) {
                progressAborted += 1;
              } else {
                progressFailed += 1;
              }
              throw error;
            } finally {
              parallelRunning -= 1;
              if (shouldEmitParallelStatus) {
                const pending = Math.max(
                  parallelRequested - parallelRunning - progressSucceeded - progressFailed - progressAborted,
                  0,
                );
                emitParallelSubagentsStatus(onEvent, PARALLEL_SUBAGENTS_PROGRESS_PREFIX, {
                  running: parallelRunning,
                  succeeded: progressSucceeded,
                  failed: progressFailed,
                  pending,
                });
              }
            }
          });
          continue;
        }

        nonAgentExecutions.push(
          executeToolUse(toolUse, index)
            .then((toolResult) => {
              toolResultsByIndex[index] = toolResult;
            })
            .catch((error) => {
              // Per-call fault isolation, mirroring the sub-agent path's
              // settled semantics (runWithLimit, see ~1020-1056). Without this,
              // a single non-agent tool-call rejection rejects the whole
              // `Promise.all` batch (~1073) → re-thrown at the turn catch
              // (~1293) → unhandled rejection in the detached run chain, taking
              // down siblings/the worker.
              //
              // Invariant 1 (abort teardown): a genuine abort/cancel/timeout
              // MUST still tear the turn down — re-throw it unchanged so the
              // turn-level handling stays identical to before. We only fold
              // NON-abort errors into a recoverable tool_result.
              if (isAbortOrTimeoutError(error) || config.signal?.aborted) {
                throw error;
              }
              // Invariant 2 (tool_use↔tool_result pairing): always populate
              // toolResultsByIndex[index] so the unresolvedToolUseIndex check
              // (~1077-1080) passes — every tool_use gets exactly one
              // tool_result. This matches the error shape produced inside
              // executeToolUse's own catch (~696-699) /
              // mcpClient.handleToolCallError.
              const messageText = error instanceof Error ? error.message : String(error);
              toolResultsByIndex[index] = {
                type: 'tool_result' as const,
                tool_use_id: toolUse.id,
                content: `Tool execution failed: ${messageText}`,
                is_error: true,
              };
            }),
        );
      }

      if (agentTasks.length > PARALLEL_AGENT_CAP) {
        log.info(
          {
            requested: agentTasks.length,
            cap: PARALLEL_AGENT_CAP,
            queued: agentTasks.length - PARALLEL_AGENT_CAP,
          },
          'agent_fanout_cap_engaged',
        );
      }

      const wrappedAgentTasks = agentTasks.map((task, agentIdx) => async (signal: AbortSignal | undefined) => {
        startedAgentIndexes.add(agentIdx);
        return task(signal);
      });

      const agentExecution = runWithLimit(PARALLEL_AGENT_CAP, wrappedAgentTasks, { signal: config.signal })
        .then((agentResults) => {
          let firstRejectedReason: unknown;
          for (let agentIndex = 0; agentIndex < agentResults.length; agentIndex += 1) {
            const toolUseIndex = agentTaskIndexes[agentIndex];
            const toolUse = toolUses[toolUseIndex];
            if (!toolUse) {
              throw new Error(
                `Missing tool_use at index ${toolUseIndex} while materializing capped ${SUB_AGENT_TOOL_NAMES.join('/')} results`,
              );
            }

            const agentResult = agentResults[agentIndex];
            if (agentResult.status === 'rejected') {
              if (!startedAgentIndexes.has(agentIndex)) {
                parallelSkipped += 1;
              } else if (isAbortOrTimeoutError(agentResult.reason) || config.signal?.aborted) {
                parallelAborted += 1;
              } else {
                parallelFailed += 1;
              }
              if (firstRejectedReason === undefined) {
                firstRejectedReason = agentResult.reason;
              }
              continue;
            }

            toolResultsByIndex[toolUseIndex] = agentResult.value;
            if (agentResult.value.is_error) {
              parallelFailed += 1;
            } else {
              parallelSucceeded += 1;
            }
          }

          if (firstRejectedReason !== undefined) {
            throw firstRejectedReason;
          }
        });

      const agentExecutionWithStatus = agentExecution.finally(() => {
        if (!shouldEmitParallelStatus || parallelBatchStartedAt === null) {
          return;
        }
        emitParallelSubagentsStatus(onEvent, PARALLEL_SUBAGENTS_COMPLETE_PREFIX, {
          requested: parallelRequested,
          succeeded: parallelSucceeded,
          failed: parallelFailed,
          aborted: parallelAborted,
          skipped: parallelSkipped,
          durationMs: Math.max(Date.now() - parallelBatchStartedAt, 0),
        });
      });

      await Promise.all([...nonAgentExecutions, agentExecutionWithStatus]);

      assertNotAborted(config.signal);

      const unresolvedToolUseIndex = toolResultsByIndex.findIndex((toolResult) => toolResult === undefined);
      if (unresolvedToolUseIndex >= 0) {
        throw new Error(`Missing tool result for tool_use index ${unresolvedToolUseIndex}`);
      }

      const toolResults = toolResultsByIndex as ToolResultBlock[];
      const cumulativeToolResultChars = toolResults.reduce((totalChars, toolResult, index) => {
        const explicitChars = toolResultCharsByIndex[index];
        if (typeof explicitChars === 'number' && Number.isFinite(explicitChars) && explicitChars >= 0) {
          return totalChars + explicitChars;
        }
        return totalChars + toToolResultText(toolResult.content).length;
      }, 0);
      const agentToolCount = agentTasks.length;
      const nonAgentToolCount = toolUses.length - agentToolCount;

      if (agentToolCount > 0 || toolUses.length >= 2) {
        log.info(
          {
            cumulativeToolResultChars,
            agentToolCount,
            nonAgentToolCount,
          },
          'parallel-tool-results-summary',
        );
      }

      messageHistory.push(toToolResultMessageParam(toolResults));

      if (config.contextWindow && !proactiveCompactionFired) {
        const projectedNextInputTokens =
          effectiveInputTokens + (cumulativeToolResultChars / CHARS_PER_TOKEN_ESTIMATE);
        const projectedUtilization = projectedNextInputTokens / config.contextWindow;

        if (projectedUtilization >= 0.85) {
          proactiveCompactionFired = true;
          onEvent({ type: 'recovery:compaction', message: 'Optimizing context for longer conversation...' });
          const { compacted, removedChars } = compactMessageHistory(messageHistory, PRESERVE_LAST_N_TURNS, true);
          if (removedChars > 0) {
            messageHistory = compacted;
          }
          log.info(
            {
              projectedUtilization,
              projectedNextInputTokens,
              cumulativeToolResultChars,
              removedChars,
            },
            'Post-fanout projected utilization crossed proactive compaction threshold',
          );
        }
      }

      // --- Circuit breaker: track tool failures and inject advisories ---
      const toolNameByUseId = new Map(toolUses.map((toolUse) => [toolUse.id, toolUse.name] as const));
      const errorBatch: Array<{ toolName: string; errorText: string }> = [];
      let successfulToolCount = 0;
      for (const tr of toolResults) {
        if (tr.is_error) {
          const toolName = toolNameByUseId.get(tr.tool_use_id) ?? 'unknown';
          const errorText = toToolResultText(tr.content);

          // A3/A12: emit tool_call_error BEFORE recordToolError so the repeat
          // check reads pre-update state. Capped per turn to keep the ledger
          // bounded for pathological loops.
          if (toolCallErrorEventsEmitted < MAX_TOOL_CALL_ERROR_EMITS_PER_TURN) {
            const isRepeat = failureTracker.isRepeatOfNormalizedSignature(toolName, errorText);
            toolCallErrorEventsEmitted += 1;
            appendDiagnosticEvent({
              kind: 'tool_call_error',
              data: {
                toolNameHash: hashToolName(toolName),
                isRepeatOfNormalizedSignature: isRepeat,
                turnCallIndex: toolCallErrorEventsEmitted,
              },
            });
          }
          errorBatch.push({ toolName, errorText });
        } else {
          successfulToolCount += 1;
        }
      }
      // Batch semantics are intentionally order-insensitive for concurrent fan-out:
      // dedupe error bursts first, then treat any successes in the same batch as
      // streak breakers so result ordering does not affect advisory behavior.
      failureTracker.recordToolErrorBatch(errorBatch);
      for (let index = 0; index < successfulToolCount; index += 1) {
        failureTracker.recordToolSuccess();
      }

      const advisory = failureTracker.getAdvisory();
      if (advisory) {
        appendDiagnosticEvent({
          kind: 'tool_advisory',
          data: {
            advisory: advisory.type,
            totalToolCalls: failureTracker.getTotalToolCalls(),
          },
        });

        if (advisory.type === 'hard_budget') {
          log.warn({ totalToolCalls: failureTracker.getTotalToolCalls() }, 'Hard tool call budget reached — aborting turn');
          appendDiagnosticEvent({
            kind: 'abort_event',
            data: {
              reason: 'budget_hard',
              durationBucketMs: bucketAbortDurationMs(Date.now() - loopStartedAt),
            },
          });
          onEvent({ type: 'turn:error', error: new Error(advisory.message) });
          throw createAbortError(advisory.message);
        }

        log.info({ advisoryType: advisory.type, totalToolCalls: failureTracker.getTotalToolCalls() }, 'Circuit breaker advisory injected');
        messageHistory.push({
          role: 'user',
          content: advisory.message,
        });
      }

      // Between-turn processing: clean up context before the next iteration.
      // Always strip old thinking blocks (safe, reduces context bloat).
      const preStripThinkingCount = messageHistory.reduce((count, msg) => {
        if (msg.role === 'assistant' && Array.isArray(msg.content)) {
          return count + msg.content.filter((b) => isThinkingLikeBlock(b)).length;
        }
        return count;
      }, 0);
      stripOldThinkingBlocks(messageHistory, getThinkingRetentionTurns(supportsReasoningReplay));
      const postStripThinkingCount = messageHistory.reduce((count, msg) => {
        if (msg.role === 'assistant' && Array.isArray(msg.content)) {
          return count + msg.content.filter((b) => isThinkingLikeBlock(b)).length;
        }
        return count;
      }, 0);
      const thinkingBlocksStripped = preStripThinkingCount - postStripThinkingCount;
      if (thinkingBlocksStripped > 0) {
        log.debug({ thinkingBlocksStripped }, 'Stripped old thinking blocks');
      }

      if (config.betweenTurns) {
        const hookStart = Date.now();
        try {
          await config.betweenTurns(messageHistory, result.usage);
          log.debug({ durationMs: Date.now() - hookStart }, 'Between-turn hook completed');
        } catch (error) {
          const messageText = error instanceof Error ? error.message : String(error);
          log.warn({ durationMs: Date.now() - hookStart, err: messageText }, 'Between-turn hook failed');
          onEvent({
            type: 'warning',
            category: 'mcp',
            message: `Between-turn hook failed: ${messageText}`,
          });
        }
      }

      if (config.onIterationEnd) {
        try {
          await config.onIterationEnd();
        } catch (error) {
          const messageText = error instanceof Error ? error.message : String(error);
          log.warn({ err: messageText }, 'onIterationEnd hook failed');
        }
      }
    } catch (error) {
      const normalizedError = normalizeLoopError(error, config.signal);

      // Context overflow recovery: compact message history and retry
      if (normalizedError instanceof ModelError
          && normalizedError.kind === 'context_overflow'
          && compactionAttempts < MAX_COMPACTION_ATTEMPTS) {
        compactionAttempts++;
        onEvent({ type: 'recovery:compaction', message: 'Compacting context to continue...' });

        const { compacted, removedChars } = compactMessageHistory(messageHistory, PRESERVE_LAST_N_TURNS);

        // No-op detection: if compaction didn't remove anything, stop retrying.
        // Do NOT emit turn:error here — the orchestrator may still try a fallback model.
        if (removedChars === 0) {
          log.warn({ attempt: compactionAttempts }, 'Compaction removed nothing — escalating');
          throw new ContextOverflowError(normalizedError, messageHistory);
        }

        messageHistory = compacted;

        // Reset proactive flags after compaction so they can fire again
        proactiveCompactionFired = false;
        warningEmitted = false;

        // Record learned limit evidence from last successful iteration.
        // Stage 2: pass `model` so the writer can resolve a profile target.
        // `profileId` is `null` here — the rebelCoreQuery wrapper closes over
        // its `activeExecutionProfileId` and supplies the right value before
        // forwarding to `recordContextOverflowOnProfile`.
        if (lastIterationInputTokens > 0) {
          config.onContextOverflow?.({
            model: config.model,
            profileId: null,
            lastKnownInputTokens: lastIterationInputTokens,
          });
        }

        log.info(
          { attempt: compactionAttempts, removedChars, historyLen: messageHistory.length },
          'Context overflow — compacted and retrying',
        );
        continue;
      }

      // Circuit breaker: compaction attempts exhausted — propagate with compacted messages.
      // Do NOT emit turn:error — the orchestrator may try a fallback model first.
      if (normalizedError instanceof ModelError && normalizedError.kind === 'context_overflow') {
        throw new ContextOverflowError(normalizedError, messageHistory);
      }

      onEvent({ type: 'turn:error', error: normalizedError });
      throw normalizedError;
    }
  }

    if (!config.suppressLoopComplete) {
      onEvent({
        type: 'loop:complete',
        totalUsage,
      });
    }

    return {
      totalUsage,
      turns,
      messageHistory,
    };
  } finally {
    hydrationCache.clear();
    contentHydrationCache.clear();
  }
}
