#!/usr/bin/env npx tsx
/**
 * CI validation: preload IPC bridge export -> exposure -> Window type parity.
 *
 * Static analysis only:
 * - Parses `src/preload/ipcBridge.ts` to discover generated domain API exports.
 * - Parses `src/preload/index.ts` to discover contextBridge.exposeInMainWorld()
 *   preload exposures.
 * - Parses `src/renderer/env.d.ts` to discover ambient Window fields.
 *
 * Reports (blocking errors):
 * - exposed preload surface without an ipcBridge export or documented exception
 * - exposed preload surface without a Window ambient field or documented exception
 * - curated renderer-facing connector domain without the full export/expose/type chain
 *
 * Known debt allowlists are intentionally narrow. Do not extend them without
 * resolving the product decision captured in
 * docs/plans/260607_oss-scrub-regression-class/PLAN.md Stage 3.
 */

import { readFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as ts from 'typescript';

export interface IpcBridgeExposureParityPaths {
  ipcBridgeFile: string;
  preloadFile: string;
  rendererEnvFile: string;
}

export interface Exposure {
  name: string;
  valueExpression: string;
  file: string;
  line: number;
}

export interface WindowField {
  name: string;
  typeText: string;
  file: string;
  line: number;
}

export interface BridgeExportException {
  name: string;
  reason: string;
  allowMissingWindowType?: boolean;
}

export interface LegacyAliasException extends BridgeExportException {
  target: string;
  allowMissingWindowType?: boolean;
}

export interface ConnectorDomainRequirement {
  name: string;
  reason: string;
}

export interface KnownDebtAllowlistEntry {
  name: string;
  allowMissingExposure?: boolean;
  allowMissingWindowType?: boolean;
  reason: string;
}

export interface MainOnlyBridgeExport {
  name: string;
  reason: string;
}

export interface StaleAllowlistEntry {
  name: string;
  allowlist: string;
  reason: string;
}

export interface FindIpcBridgeExposureParityViolationsOptions {
  repoRoot?: string;
  paths?: Partial<IpcBridgeExposureParityPaths>;
  readFile?: (absolutePath: string) => string;
  legacyAliases?: readonly LegacyAliasException[];
  nonIpcBridgeExposures?: readonly BridgeExportException[];
  connectorDomains?: readonly ConnectorDomainRequirement[];
  knownDebtAllowlist?: readonly KnownDebtAllowlistEntry[];
  mainOnlyBridgeExports?: readonly MainOnlyBridgeExport[];
}

export interface FindIpcBridgeExposureParityViolationsResult {
  bridgeExports: string[];
  exposures: Exposure[];
  windowFields: WindowField[];
  exposedWithoutBridgeExport: Exposure[];
  exposedWithoutWindowType: Exposure[];
  legacyAliasTargetViolations: string[];
  connectorDomainValueBindingViolations: string[];
  connectorDomainsMissingExport: ConnectorDomainRequirement[];
  connectorDomainsMissingExposure: ConnectorDomainRequirement[];
  connectorDomainsMissingWindowType: ConnectorDomainRequirement[];
  bridgeExportClassificationConflicts: string[];
  unclassifiedBridgeExports: string[];
  mainOnlyBridgeExportsExposed: string[];
  staleAllowlistEntries: StaleAllowlistEntry[];
  warnings: string[];
}

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PLAN_REF = 'docs/plans/260607_oss-scrub-regression-class/PLAN.md Stage 3';

const DEFAULT_PATHS: IpcBridgeExposureParityPaths = {
  ipcBridgeFile: 'src/preload/ipcBridge.ts',
  preloadFile: 'src/preload/index.ts',
  rendererEnvFile: 'src/renderer/env.d.ts',
};

/**
 * Legacy aliases intentionally exposed in preload even though the generated
 * bridge exports only the canonical target name.
 */
const LEGACY_ALIAS_EXCEPTIONS: readonly LegacyAliasException[] = [
  {
    name: 'workspaceApi',
    target: 'libraryApi',
    allowMissingWindowType: true,
    reason: `Legacy alias for libraryApi kept for backward compatibility; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'tasksApi',
    target: 'inboxApi',
    reason: `Legacy alias for inboxApi kept for backward compatibility; tracked by ${PLAN_REF}.`,
  },
];

/**
 * Preload surfaces that are locally defined in src/preload/index.ts rather than
 * generated by src/preload/ipcBridge.ts. These are not connector-domain bridge
 * exports, but they still need Window typing unless explicitly noted.
 */
const NON_IPC_BRIDGE_EXPOSURES: readonly BridgeExportException[] = [
  {
    name: '__SENTRY_IPC__',
    reason: `Sentry preload integration surface, not a Rebel IPC connector domain; tracked by ${PLAN_REF}.`,
  },
  {
    name: '__rebelDev',
    allowMissingWindowType: true,
    reason: `Development-only diagnostic surface, not a Rebel IPC connector domain; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'e2eApi',
    reason: `E2E-only readiness/control surface defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'emergencyApi',
    reason: `Emergency quit/relaunch surface defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'api',
    reason: `Legacy flat API surface defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'safetyPromptSubscriptions',
    reason: `Push-subscription helper surface defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'safetyActivityLogSubscriptions',
    reason: `Push-subscription helper surface defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'btsSubscriptions',
    reason: `Push-subscription helper surface defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'appBridgeSubscriptions',
    allowMissingWindowType: true,
    reason: `Browser-extension push-subscription helper defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'userEngagementApi',
    reason: `Renderer engagement helper defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'fileApi',
    reason: `File helper surface defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
  {
    name: 'electronEnv',
    reason: `Runtime environment metadata surface defined in preload, not generated by ipcBridge; tracked by ${PLAN_REF}.`,
  },
];

function rendererFacingBridgeExport(name: string): ConnectorDomainRequirement {
  return {
    name,
    reason: `Renderer-facing ipcBridge domain; full export/exposure/Window chain required by ${PLAN_REF}.`,
  };
}

/**
 * Explicit SSOT for ipcBridge *Api exports that are supposed to be reachable
 * from the renderer. Keeping the current export set classified here prevents a
 * future scrub from silencing the guard by removing a domain from a narrower
 * connector-only list.
 */
const RENDERER_FACING_CONNECTOR_DOMAINS: readonly ConnectorDomainRequirement[] = [
  rendererFacingBridgeExport('achievementsApi'),
  rendererFacingBridgeExport('agentApi'),
  rendererFacingBridgeExport('agentErrorApi'),
  rendererFacingBridgeExport('appApi'),
  rendererFacingBridgeExport('appBridgeApi'),
  rendererFacingBridgeExport('authApi'),
  rendererFacingBridgeExport('automationsApi'),
  rendererFacingBridgeExport('bugReportApi'),
  rendererFacingBridgeExport('calendarApi'),
  rendererFacingBridgeExport('cloudApi'),
  rendererFacingBridgeExport('cloudContinuityApi'),
  rendererFacingBridgeExport('codexApi'),
  rendererFacingBridgeExport('communityEventsApi'),
  rendererFacingBridgeExport('communityVideoRecsApi'),
  rendererFacingBridgeExport('contributionApi'),
  rendererFacingBridgeExport('dailySparkApi'),
  rendererFacingBridgeExport('dashboardApi'),
  rendererFacingBridgeExport('demoApi'),
  rendererFacingBridgeExport('diagnosticsApi'),
  rendererFacingBridgeExport('discourseApi'),
  rendererFacingBridgeExport('errorApi'),
  rendererFacingBridgeExport('errorRecoveryApi'),
  rendererFacingBridgeExport('exportApi'),
  rendererFacingBridgeExport('feedbackApi'),
  rendererFacingBridgeExport('fileConversationApi'),
  rendererFacingBridgeExport('focusApi'),
  rendererFacingBridgeExport('foldersApi'),
  rendererFacingBridgeExport('githubApi'),
  rendererFacingBridgeExport('googleWorkspaceApi'),
  rendererFacingBridgeExport('heroChoiceApi'),
  rendererFacingBridgeExport('htmlPreviewTrustApi'),
  rendererFacingBridgeExport('hubspotApi'),
  rendererFacingBridgeExport('identityApi'),
  rendererFacingBridgeExport('inboundTriggersApi'),
  rendererFacingBridgeExport('inboxApi'),
  rendererFacingBridgeExport('libraryApi'),
  rendererFacingBridgeExport('localInferenceApi'),
  rendererFacingBridgeExport('localSttApi'),
  rendererFacingBridgeExport('mcpAppsApi'),
  rendererFacingBridgeExport('meetingBotApi'),
  rendererFacingBridgeExport('memoryApi'),
  rendererFacingBridgeExport('microsoftApi'),
  rendererFacingBridgeExport('migrationApi'),
  rendererFacingBridgeExport('miscApi'),
  rendererFacingBridgeExport('officeSidecarApi'),
  rendererFacingBridgeExport('openRouterApi'),
  rendererFacingBridgeExport('operatorsApi'),
  rendererFacingBridgeExport('permissionsApi'),
  rendererFacingBridgeExport('physicalRecordingApi'),
  rendererFacingBridgeExport('plaudApi'),
  rendererFacingBridgeExport('pluginsApi'),
  rendererFacingBridgeExport('safetyActivityLogApi'),
  rendererFacingBridgeExport('safetyApi'),
  rendererFacingBridgeExport('safetyPromptApi'),
  rendererFacingBridgeExport('salesforceApi'),
  rendererFacingBridgeExport('scratchpadApi'),
  rendererFacingBridgeExport('searchApi'),
  rendererFacingBridgeExport('sessionsApi'),
  rendererFacingBridgeExport('settingsApi'),
  rendererFacingBridgeExport('skillHistoryApi'),
  rendererFacingBridgeExport('skillsApi'),
  rendererFacingBridgeExport('slackApi'),
  rendererFacingBridgeExport('spaceMaintenanceApi'),
  rendererFacingBridgeExport('subscriptionApi'),
  rendererFacingBridgeExport('systemHealthApi'),
  rendererFacingBridgeExport('systemImprovementApi'),
  rendererFacingBridgeExport('timeSavedApi'),
  rendererFacingBridgeExport('todoistApi'),
  rendererFacingBridgeExport('usageApi'),
  rendererFacingBridgeExport('useCaseLibraryApi'),
  rendererFacingBridgeExport('userTasksApi'),
  rendererFacingBridgeExport('versionApi'),
  rendererFacingBridgeExport('voiceApi'),
];

/**
 * ipcBridge *Api exports that are intentionally exported for main/preload
 * composition but not exposed to the renderer. The current tree has no clean
 * main-only *Api exports: communityApi and zendeskApi are tracked as known debt
 * below because their product direction is still unresolved.
 */
const MAIN_ONLY_BRIDGE_EXPORTS: readonly MainOnlyBridgeExport[] = [];

/**
 * Known debt only. Do not extend this list. Each entry must reference
 * docs/plans/260607_oss-scrub-regression-class because this allowlist exists
 * solely to let the guard pass on the current tree while keeping the debt visible.
 */
const KNOWN_DEBT_ALLOWLIST: readonly KnownDebtAllowlistEntry[] = [
  {
    name: 'communityApi',
    allowMissingExposure: true,
    allowMissingWindowType: true,
    reason: `Known debt - export-only drift pending product decision in ${PLAN_REF}; do not extend.`,
  },
  {
    name: 'quickCaptureApi',
    allowMissingWindowType: true,
    reason: `Known debt - exposed but untyped in Window pending cleanup in ${PLAN_REF}; do not extend.`,
  },
  {
    name: 'zendeskApi',
    allowMissingExposure: true,
    allowMissingWindowType: true,
    reason: `Known debt - export-only drift pending product decision in ${PLAN_REF}; do not extend.`,
  },
];

function resolvePaths(
  repoRoot: string,
  overrides?: Partial<IpcBridgeExposureParityPaths>,
): IpcBridgeExposureParityPaths {
  const merged: IpcBridgeExposureParityPaths = { ...DEFAULT_PATHS, ...(overrides ?? {}) };
  return {
    ipcBridgeFile: resolve(repoRoot, merged.ipcBridgeFile),
    preloadFile: resolve(repoRoot, merged.preloadFile),
    rendererEnvFile: resolve(repoRoot, merged.rendererEnvFile),
  };
}

function createSourceFile(filePath: string, source: string): ts.SourceFile {
  return ts.createSourceFile(filePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
}

function hasExportModifier(node: ts.Node): boolean {
  return ts.canHaveModifiers(node)
    && (ts.getModifiers(node) ?? []).some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword);
}

function getPropertyNameKey(name: ts.PropertyName): string | null {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNoSubstitutionTemplateLiteral(name)) {
    return name.text;
  }
  if (ts.isComputedPropertyName(name)) {
    const expression = name.expression;
    if (ts.isStringLiteral(expression) || ts.isNoSubstitutionTemplateLiteral(expression)) {
      return expression.text;
    }
  }
  return null;
}

function getLine(sourceFile: ts.SourceFile, node: ts.Node): number {
  return sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line + 1;
}

function collectIpcBridgeExports(params: {
  filePath: string;
  source: string;
}): Set<string> {
  const sourceFile = createSourceFile(params.filePath, params.source);
  const exports = new Set<string>();

  for (const statement of sourceFile.statements) {
    if (!ts.isVariableStatement(statement) || !hasExportModifier(statement)) continue;
    for (const declaration of statement.declarationList.declarations) {
      if (ts.isIdentifier(declaration.name)) {
        exports.add(declaration.name.text);
      }
    }
  }

  return exports;
}

function isContextBridgeExposeInMainWorldCall(node: ts.CallExpression): boolean {
  if (!ts.isPropertyAccessExpression(node.expression)) return false;
  if (node.expression.name.text !== 'exposeInMainWorld') return false;
  return ts.isIdentifier(node.expression.expression) && node.expression.expression.text === 'contextBridge';
}

function collectContextBridgeExposures(params: {
  filePath: string;
  source: string;
  repoRoot: string;
}): Exposure[] {
  const sourceFile = createSourceFile(params.filePath, params.source);
  const exposures: Exposure[] = [];

  const visit = (node: ts.Node): void => {
    if (ts.isCallExpression(node) && isContextBridgeExposeInMainWorldCall(node)) {
      const [nameArgument, valueArgument] = node.arguments;
      if (nameArgument && (ts.isStringLiteral(nameArgument) || ts.isNoSubstitutionTemplateLiteral(nameArgument))) {
        exposures.push({
          name: nameArgument.text,
          valueExpression: valueArgument ? valueArgument.getText(sourceFile) : '<missing>',
          file: relative(params.repoRoot, params.filePath),
          line: getLine(sourceFile, node),
        });
      }
    }
    ts.forEachChild(node, visit);
  };

  visit(sourceFile);
  return exposures.sort((a, b) => a.name.localeCompare(b.name) || a.line - b.line);
}

function collectWindowFields(params: {
  filePath: string;
  source: string;
  repoRoot: string;
}): WindowField[] {
  const sourceFile = createSourceFile(params.filePath, params.source);
  const fields: WindowField[] = [];

  const visit = (node: ts.Node): void => {
    if (ts.isInterfaceDeclaration(node) && node.name.text === 'Window') {
      for (const member of node.members) {
        if (!ts.isPropertySignature(member)) continue;
        const name = getPropertyNameKey(member.name);
        if (!name) continue;
        fields.push({
          name,
          typeText: member.type ? member.type.getText(sourceFile) : '<missing>',
          file: relative(params.repoRoot, params.filePath),
          line: getLine(sourceFile, member),
        });
      }
    }
    ts.forEachChild(node, visit);
  };

  visit(sourceFile);
  return fields.sort((a, b) => a.name.localeCompare(b.name) || a.line - b.line);
}

function makeNameMap<T extends { name: string }>(entries: readonly T[]): Map<string, T> {
  return new Map(entries.map((entry) => [entry.name, entry]));
}

function hasKnownDebtWindowTypeAllowlist(
  name: string,
  knownDebtByName: Map<string, KnownDebtAllowlistEntry>,
): boolean {
  return knownDebtByName.get(name)?.allowMissingWindowType === true;
}

function hasKnownDebtExposureAllowlist(
  name: string,
  knownDebtByName: Map<string, KnownDebtAllowlistEntry>,
): boolean {
  return knownDebtByName.get(name)?.allowMissingExposure === true;
}

export function findIpcBridgeExposureParityViolations(
  options: FindIpcBridgeExposureParityViolationsOptions = {},
): FindIpcBridgeExposureParityViolationsResult {
  const repoRoot = options.repoRoot ? resolve(options.repoRoot) : REPO_ROOT;
  const paths = resolvePaths(repoRoot, options.paths);
  const readFile = options.readFile ?? ((absolutePath: string) => readFileSync(absolutePath, 'utf8'));

  const legacyAliases = options.legacyAliases ?? LEGACY_ALIAS_EXCEPTIONS;
  const nonIpcBridgeExposures = options.nonIpcBridgeExposures ?? NON_IPC_BRIDGE_EXPOSURES;
  const connectorDomains = options.connectorDomains ?? RENDERER_FACING_CONNECTOR_DOMAINS;
  const knownDebtAllowlist = options.knownDebtAllowlist ?? KNOWN_DEBT_ALLOWLIST;
  const mainOnlyBridgeExports = options.mainOnlyBridgeExports ?? MAIN_ONLY_BRIDGE_EXPORTS;

  const bridgeExports = collectIpcBridgeExports({
    filePath: paths.ipcBridgeFile,
    source: readFile(paths.ipcBridgeFile),
  });
  const exposures = collectContextBridgeExposures({
    filePath: paths.preloadFile,
    source: readFile(paths.preloadFile),
    repoRoot,
  });
  const windowFields = collectWindowFields({
    filePath: paths.rendererEnvFile,
    source: readFile(paths.rendererEnvFile),
    repoRoot,
  });

  const exposuresByName = makeNameMap(exposures);
  const windowFieldsByName = makeNameMap(windowFields);
  const legacyAliasByName = makeNameMap(legacyAliases);
  const nonIpcBridgeExposureByName = makeNameMap(nonIpcBridgeExposures);
  const knownDebtByName = makeNameMap(knownDebtAllowlist);
  const connectorDomainByName = makeNameMap(connectorDomains);
  const mainOnlyBridgeExportByName = makeNameMap(mainOnlyBridgeExports);

  const exposedWithoutBridgeExport = exposures
    .filter((exposure) => !bridgeExports.has(exposure.name))
    .filter((exposure) => !legacyAliasByName.has(exposure.name))
    .filter((exposure) => !nonIpcBridgeExposureByName.has(exposure.name));

  const exposedWithoutWindowType = exposures
    .filter((exposure) => !windowFieldsByName.has(exposure.name))
    .filter((exposure) => legacyAliasByName.get(exposure.name)?.allowMissingWindowType !== true)
    .filter((exposure) => nonIpcBridgeExposureByName.get(exposure.name)?.allowMissingWindowType !== true)
    .filter((exposure) => !hasKnownDebtWindowTypeAllowlist(exposure.name, knownDebtByName))
    .sort((a, b) => a.name.localeCompare(b.name) || a.line - b.line);

  const legacyAliasTargetViolations: string[] = [];
  for (const alias of legacyAliases) {
    const exposure = exposuresByName.get(alias.name);
    if (!exposure) continue;

    if (exposure.valueExpression !== alias.target) {
      legacyAliasTargetViolations.push(
        `${alias.name} should expose ${alias.target}, but exposes ${exposure.valueExpression}`,
      );
    }
    if (!bridgeExports.has(alias.target)) {
      legacyAliasTargetViolations.push(
        `${alias.name} targets ${alias.target}, but ${alias.target} is not exported by src/preload/ipcBridge.ts`,
      );
    }
  }
  legacyAliasTargetViolations.sort();

  const connectorDomainValueBindingViolations = connectorDomains
    .map((domain) => {
      const exposure = exposuresByName.get(domain.name);
      if (!exposure || exposure.valueExpression === domain.name) return null;
      return `${domain.name} should expose ${domain.name}, but exposes ${exposure.valueExpression}`;
    })
    .filter((violation): violation is string => violation !== null)
    .sort();

  const connectorDomainsMissingExport = connectorDomains
    .filter((domain) => !bridgeExports.has(domain.name));

  const connectorDomainsMissingExposure = connectorDomains
    .filter((domain) => !exposuresByName.has(domain.name))
    .filter((domain) => !hasKnownDebtExposureAllowlist(domain.name, knownDebtByName));

  const connectorDomainsMissingWindowType = connectorDomains
    .filter((domain) => !windowFieldsByName.has(domain.name))
    .filter((domain) => !hasKnownDebtWindowTypeAllowlist(domain.name, knownDebtByName));

  const bridgeExportClassificationConflicts: string[] = [];
  const unclassifiedBridgeExports: string[] = [];
  for (const exportName of [...bridgeExports].filter((name) => name.endsWith('Api')).sort()) {
    const buckets = [
      connectorDomainByName.has(exportName) ? 'renderer-facing' : null,
      mainOnlyBridgeExportByName.has(exportName) ? 'main-only' : null,
      legacyAliasByName.has(exportName) ? 'legacy-alias' : null,
      knownDebtByName.has(exportName) ? 'known-debt' : null,
    ].filter((bucket): bucket is string => bucket !== null);

    if (buckets.length === 0) {
      unclassifiedBridgeExports.push(exportName);
    } else if (buckets.length > 1) {
      bridgeExportClassificationConflicts.push(`${exportName}: ${buckets.join(', ')}`);
    }
  }

  const mainOnlyBridgeExportsExposed = mainOnlyBridgeExports
    .filter((entry) => exposuresByName.has(entry.name))
    .map((entry) => `${entry.name}: ${entry.reason}`)
    .sort();

  const staleAllowlistEntries: StaleAllowlistEntry[] = [];
  for (const entry of knownDebtAllowlist) {
    if (entry.allowMissingExposure && exposuresByName.has(entry.name)) {
      staleAllowlistEntries.push({
        name: entry.name,
        allowlist: 'knownDebtMissingExposure',
        reason: entry.reason,
      });
    }
    if (entry.allowMissingWindowType && windowFieldsByName.has(entry.name)) {
      staleAllowlistEntries.push({
        name: entry.name,
        allowlist: 'knownDebtMissingWindowType',
        reason: entry.reason,
      });
    }
  }
  for (const alias of legacyAliases) {
    if (alias.allowMissingWindowType && windowFieldsByName.has(alias.name)) {
      staleAllowlistEntries.push({
        name: alias.name,
        allowlist: 'legacyAliasMissingWindowType',
        reason: alias.reason,
      });
    }
  }
  for (const exposureException of nonIpcBridgeExposures) {
    if (exposureException.allowMissingWindowType && windowFieldsByName.has(exposureException.name)) {
      staleAllowlistEntries.push({
        name: exposureException.name,
        allowlist: 'nonIpcBridgeMissingWindowType',
        reason: exposureException.reason,
      });
    }
  }
  staleAllowlistEntries.sort((a, b) => a.name.localeCompare(b.name) || a.allowlist.localeCompare(b.allowlist));

  const warnings: string[] = [];
  if (staleAllowlistEntries.length > 0) {
    warnings.push(
      `${staleAllowlistEntries.length} allowlist entry/entries are stale. Remove resolved debt from the allowlist.`,
    );
  }

  return {
    bridgeExports: [...bridgeExports].sort(),
    exposures,
    windowFields,
    exposedWithoutBridgeExport,
    exposedWithoutWindowType,
    legacyAliasTargetViolations,
    connectorDomainValueBindingViolations,
    connectorDomainsMissingExport,
    connectorDomainsMissingExposure,
    connectorDomainsMissingWindowType,
    bridgeExportClassificationConflicts,
    unclassifiedBridgeExports,
    mainOnlyBridgeExportsExposed,
    staleAllowlistEntries,
    warnings,
  };
}

function formatExposure(exposure: Exposure): string {
  return `${exposure.file}:${exposure.line} ${exposure.name} -> ${exposure.valueExpression}`;
}

export function main(): void {
  const result = findIpcBridgeExposureParityViolations();

  for (const warning of result.warnings) {
    process.stderr.write(`[ipc-bridge-exposure-parity] warning: ${warning}\n`);
  }

  if (result.staleAllowlistEntries.length > 0) {
    process.stderr.write(
      `[ipc-bridge-exposure-parity] warning: ${result.staleAllowlistEntries.length} stale allowlist entry/entries:\n`,
    );
    for (const entry of result.staleAllowlistEntries) {
      process.stderr.write(`  - ${entry.name} (in ${entry.allowlist} allowlist): ${entry.reason}\n`);
    }
  }

  const errors: string[] = [];

  if (result.exposedWithoutBridgeExport.length > 0) {
    errors.push(
      `${result.exposedWithoutBridgeExport.length} preload exposure(s) without an ipcBridge export or documented exception:`,
    );
    for (const exposure of result.exposedWithoutBridgeExport) {
      errors.push(`  - ${formatExposure(exposure)}`);
    }
  }

  if (result.exposedWithoutWindowType.length > 0) {
    errors.push(
      `${result.exposedWithoutWindowType.length} preload exposure(s) without a Window ambient type or documented exception:`,
    );
    for (const exposure of result.exposedWithoutWindowType) {
      errors.push(`  - ${formatExposure(exposure)}`);
    }
  }

  if (result.legacyAliasTargetViolations.length > 0) {
    errors.push(`${result.legacyAliasTargetViolations.length} legacy alias target violation(s):`);
    for (const violation of result.legacyAliasTargetViolations) {
      errors.push(`  - ${violation}`);
    }
  }

  if (result.connectorDomainValueBindingViolations.length > 0) {
    errors.push(
      `${result.connectorDomainValueBindingViolations.length} renderer-facing bridge exposure value-binding violation(s):`,
    );
    for (const violation of result.connectorDomainValueBindingViolations) {
      errors.push(`  - ${violation}`);
    }
  }

  if (result.connectorDomainsMissingExport.length > 0) {
    errors.push(
      `${result.connectorDomainsMissingExport.length} renderer-facing bridge domain(s) without ipcBridge export:`,
    );
    for (const domain of result.connectorDomainsMissingExport) {
      errors.push(`  - ${domain.name}: ${domain.reason}`);
    }
  }

  if (result.connectorDomainsMissingExposure.length > 0) {
    errors.push(
      `${result.connectorDomainsMissingExposure.length} renderer-facing bridge domain(s) without preload exposure:`,
    );
    for (const domain of result.connectorDomainsMissingExposure) {
      errors.push(`  - ${domain.name}: ${domain.reason}`);
    }
  }

  if (result.connectorDomainsMissingWindowType.length > 0) {
    errors.push(
      `${result.connectorDomainsMissingWindowType.length} renderer-facing bridge domain(s) without Window ambient type:`,
    );
    for (const domain of result.connectorDomainsMissingWindowType) {
      errors.push(`  - ${domain.name}: ${domain.reason}`);
    }
  }

  if (result.bridgeExportClassificationConflicts.length > 0) {
    errors.push(
      `${result.bridgeExportClassificationConflicts.length} ipcBridge *Api export classification conflict(s):`,
    );
    for (const conflict of result.bridgeExportClassificationConflicts) {
      errors.push(`  - ${conflict}`);
    }
  }

  if (result.unclassifiedBridgeExports.length > 0) {
    errors.push(
      `${result.unclassifiedBridgeExports.length} unclassified ipcBridge *Api export(s) - classify as renderer-facing, main-only, legacy alias, or known-debt:`,
    );
    for (const exportName of result.unclassifiedBridgeExports) {
      errors.push(`  - ${exportName}`);
    }
  }

  if (result.mainOnlyBridgeExportsExposed.length > 0) {
    errors.push(`${result.mainOnlyBridgeExportsExposed.length} main-only ipcBridge *Api export(s) exposed to renderer:`);
    for (const violation of result.mainOnlyBridgeExportsExposed) {
      errors.push(`  - ${violation}`);
    }
  }

  if (errors.length > 0) {
    process.stderr.write('IPC bridge exposure parity check failed.\n');
    for (const line of errors) {
      process.stderr.write(`${line}\n`);
    }
    process.exit(1);
  }

  process.stdout.write(
    `IPC bridge exposure parity check passed (${result.bridgeExports.length} ipcBridge export${result.bridgeExports.length === 1 ? '' : 's'}, ${result.exposures.length} preload exposure${result.exposures.length === 1 ? '' : 's'}, ${result.windowFields.length} Window field${result.windowFields.length === 1 ? '' : 's'}, ${RENDERER_FACING_CONNECTOR_DOMAINS.length} required renderer-facing bridge domain${RENDERER_FACING_CONNECTOR_DOMAINS.length === 1 ? '' : 's'} scanned).\n`,
  );
  process.exit(0);
}

const invokedAsScript = (() => {
  if (!process.argv[1]) return false;
  try {
    return resolve(process.argv[1]) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
})();

if (invokedAsScript) {
  main();
}
