#!/usr/bin/env npx tsx
/**
 * IPC Bridge Generator
 *
 * Reads the IPC contract definitions and generates:
 * 1. src/preload/generated/ipcBridge.ts - Typed preload bridge (all domains)
 *
 * Usage:
 *   npx tsx scripts/generate-ipc-bridge.ts
 *   npm run generate:ipc
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const GENERATED_DIR = path.join(ROOT, 'src/preload/generated');
const BRIDGE_FILE = path.join(GENERATED_DIR, 'ipcBridge.ts');

type DomainChannels = Record<string, ChannelDef>;

interface ChannelDef {
  type?: 'invoke' | 'sync';
  channel: string;
  description?: string;
  request: unknown;
  response: unknown;
}

/**
 * Load the TypeScript contract module via tsx
 */
export async function loadContract(): Promise<{ ipcContract: Record<string, DomainChannels> }> {
  const contractPath = path.join(ROOT, 'src/shared/ipc/contracts.ts');
  const module = await import(contractPath);
  return module as { ipcContract: Record<string, DomainChannels> };
}

/**
 * Generate TypeScript code for the preload bridge
 */
export function generateBridgeCode(domainEntries: [string, DomainChannels][]): string {
  const domainSections = domainEntries.map(([domain, channels]) => generateDomainSection(domain, channels));
  const legacyBlock = generateLegacyBlock();

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Generated by: scripts/generate-ipc-bridge.ts
 * Source: src/shared/ipc/contracts.ts
 *
 * Regenerate with: npm run generate:ipc
 */

import { ipcRenderer } from 'electron';
import type { IpcRequestOf, IpcResponseOf } from '@shared/ipc/contracts';

${domainSections.map((section) => section.code).join('\n\n')}

// =============================================================================
// Legacy Compatibility Layer
// =============================================================================

/**
 * Legacy flat API surface for backward compatibility.
 * New code should use domain-specific APIs (workspaceApi, settingsApi, etc.).
 *
 * @deprecated Use domain-specific APIs instead
 */
export const legacyApiMethods = {
${legacyBlock}
};

export type LegacyApiMethods = typeof legacyApiMethods;
`;
}

function generateDomainSection(domain: string, channels: DomainChannels): { code: string } {
  const apiName = `${domain}Api`;
  const typeName = `${capitalize(domain)}Api`;
  const meta = DOMAIN_DESCRIPTIONS[domain] ?? defaultDomainMeta(domain);

  const methodStrings = Object.values(channels).map((def) => {
    const methodName = channelToMethodName(def.channel);
    const isSync = def.type === 'sync';

    if (isVoidSchema(def.request)) {
      if (isSync) {
        return `  ${methodName}: () =>\n    ipcRenderer.sendSync('${def.channel}') as IpcResponseOf<'${def.channel}'>,
`;
      }
      return `  ${methodName}: () =>\n    ipcRenderer.invoke('${def.channel}') as Promise<IpcResponseOf<'${def.channel}'>>,
`;
    }

    const optional = isOptionalSchema(def.request);
    const param = optional ? `request?: IpcRequestOf<'${def.channel}'>` : `request: IpcRequestOf<'${def.channel}'>`;

    if (isSync) {
      return `  ${methodName}: (${param}) =>\n    ipcRenderer.sendSync('${def.channel}', request) as IpcResponseOf<'${def.channel}'>,
`;
    }
    return `  ${methodName}: (${param}) =>\n    ipcRenderer.invoke('${def.channel}', request) as Promise<IpcResponseOf<'${def.channel}'>>,
`;
  });

  return {
    code: `// =============================================================================\n// ${meta.title}\n// =============================================================================\n\n/**\n * ${meta.description}\n * Handler: ${meta.handler}\n */\nexport const ${apiName} = {\n${methodStrings.join('\n')}\n};\n\nexport type ${typeName} = typeof ${apiName};`,
  };
}

function generateLegacyBlock(): string {
  return LEGACY_METHOD_MAPPINGS.map(({ comment, entries }) => {
    const lines = entries.map(({ legacyName, target }) => `  ${legacyName}: ${target},`);
    return comment ? `  // ${comment}\n${lines.join('\n')}` : lines.join('\n');
  }).join('\n\n');
}

function channelToMethodName(channel: string): string {
  const withoutPrefix = channel.replace(/^[^:]+:/, '');
  return withoutPrefix.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

function isVoidSchema(schema: unknown): boolean {
  if (!schema || typeof schema !== 'object') return true;
  const def = (schema as { _def?: { typeName?: string } })._def;
  if (!def) return true;
  return def.typeName === 'ZodVoid' || def.typeName === 'ZodUndefined';
}

function isOptionalSchema(schema: unknown): boolean {
  if (!schema || typeof schema !== 'object') return false;
  const def = (schema as { _def?: { typeName?: string } })._def;
  if (!def) return false;
  return def.typeName === 'ZodOptional';
}

function capitalize(value: string): string {
  if (!value) return value;
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function defaultDomainMeta(domain: string) {
  return {
    title: `${capitalize(domain)} API`,
    description: 'Domain API',
    handler: `src/main/ipc/${domain}Handlers.ts`,
  };
}

const DOMAIN_DESCRIPTIONS: Record<string, { title: string; description: string; handler: string }> = {
  library: {
    title: 'Library API',
    description: 'Library file operations API',
    handler: 'src/main/ipc/libraryHandlers.ts',
  },
  settings: {
    title: 'Settings API',
    description: 'Application settings API',
    handler: 'src/main/ipc/settingsHandlers.ts',
  },
  app: {
    title: 'App API',
    description: 'Shell and URL operations API',
    handler: 'src/main/ipc/appHandlers.ts',
  },
  export: {
    title: 'Export API',
    description: 'PDF and file export API',
    handler: 'src/main/ipc/exportHandlers.ts',
  },
  voice: {
    title: 'Voice API',
    description: 'Voice transcription and TTS API',
    handler: 'src/main/ipc/voiceHandlers.ts',
  },
  agent: {
    title: 'Agent API',
    description: 'Agent turn execution API',
    handler: 'src/main/ipc/agentHandlers.ts',
  },
  permissions: {
    title: 'Permissions API',
    description: 'OS permission checks API',
    handler: 'src/main/ipc/permissionsHandlers.ts',
  },
  sessions: {
    title: 'Sessions API',
    description: 'Agent session persistence API',
    handler: 'src/main/ipc/sessionsHandlers.ts',
  },
  tasks: {
    title: 'Tasks API',
    description: 'Task queue management API',
    handler: 'src/main/ipc/tasksHandlers.ts',
  },
  automations: {
    title: 'Automations API',
    description: 'Scheduled automation workflows API',
    handler: 'src/main/ipc/automationsHandlers.ts',
  },
  demo: {
    title: 'Demo API',
    description: 'Demo mode management API',
    handler: 'src/main/ipc/demoHandlers.ts',
  },
  dashboard: {
    title: 'Dashboard API',
    description: 'Contextual suggestions API',
    handler: 'src/main/ipc/dashboardHandlers.ts',
  },
  misc: {
    title: 'Misc API',
    description: 'Miscellaneous operations API (analytics, Sentry, conversation, etc.)',
    handler: 'src/main/ipc/miscHandlers.ts',
  },
  cloud: {
    title: 'Cloud API',
    description: 'Cloud Sprite provisioning, management, and migration API',
    handler: 'src/main/ipc/cloudHandlers.ts',
  },
  skillHistory: {
    title: 'Skill history API',
    description: 'Shared skill collaboration snapshot list, load, restore, fork',
    handler: 'src/main/ipc/libraryHandlers.ts',
  },
};

const LEGACY_METHOD_MAPPINGS: Array<{ comment?: string; entries: { legacyName: string; target: string }[] }> = [
  {
    comment: 'Library methods (legacy names)',
    entries: [
      { legacyName: 'listWorkspaceFiles', target: 'libraryApi.listFiles' },
      { legacyName: 'readWorkspaceFile', target: 'libraryApi.readFile' },
      { legacyName: 'readFileAsBase64', target: 'libraryApi.readFileBase64' },
      { legacyName: 'writeWorkspaceFile', target: 'libraryApi.writeFile' },
      { legacyName: 'createWorkspaceFile', target: 'libraryApi.createFile' },
      { legacyName: 'createWorkspaceFolder', target: 'libraryApi.createFolder' },
      { legacyName: 'renameWorkspaceItem', target: 'libraryApi.renameItem' },
      { legacyName: 'moveWorkspaceItem', target: 'libraryApi.moveItem' },
      { legacyName: 'deleteWorkspaceItem', target: 'libraryApi.deleteItem' },
    ],
  },
  {
    comment: 'Settings methods (legacy names)',
    entries: [
      { legacyName: 'getSettings', target: 'settingsApi.get' },
      { legacyName: 'updateSettings', target: 'settingsApi.update' },
      { legacyName: 'getDefaultWorkspacePath', target: 'settingsApi.getDefaultWorkspace' },
      { legacyName: 'chooseDirectory', target: 'settingsApi.chooseDirectory' },
      { legacyName: 'chooseFile', target: 'settingsApi.chooseFile' },
      { legacyName: 'chooseExecutable', target: 'settingsApi.chooseExecutable' },
      { legacyName: 'getMcpSummary', target: 'settingsApi.mcpSummary' },
      { legacyName: 'ensureManagedMcpConfig', target: 'settingsApi.mcpEnsureManaged' },
      { legacyName: 'getMcpServerDetails', target: 'settingsApi.mcpGetServer' },
      { legacyName: 'addRebelInboxServer', target: 'settingsApi.mcpAddRebelServer' },
      { legacyName: 'addRebelTaskQueueServer', target: 'settingsApi.mcpAddRebelServer' },
      { legacyName: 'upsertMcpServer', target: 'settingsApi.mcpUpsertServer' },
      { legacyName: 'removeMcpServer', target: 'settingsApi.mcpRemoveServer' },
      { legacyName: 'patchMcpRouterPath', target: 'settingsApi.mcpRouterPath' },
    ],
  },
  {
    comment: 'App methods',
    entries: [
      { legacyName: 'openPath', target: 'appApi.openPath' },
      { legacyName: 'openUrl', target: 'appApi.openUrl' },
      { legacyName: 'revealPath', target: 'appApi.revealPath' },
    ],
  },
  {
    comment: 'Export methods',
    entries: [
      { legacyName: 'exportToPdf', target: 'exportApi.toPdf' },
      { legacyName: 'saveFile', target: 'exportApi.saveFile' },
    ],
  },
  {
    comment: 'Voice methods',
    entries: [
      { legacyName: 'transcribeAudio', target: 'voiceApi.transcribe' },
      { legacyName: 'textToSpeech', target: 'voiceApi.textToSpeech' },
    ],
  },
  {
    comment: 'Agent methods',
    entries: [
      { legacyName: 'startAgentTurn', target: 'agentApi.turn' },
      { legacyName: 'stopTurn', target: 'agentApi.stopTurn' },
    ],
  },
  {
    comment: 'Permissions methods',
    entries: [
      { legacyName: 'getMicrophonePermissionStatus', target: 'permissionsApi.getMicrophoneStatus' },
      { legacyName: 'requestMicrophonePermission', target: 'permissionsApi.requestMicrophone' },
      { legacyName: 'checkFileAccess', target: 'permissionsApi.checkFileAccess' },
      { legacyName: 'openSystemPreferences', target: 'permissionsApi.openSystemPreferences' },
    ],
  },
  {
    comment: 'Sessions methods',
    entries: [
      { legacyName: 'loadAgentSessions', target: 'sessionsApi.load' },
      { legacyName: 'saveAgentSessions', target: 'sessionsApi.save' },
    ],
  },
  {
    comment: 'Inbox methods',
    entries: [
      { legacyName: 'loadInbox', target: 'inboxApi.load' },
      { legacyName: 'deleteInboxItem', target: 'inboxApi.delete' },
      { legacyName: 'recordInboxExecution', target: 'inboxApi.recordExecution' },
      // Legacy aliases
      { legacyName: 'loadTaskQueue', target: 'inboxApi.load' },
      { legacyName: 'deleteTask', target: 'inboxApi.delete' },
      { legacyName: 'recordTaskExecution', target: 'inboxApi.recordExecution' },
    ],
  },
  {
    comment: 'Automations methods',
    entries: [
      { legacyName: 'loadAutomations', target: 'automationsApi.state' },
      { legacyName: 'upsertAutomation', target: 'automationsApi.upsert' },
      { legacyName: 'deleteAutomation', target: 'automationsApi.delete' },
      { legacyName: 'runAutomationNow', target: 'automationsApi.runNow' },
      { legacyName: 'setAutomationHistoryVisibility', target: 'automationsApi.setHistoryVisibility' },
    ],
  },
  {
    comment: 'Demo methods',
    entries: [
      { legacyName: 'enterDemoMode', target: 'demoApi.enter' },
      { legacyName: 'exitDemoMode', target: 'demoApi.exit' },
      { legacyName: 'getDemoModeStatus', target: 'demoApi.status' },
    ],
  },
  {
    comment: 'Dashboard methods',
    entries: [
      { legacyName: 'prefetchAttentionSuggestions', target: 'dashboardApi.prefetchAttentionSuggestions' },
      { legacyName: 'getAttentionSuggestions', target: 'dashboardApi.getAttentionSuggestions' },
    ],
  },
  {
    comment: 'Misc methods',
    entries: [
      { legacyName: 'getAnalyticsStatus', target: 'miscApi.status' },
      { legacyName: 'generateConversationTitle', target: 'miscApi.generateTitle' },
      { legacyName: 'setUserEmail', target: 'miscApi.setEmail' },
      { legacyName: 'captureException', target: 'miscApi.captureException' },
      { legacyName: 'captureMessage', target: 'miscApi.captureMessage' },
    ],
  },
];

async function main() {
  console.log('🔧 IPC Bridge Generator');
  console.log('========================\n');

  console.log('📖 Loading IPC contract...');
  const contract = await loadContract();
  const domainEntries = Object.entries(contract.ipcContract);

  for (const [domain, channels] of domainEntries) {
    console.log(`   Found ${Object.keys(channels).length} ${domain} channels`);
  }
  const totalChannels = domainEntries.reduce((sum, [, channels]) => sum + Object.keys(channels).length, 0);
  console.log(`   Total: ${totalChannels} channels\n`);

  console.log('⚙️  Generating preload bridge...');
  const bridgeCode = generateBridgeCode(domainEntries);

  await fs.mkdir(GENERATED_DIR, { recursive: true });

  await fs.writeFile(BRIDGE_FILE, bridgeCode, 'utf8');
  console.log(`   ✅ Written: ${path.relative(ROOT, BRIDGE_FILE)}`);

  console.log('\n✨ Done!\n');
}

// Guard: only run main() when this script is executed directly, not when imported
// by other scripts (e.g. validate-ipc.ts imports generateBridgeCode).
const isDirectRun = process.argv[1] &&
  fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isDirectRun) {
  main().catch((error) => {
    console.error('❌ Generator failed:', error);
    process.exit(1);
  });
}


