#!/usr/bin/env npx tsx
/**
 * Generate src/core/services/superMcpVersion.generated.ts from
 * super-mcp/package.json.
 *
 * Run modes:
 *   tsx scripts/generate-super-mcp-version.ts          # write or update
 *   tsx scripts/generate-super-mcp-version.ts --check  # CI: fail if stale
 *
 * Wired into validate:fast as `validate:super-mcp-version-codegen`.
 *
 * @see docs/plans/260607_supermcp-release-automation/PLAN.md (Stage 1)
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SUPER_MCP_PACKAGE_PATH = path.join(REPO_ROOT, 'super-mcp/package.json');
const GENERATED_PATH = path.join(REPO_ROOT, 'src/core/services/superMcpVersion.generated.ts');
const EXPECTED_PACKAGE_NAME = 'super-mcp-router';

interface GenerateOptions {
  readonly checkOnly: boolean;
}

interface SuperMcpPackageJson {
  readonly name: string;
  readonly version: string;
}

function parseArgs(argv: readonly string[]): GenerateOptions {
  return { checkOnly: argv.includes('--check') };
}

function readSuperMcpPackageJson(): SuperMcpPackageJson {
  const parsed = JSON.parse(fs.readFileSync(SUPER_MCP_PACKAGE_PATH, 'utf8')) as {
    readonly name?: unknown;
    readonly version?: unknown;
  };
  if (parsed.name !== EXPECTED_PACKAGE_NAME) {
    throw new Error(
      `Expected ${path.relative(REPO_ROOT, SUPER_MCP_PACKAGE_PATH)} name to be ` +
        `${JSON.stringify(EXPECTED_PACKAGE_NAME)}, got ${JSON.stringify(parsed.name)}.`,
    );
  }
  if (typeof parsed.version !== 'string' || parsed.version.trim().length === 0) {
    throw new Error(
      `Expected ${path.relative(REPO_ROOT, SUPER_MCP_PACKAGE_PATH)} version to be a non-empty string.`,
    );
  }
  return {
    name: parsed.name,
    version: parsed.version,
  };
}

function renderGeneratedFile(version: string): string {
  const lines: string[] = [
    '/**',
    ' * AUTO-GENERATED — Stage 1 (super-mcp version single source of truth).',
    ' *',
    ' * Source: super-mcp/package.json (`version`, with `name` asserted as `super-mcp-router`).',
    ' * Generator: scripts/generate-super-mcp-version.ts',
    ' *',
    ' * Updating super-mcp: bump super-mcp/package.json and rerun',
    ' * `npm run generate:super-mcp-version` (or let validate:fast catch the drift).',
    ' * DO NOT edit this file directly — your edits will be overwritten.',
    ' */',
    '',
    `export const GENERATED_SUPER_MCP_ROUTER_VERSION = ${JSON.stringify(version)} as const;`,
    '',
  ];
  return lines.join('\n');
}

function main(): number {
  const options = parseArgs(process.argv.slice(2));
  const packageJson = readSuperMcpPackageJson();
  const nextContent = renderGeneratedFile(packageJson.version);

  if (options.checkOnly) {
    let existing = '';
    try {
      existing = fs.readFileSync(GENERATED_PATH, 'utf8');
    } catch {
      process.stderr.write(
        `[generate-super-mcp-version] FAIL: generated file missing at ${path.relative(REPO_ROOT, GENERATED_PATH)}\n`,
      );
      return 1;
    }
    if (existing !== nextContent) {
      process.stderr.write(
        '[generate-super-mcp-version] FAIL: generated file is stale. ' +
          'Run `npm run generate:super-mcp-version` to refresh.\n',
      );
      return 1;
    }
    process.stdout.write(
      `[generate-super-mcp-version] OK: super-mcp-router@${packageJson.version} in sync.\n`,
    );
    return 0;
  }

  fs.writeFileSync(GENERATED_PATH, nextContent, 'utf8');
  process.stdout.write(
    `[generate-super-mcp-version] wrote super-mcp-router@${packageJson.version} to ` +
      `${path.relative(REPO_ROOT, GENERATED_PATH)}\n`,
  );
  return 0;
}

try {
  process.exit(main());
} catch (err) {
  process.stderr.write(
    `[generate-super-mcp-version] ERROR: ${err instanceof Error ? err.message : String(err)}\n`,
  );
  process.exit(1);
}
