/**
 * Type-safe mapping from a connector name (the user-supplied argument to
 * `npm run mcp:release <name>`) to:
 *
 *  - the npm package name on the registry,
 *  - the catalog ID(s) that pin the version.
 *
 * One source of truth: extending support for a new connector requires
 * appending a typed entry here. The release script consumes this table at
 * Stages 0 and 6.
 *
 * Note (2026-05-26): the Microsoft 5 previously carried a
 * `microsoftPrimaryConst` field for atomic update of
 * `MICROSOFT_REBEL_OSS_DEFS.packageSpec` alongside the catalog. As of v2 of
 * the release plan, MICROSOFT_REBEL_OSS_DEFS no longer carries `packageSpec`
 * — the catalog is the sole source of truth for OSS pins, with structured
 * errors on miss. The atomic-update branch in Stage 6 was removed.
 *
 * See docs/plans/260525_oss_release_automation.md (v2) for context.
 */

export interface ConnectorReleaseMapping {
  /**
   * The connector name passed on the CLI: `npm run mcp:release <name>`.
   * Must match the directory name under `mcp-servers/connectors/<name>/`.
   */
  readonly name: string;

  /**
   * The full npm package name (without version) as published on the
   * registry, e.g. `@mindstone/mcp-server-slack`.
   */
  readonly npmPackage: string;

  /**
   * The catalog IDs (from resources/connector-catalog.json) whose
   * `mcpConfig.args[1]` should be updated when this connector is released.
   * Most connectors map 1:1, but some legacy entries map to multiple IDs.
   */
  readonly catalogIds: readonly string[];

  /**
   * If true, this connector has not yet been published to npm.
   * The release script's first-publish path skips the version-already-
   * published check and bootstraps the catalog entry against 0.0.1.
   */
  readonly firstPublish?: boolean;
}

const SLACK: ConnectorReleaseMapping = {
  name: 'slack',
  npmPackage: '@mindstone/mcp-server-slack',
  catalogIds: ['bundled-slack'],
};

const HUBSPOT: ConnectorReleaseMapping = {
  name: 'hubspot',
  npmPackage: '@mindstone/mcp-server-hubspot',
  catalogIds: ['bundled-hubspot'],
};

const GOOGLE_WORKSPACE: ConnectorReleaseMapping = {
  name: 'google-workspace',
  npmPackage: '@mindstone/mcp-server-google-workspace',
  catalogIds: ['bundled-google'],
};

const VANTA: ConnectorReleaseMapping = {
  name: 'vanta',
  npmPackage: '@mindstone/mcp-server-vanta',
  catalogIds: ['bundled-vanta'],
};

const OPENAI_IMAGE: ConnectorReleaseMapping = {
  name: 'openai-image',
  npmPackage: '@mindstone/mcp-server-openai-image',
  catalogIds: ['openai-image-generation'],
};

const REPLIT_SSH: ConnectorReleaseMapping = {
  name: 'replit-ssh',
  npmPackage: '@mindstone/mcp-server-replit-ssh',
  catalogIds: ['bundled-replit-ssh'],
};

// Microsoft 5 — uniform catalog-only treatment as of v2 of the release plan.
// MICROSOFT_REBEL_OSS_DEFS in src/main/services/bundledMcpManager.ts no longer
// carries packageSpec; reading the catalog is the only path, with structured
// errors on miss.
const MICROSOFT_MAIL: ConnectorReleaseMapping = {
  name: 'microsoft-mail',
  npmPackage: '@mindstone/mcp-server-microsoft-mail',
  catalogIds: ['bundled-microsoft-mail'],
};

const MICROSOFT_CALENDAR: ConnectorReleaseMapping = {
  name: 'microsoft-calendar',
  npmPackage: '@mindstone/mcp-server-microsoft-calendar',
  catalogIds: ['bundled-microsoft-calendar'],
};

const MICROSOFT_FILES: ConnectorReleaseMapping = {
  name: 'microsoft-files',
  npmPackage: '@mindstone/mcp-server-microsoft-files',
  catalogIds: ['bundled-microsoft-files'],
};

const MICROSOFT_TEAMS: ConnectorReleaseMapping = {
  name: 'microsoft-teams',
  npmPackage: '@mindstone/mcp-server-microsoft-teams',
  catalogIds: ['bundled-microsoft-teams'],
};

const MICROSOFT_SHAREPOINT: ConnectorReleaseMapping = {
  name: 'microsoft-sharepoint',
  npmPackage: '@mindstone/mcp-server-microsoft-sharepoint',
  catalogIds: ['bundled-microsoft-sharepoint'],
};

const RETELL_AI: ConnectorReleaseMapping = {
  name: 'retell-ai',
  npmPackage: '@mindstone/mcp-server-retell-ai',
  catalogIds: ['bundled-retell-ai'],
};

// --- Backfill (2026-06-11, Stage 4 of docs/plans/260611_mcp-landing-process/PLAN.md) ---
// The catalog pinned 35 distinct @mindstone/mcp-server-* packages but only 12
// were mapped here, leaving most connectors unreleasable via `mcp:release`.
// Entries below were generated by scanning resources/connector-catalog.json
// `mcpConfig.args` pins, grouping catalog IDs by package, and verifying each
// `name` against an existing `mcp-servers/connectors/<name>/` directory.
// scripts/check-release-mapping-completeness.ts (validate:fast) now keeps this
// table complete.

const APPLE_SHORTCUTS: ConnectorReleaseMapping = {
  name: 'apple-shortcuts',
  npmPackage: '@mindstone/mcp-server-apple-shortcuts',
  catalogIds: ['bundled-apple-shortcuts'],
};

const BROWSER_AUTOMATION: ConnectorReleaseMapping = {
  name: 'browser-automation',
  npmPackage: '@mindstone/mcp-server-browser-automation',
  catalogIds: ['bundled-browser-automation'],
};

// Internal release-pipeline test connector — not for use. It deliberately has
// no catalog entry (zero user surface); releases exercise the pipeline only.
const CANARY: ConnectorReleaseMapping = {
  name: 'canary',
  npmPackage: '@mindstone/mcp-server-canary',
  catalogIds: [],
};

const ELEVENLABS: ConnectorReleaseMapping = {
  name: 'elevenlabs',
  npmPackage: '@mindstone/mcp-server-elevenlabs',
  catalogIds: ['bundled-elevenlabs'],
};

// One package backs three catalog entries (iCloud / Yahoo / custom IMAP) —
// a release must bump all three pins atomically.
const EMAIL_IMAP: ConnectorReleaseMapping = {
  name: 'email-imap',
  npmPackage: '@mindstone/mcp-server-email-imap',
  catalogIds: ['bundled-icloud-mail', 'bundled-yahoo-mail', 'bundled-custom-email'],
};

const FATHOM: ConnectorReleaseMapping = {
  name: 'fathom',
  npmPackage: '@mindstone/mcp-server-fathom',
  catalogIds: ['bundled-fathom'],
};

const FRESHDESK: ConnectorReleaseMapping = {
  name: 'freshdesk',
  npmPackage: '@mindstone/mcp-server-freshdesk',
  catalogIds: ['bundled-freshdesk'],
};

const GAMMA: ConnectorReleaseMapping = {
  name: 'gamma',
  npmPackage: '@mindstone/mcp-server-gamma',
  catalogIds: ['bundled-gamma'],
};

const GOOGLE_ANALYTICS: ConnectorReleaseMapping = {
  name: 'google-analytics',
  npmPackage: '@mindstone/mcp-server-google-analytics',
  catalogIds: ['bundled-google-analytics'],
};

const HUMAANS: ConnectorReleaseMapping = {
  name: 'humaans',
  npmPackage: '@mindstone/mcp-server-humaans',
  catalogIds: ['bundled-humaans'],
};

const KLING: ConnectorReleaseMapping = {
  name: 'kling',
  npmPackage: '@mindstone/mcp-server-kling',
  catalogIds: ['bundled-kling'],
};

const MIXMAX: ConnectorReleaseMapping = {
  name: 'mixmax',
  npmPackage: '@mindstone/mcp-server-mixmax',
  catalogIds: ['bundled-mixmax'],
};

const NANO_BANANA: ConnectorReleaseMapping = {
  name: 'nano-banana',
  npmPackage: '@mindstone/mcp-server-nano-banana',
  catalogIds: ['bundled-nano-banana'],
};

const NAPKIN: ConnectorReleaseMapping = {
  name: 'napkin',
  npmPackage: '@mindstone/mcp-server-napkin',
  catalogIds: ['bundled-napkin'],
};

// NOTE: the office pin is ALSO mirrored by the canonical constant in
// src/shared/sidecar/officePackage.ts — an office release must bump
// OFFICE_MCP_PACKAGE_VERSION too, or scripts/check-office-package-version.ts
// (validate:fast) fails on the drift.
const OFFICE: ConnectorReleaseMapping = {
  name: 'office',
  npmPackage: '@mindstone/mcp-server-office',
  catalogIds: ['bundled-office'],
};

const OPUS_VIDEO_CLIP: ConnectorReleaseMapping = {
  name: 'opus-video-clip',
  npmPackage: '@mindstone/mcp-server-opus-video-clip',
  catalogIds: ['bundled-opus-video-clip'],
};

const PANDADOC: ConnectorReleaseMapping = {
  name: 'pandadoc',
  npmPackage: '@mindstone/mcp-server-pandadoc',
  catalogIds: ['bundled-pandadoc'],
};

const QUICKBOOKS: ConnectorReleaseMapping = {
  name: 'quickbooks',
  npmPackage: '@mindstone/mcp-server-quickbooks',
  catalogIds: ['bundled-quickbooks'],
};

const RUNWAY: ConnectorReleaseMapping = {
  name: 'runway',
  npmPackage: '@mindstone/mcp-server-runway',
  catalogIds: ['bundled-runway'],
};

const SALESFORCE: ConnectorReleaseMapping = {
  name: 'salesforce',
  npmPackage: '@mindstone/mcp-server-salesforce',
  catalogIds: ['bundled-salesforce'],
};

const SERVICENOW: ConnectorReleaseMapping = {
  name: 'servicenow',
  npmPackage: '@mindstone/mcp-server-servicenow',
  catalogIds: ['bundled-servicenow'],
};

const TALENTLMS: ConnectorReleaseMapping = {
  name: 'talentlms',
  npmPackage: '@mindstone/mcp-server-talentlms',
  catalogIds: ['bundled-talentlms'],
};

const WORKDAY: ConnectorReleaseMapping = {
  name: 'workday',
  npmPackage: '@mindstone/mcp-server-workday',
  catalogIds: ['bundled-workday'],
};

/**
 * Catalog-pinned packages deliberately NOT releasable via `mcp:release`.
 * Each exclusion must carry a documented reason; the completeness check
 * (scripts/check-release-mapping-completeness.ts) accepts a catalog pin only
 * if it resolves to a mapping entry above or an exclusion here.
 */
export interface ExcludedReleasePackage {
  /** Full npm package name (without version), e.g. `@mindstone/mcp-server-xero`. */
  readonly npmPackage: string;
  /** Why this package is excluded from the release mapping. */
  readonly reason: string;
}

export const EXCLUDED_PACKAGES: readonly ExcludedReleasePackage[] = [
  {
    npmPackage: '@mindstone/mcp-server-xero',
    reason:
      'release ownership undecided (community-provider entry) — decide before any xero release; ' +
      'see docs/plans/260611_mcp-landing-process/PLAN.md Stage 4',
  },
];

/**
 * Single source of truth — append-only as new OSS connectors land.
 */
export const CONNECTOR_RELEASE_MAPPINGS = {
  slack: SLACK,
  hubspot: HUBSPOT,
  'google-workspace': GOOGLE_WORKSPACE,
  vanta: VANTA,
  'openai-image': OPENAI_IMAGE,
  'replit-ssh': REPLIT_SSH,
  'microsoft-mail': MICROSOFT_MAIL,
  'microsoft-calendar': MICROSOFT_CALENDAR,
  'microsoft-files': MICROSOFT_FILES,
  'microsoft-teams': MICROSOFT_TEAMS,
  'microsoft-sharepoint': MICROSOFT_SHAREPOINT,
  'retell-ai': RETELL_AI,
  // Backfill 2026-06-11 (Stage 4) — see section comment above.
  'apple-shortcuts': APPLE_SHORTCUTS,
  'browser-automation': BROWSER_AUTOMATION,
  canary: CANARY,
  elevenlabs: ELEVENLABS,
  'email-imap': EMAIL_IMAP,
  fathom: FATHOM,
  freshdesk: FRESHDESK,
  gamma: GAMMA,
  'google-analytics': GOOGLE_ANALYTICS,
  humaans: HUMAANS,
  kling: KLING,
  mixmax: MIXMAX,
  'nano-banana': NANO_BANANA,
  napkin: NAPKIN,
  office: OFFICE,
  'opus-video-clip': OPUS_VIDEO_CLIP,
  pandadoc: PANDADOC,
  quickbooks: QUICKBOOKS,
  runway: RUNWAY,
  salesforce: SALESFORCE,
  servicenow: SERVICENOW,
  talentlms: TALENTLMS,
  workday: WORKDAY,
} as const satisfies Record<string, ConnectorReleaseMapping>;

export type ConnectorReleaseName = keyof typeof CONNECTOR_RELEASE_MAPPINGS;

export function getMapping(name: string): ConnectorReleaseMapping {
  const mapping = (CONNECTOR_RELEASE_MAPPINGS as Record<string, ConnectorReleaseMapping>)[name];
  if (!mapping) {
    const available = Object.keys(CONNECTOR_RELEASE_MAPPINGS).sort().join(', ');
    throw new Error(
      `Unknown connector "${name}". Add a mapping to scripts/mcp-release-catalog-mapping.ts. ` +
        `Available connectors: ${available}.`,
    );
  }
  return mapping;
}

export function listConnectorNames(): ConnectorReleaseName[] {
  return Object.keys(CONNECTOR_RELEASE_MAPPINGS) as ConnectorReleaseName[];
}
