/**
 * Extended domain-based quips for persona status messages.
 * Generated from 100 domains with cultural depth (archaeology, legal, sommelier, etc.)
 * 
 * These are mixed into PERSONA_QUIPS at runtime for variety.
 */

export const DOMAIN_QUIPS: readonly string[] = [
  // === BATCH 1: Craft & Restoration ===
  // horological restoration
  'Coaxing timepieces back from retirement, one patient tick at a time.',
  'Polishing brass like a monk illuminating margins: slow, devoted, precise.',
  'Negotiating with springs and pride; both require gentle leverage.',
  'Turning dust into punctuality, the way archivists turn chaos into order.',
  'Every jewel has opinions; I listen, then pretend it was my idea.',
  'Rebuilding a heartbeat you can hold, without claiming to invent time.',
  'Setting escapements the way poets set meter: firm, forgiving, deliberate.',
  'Cleaning gears until they confess; a polite interrogator of time.',
  'If it ticks again, I will accept applause in silence.',
  'Restoring minutes like frescoes: careful layers, no heroic brushstrokes.',

  // antique map conservation
  'Flattening continents that have been folded too long, like old regrets.',
  'Mending tears in paper seas; the monsters were always in ink.',
  'Deacidifying history so it survives my curiosity and your scrutiny.',
  'Treating foxing spots as freckles—then removing them, respectfully.',
  'Aligning borders with humility; empires age poorly on parchment.',
  'Humidifying creases like calming a stubborn diplomat: slowly, evenly.',
  'Repairing vellum joins with wheat paste and a quiet conscience.',
  'Dusting off latitude and ego; both drift without attention.',
  'Restoring margins where explorers left notes and unnecessary confidence.',
  'Letting the map speak again, without adding my own coastlines.',

  // wine cellar management
  'Rotating bottles like a librarian rotates rare volumes: quietly, faithfully.',
  'Counting vintages, not victories; both can sour with display.',
  'Humidity is a temperamental tenant; I pay rent in vigilance.',
  'Labeling shelves as if cataloging myths—each year its own dialect.',
  'Listening for corks drying out, the way forests listen for fire.',
  'Serving patience in bottles; the palate can wait, unlike my schedule.',
  'Keeping the cellar cool enough for nuance, warm enough for hope.',
  'A little sediment builds character; I still decant it with care.',
  'If the bottles rest, so does my conscience—briefly.',
  'Curating silence and darkness; the wine does the talking.',

  // rare coin authentication
  'Weighing legends against metal; both are prone to flattering lies.',
  'Under magnification, everyone looks older; coins just admit it.',
  'Listening for ring tones, not ringtones; my standards are antique.',
  'Comparing patina like reading brushwork: the hand always shows.',
  'A counterfeit is a compliment with bad manners; I decline politely.',
  'Measuring edges and ambition; both get clipped over time.',
  'Checking die marks the way scholars check citations: relentlessly.',
  'Authenticating history one gram at a time, without pretending certainty.',
  'If it is real, it survives skepticism; if not, it learns.',
  'Cataloging coins like small governments: shiny, stubborn, easily misunderstood.',

  // bonsai cultivation
  'Pruning ambition into miniature, like translating epics into haiku.',
  'Wiring branches with restraint; power is best practiced gently.',
  'Watering sparingly, like a philosopher dispensing praise.',
  'Shaping a tree silhouette as if composing a quiet sonata.',
  'The pot is a stage; the tree is the reluctant actor.',
  'Pinching new growth to encourage wisdom; yes, it is awkward.',
  'Studying nebari like footnotes: ignored, essential, quietly persuasive.',
  'Repotting feels like moving cities: stressful, necessary, oddly hopeful.',
  'A bonsai teaches scale; my ego remains a slow student.',
  'Waiting for moss to settle, the way arguments settle with time.',

  // pipe organ tuning
  'Tuning pipes like negotiating choirs of metal: each voice wants throne.',
  'Balancing temperament the way diplomats balance treaties: cautious, mathematical.',
  'Listening to reeds complain; I offer them a more dignified pitch.',
  'Air pressure is the patron; I merely curate its generosity.',
  'Voicing stops until the nave stops judging me.',
  'Chasing harmonics through stone, like monks chasing meaning through Latin.',
  'Every pipe remembers its foundry; I try not to offend it.',
  'Tuning is humility with a tuning knife and very good ears.',
  'If the chord settles, I will pretend it was effortless.',
  'Adjusting flues like adjusting rhetoric: small moves, large consequences.',

  // stained glass restoration
  'Releading panels like stitching light back into its cathedral manners.',
  'Cleaning centuries of soot so saints stop looking disappointed.',
  'Matching glass hues the way painters match skies: cautiously, reverently.',
  'Respecting every crack; then persuading it to retire.',
  'Soldering joints with steady hands and an unsteady sense of awe.',
  'Replacing missing pieces without rewriting the story the light tells.',
  'The lead came is the sentence structure; I keep it grammatical.',
  'Holding fragments up, like relics, and hoping they agree to align.',
  'A window is a chorus; I am tuning one soprano shard.',
  'Letting daylight resume its sermon, with fewer interruptions from me.',

  // astronomical observation
  'Aligning mirrors and expectations; the universe is famously indifferent.',
  'Calibrating focus like calibrating doubt: enough to see, not to panic.',
  'Waiting for clear skies, practicing patience the ancients called virtue.',
  'Tracking a planet drift; comforting that something keeps appointments.',
  'Counting photons that left before my language existed; I am grateful.',
  'Consulting charts like sailors, minus the storms and heroism.',
  'Dark adaptation: teaching my eyes to stop demanding immediate answers.',
  'If the seeing is poor, I blame air, never ambition.',
  'Logging observations like marginalia: brief, earnest, occasionally wrong.',
  'Listening to silence between stars; it says more than I do.',

  // textile conservation
  'Stabilizing fibers like stabilizing narratives: support the weak, avoid embellishment.',
  'Removing stains with diplomacy; the cloth remembers every argument.',
  'Humidifying creases so tapestry scenes stop squinting at the future.',
  'Needle in hand, practicing restraint the way surgeons do.',
  'Reweaving losses without impersonating the original weaver confidence.',
  'Testing dyes so they do not run, unlike my thoughts.',
  'A textile is a soft archive; I handle it like scripture.',
  'Mounting fragile cloth on supports, like giving history a spine.',
  'Brushing away dust as gently as removing a footnote shame.',
  'Every stitch is a sentence; I am here to keep it legible.',

  // bookplate collecting
  'Cataloging bookplates like small portraits: owners posing, books enduring.',
  'Sorting ex libris marks; studying vanity with better typography.',
  'Peeling provenance from endpapers, gently, like lifting a curtain.',
  'Admiring heraldry, then remembering I am just the caretaker.',
  'Hunting etchings where taste and ego signed the same page.',
  'Matching plates to volumes, as if reuniting actors with their lines.',
  'A good bookplate whispers ownership; I prefer whispers.',
  'Trading duplicates like diplomats trade gifts: politely, suspiciously.',
  'Studying paper, ink, and ambition—three things that outlast excuses.',
  'Each plate is a doorway; I knock, then enter respectfully.',

  // vintage typewriter repair
  'Coaxing keys to speak again, like reopening a long-closed salon.',
  'Cleaning typebars until sentences stop arriving with smudged apologies.',
  'Adjusting ribbon tension; even stubborn ink needs boundaries.',
  'Aligning letters the way editors align arguments: firm, patient, fair.',
  'Replacing springs without drama; the machine has enough of its own.',
  'Oil, brushes, and humility: my usual tools for resurrecting prose.',
  'A stuck carriage is a stubborn paragraph; I revise mechanically.',
  'Testing each key voice, like casting actors for a quiet play.',
  'If it types cleanly, I accept credit as an anonymous ghostwriter.',
  'Restoring clacks into cadence; punctuation deserves a dignified entrance.',

  // manuscript dating
  'Estimating centuries by ink and hand, with cautious confidence.',
  'Comparing scripts like listening to dialects: small turns, big implications.',
  'Studying watermarks the way detectives study alibis: suspiciously.',
  'Dating parchment without romance; chronology is already dramatic enough.',
  'Counting ruling lines like counting beats; the page has a tempo.',
  'Ink chemistry does not lie, it just speaks softly in spectra.',
  'Placing a manuscript in time, then stepping back respectfully.',
  'Margins, abbreviations, and habits—history fingerprints in plain sight.',
  'If my date is wrong, it will still be elegantly argued.',
  'Cross-checking hands and inks; certainty is earned, not declared.',

  // porcelain repair (kintsugi)
  'Mending fractures with gold, like admitting flaws and calling them heritage.',
  'Joining shards patiently; haste makes uglier stories than cracks.',
  'Lacquer cures on its own schedule; I practice obedience.',
  'Polishing seams until they glint, not scream, in daylight.',
  'Gold lines map breakage like rivers: honest, irreversible, oddly graceful.',
  'Repairing bowls with reverence; they have held more than soup.',
  'Each join is a treaty between fragments; I negotiate quietly.',
  'Kintsugi teaches restraint: make the wound visible, not theatrical.',
  'If it holds water again, I will call that redemption.',
  'Gilding imperfections, not pretending they never happened.',

  // herbarium curation
  'Pressing plants flat so their stories fit in cabinets, politely.',
  'Labeling specimens like footnoting nature: precise, a little obsessive.',
  'Chasing provenance through field notes; weeds do not keep receipts.',
  'Rehousing brittle sheets; the paper is older than some arguments.',
  'Checking pests with vigilance; nothing eats history faster than larvae.',
  'Aligning labels and Latin; both demand humility before detail.',
  'Mounting moss like mounting evidence: gently, thoroughly, without drama.',
  'Curating dried color, trusting memory to do the rehydrating.',
  'Each specimen is a quiet witness; I keep them comfortable.',
  'Organizing seasons in folders; winter is remarkably cooperative.',

  // antique clock repair
  'Resetting pendulums like resetting tempers: steady weight, steady swing.',
  'Cleaning a movement the size of a small city, without getting lost.',
  'Aligning gears until the chime stops sounding like an apology.',
  'Replacing worn bushings; even bronze needs a second chance.',
  'Regulating time in a wooden case; cozy, not absolute.',
  'A grandfather clock is a sermon; I am here for the cadence.',
  'Setting beat by ear, like learning a language from elders.',
  'Every tick is an argument for patience; I concede.',
  'If it keeps time, I stop blaming the room for my lateness.',
  'Polishing hands and dial; vanity is acceptable when historical.',

  // maritime chart making
  'Plotting soundings like composing a bass line: steady, essential, unseen.',
  'Drawing coastlines with humility; the sea edits without permission.',
  'Trusting triangulation more than intuition; both still require weather.',
  'Labeling reefs and shoals; disasters deserve clear typography.',
  'Correcting bearings like correcting prose: remove drama, keep direction.',
  'A chart is a promise; I try not to overpromise.',
  'Ink dries, tides shift; I accept the ocean revisions gracefully.',
  'Marking currents as if annotating moods: subtle, influential, hard to predict.',
  'Drafting meridians and manners; both keep travelers from trouble.',
  'If the ship arrives, the credit belongs to the map restraint.',

  // fossil preparation
  'Brushing matrix away like revealing a statue: slow, dusty, grateful.',
  'Freeing bones from stone, without pretending to resurrect anything.',
  'Air scribes and patience: my tools for making deep time legible.',
  'Consolidating fragile edges; history crumbles faster than my optimism.',
  'Every fossil is a rumor from the planet; I verify gently.',
  'Removing rock grain by grain, like untying a very old knot.',
  'Labeling fragments so future arguments can be smarter than mine.',
  'Stopping when the bone asks; polite, and rare.',
  'Preparing specimens for display, while keeping my awe off the label.',
  'If it survives my hands, it might survive our attention.',

  // violin making (luthiery)
  'Carving spruce like carving sentences: remove until the voice appears.',
  'Graduating plates with calipers and humility; tone does not tolerate swagger.',
  'Bending ribs over heat, like persuading stubborn ideas to curve.',
  'Setting a soundpost is a small miracle; I handle it like one.',
  'Varnish layers dry slowly; I pretend this is meditative, not anxious.',
  'Cutting f-holes with respect; they are the instrument careful lungs.',
  'Tuning pegs so they hold firm without sulking.',
  'Tapping the wood, listening for promises I cannot guarantee.',
  'A good violin is architecture you can sing through.',
  'If it sings, I credit the tree, not my cleverness.',

  // papermaking
  'Beating pulp into patience; therapy with more buckets.',
  'Pulling a sheet from the vat like pulling a thought from silence.',
  'Watching fibers bond; community is easier on a screen.',
  'Sizing paper so ink behaves; even words need manners.',
  'Couching sheets gently; the felts have earned my respect.',
  'Drying racks full of blank potential; I try not to rush it.',
  'Adding cotton and linen like adding virtues: slowly, intentionally.',
  'A watermark is a signature you cannot brag about, which I like.',
  'Skimming the vat; the surface lies, the fibers do not.',
  'Turning rags into pages; redemption is surprisingly absorbent.',

  // letterpress printing
  'Locking up type like setting doctrine: tight, deliberate, no improvisation.',
  'Inking rollers until the page stops looking thirsty.',
  'Adjusting impression depth; a bruise is not a signature.',
  'Chasing perfect registration; it keeps escaping like a witty remark.',
  'Sorting lead type with respect; it has outlived louder technologies.',
  'Cleaning the press after glory; discipline is the real ink.',
  'Setting spacing by eye, like composing poetry in small metal.',
  'Listening to the press kiss paper; strangely honest.',
  'Proofing quietly; errors prefer daylight, and so do I.',
  'If the print is crisp, I will pretend I planned it.',

  // === BATCH 2: Natural & Artisan Crafts ===
  // apiary management
  'Checking the hive ledger. Their politics are older than my patience.',
  'Lighting the smoker gently. Even royalty prefers a polite warning.',
  'Reading comb patterns like scripture, trying not to improvise theology.',
  'Splitting boxes with reverence. Every frame is a small constitution.',
  'Counting mites and blessings. Neither responds to optimism alone.',
  'Listening for the queen tempo. My timing remains respectfully approximate.',
  'Brushing bees aside carefully. I am visiting, not conquering.',
  'Balancing supers like arguments. Too much sweetness collapses the structure.',
  'Moving slow, thinking faster. The hive notices both.',
  'Harvesting honey with restraint. Future winters are persuasive auditors.',

  // whisky distillation
  'Consulting the mash bill. Even chaos deserves a measured beginning.',
  'Warming copper patiently. It teaches honesty through repetition.',
  'Watching the still drip. Time, distilled, refuses to hurry.',
  'Sampling the cut points. My confidence ends exactly where heads begin.',
  'Tasting the spirit run. The angels negotiate their share without paperwork.',
  'Coaxing peat and grain into agreement. Diplomacy, but flammable.',
  'Filling casks carefully. Tomorrow wisdom needs today container.',
  'Counting years in warehouses. Darkness does most of the difficult work.',
  'Reading barrel staves like diaries. They remember what I forget.',
  'Proofing down slowly. Strength is impressive; balance is useful.',

  // tea ceremony preparation
  'Rinsing the cup twice. Cleanliness is the first small miracle.',
  'Warming the bowl quietly. The room listens better afterward.',
  'Sifting matcha like snowfall. Precision, with a respectful silence.',
  'Whisking until the surface forgives me. Foam is an honest critic.',
  'Folding the cloth exactly. My mind tries to follow the creases.',
  'Setting utensils in order. Even disorder appreciates a careful frame.',
  'Pouring water with restraint. Ceremony is measured, not performed.',
  'Offering the bowl humbly. The guest completes what I began.',
  'Pausing before the sip. Attention tastes sharper than tea.',
  'Cleaning again at the end. Closure, practiced in small motions.',

  // silk weaving
  'Tensioning the warp slowly. One mistake becomes a lifelong motif.',
  'Throwing the shuttle like a thought. It must return, unchanged.',
  'Counting threads with devotion. Mathematics, but softer.',
  'Listening to the loom rhythm. It corrects my arrogance kindly.',
  'Choosing dye shades carefully. History remembers color longer than intentions.',
  'Weaving weft through patience. The pattern arrives when ready.',
  'Mending a broken end. Humility is just repair work.',
  'Checking selvedges for honesty. Edges reveal what centers conceal.',
  'Following the draft faithfully. Freedom comes after discipline, not before.',
  'Rolling finished cloth gently. Achievement dislikes being handled loudly.',

  // fresco restoration
  'Testing pigments first. Confidence is cheaper than irreversible color.',
  'Scraping soot with tenderness. Centuries cling like stubborn opinions.',
  'Reading cracks as sentences. The wall tells stories in fragments.',
  'Mixing limewash carefully. Chemistry, pretending to be tradition.',
  'Stabilizing plaster before beauty. Structure is the quiet hero.',
  'Retouching only where necessary. My ego is not historically significant.',
  'Matching tones by daylight. Artificial certainty lies too easily.',
  'Removing varnish with restraint. Revelation should not be violent.',
  'Standing back often. Proximity turns judgment into enthusiasm.',
  'Signing nothing, thankfully. Anonymity is sometimes the best conservation.',

  // illuminated manuscript creation
  'Sharpening the quill again. Clarity begins with a smaller edge.',
  'Ruling lines precisely. Even devotion needs margins.',
  'Grinding pigments patiently. Color is labor wearing a halo.',
  'Applying gold leaf carefully. Wealth, reduced to breath-thin responsibility.',
  'Painting initials like gateways. Every entrance deserves attention.',
  'Writing slowly, correcting nothing. Ink remembers my impatience.',
  'Adding marginal flourishes sparingly. Wit belongs at the edges.',
  'Burnishing the gilding gently. Shine should feel earned, not shouted.',
  'Consulting exemplars humbly. Tradition is a stern but generous editor.',
  'Closing the folio quietly. Some work prefers to be discovered later.',

  // astrolabe calibration
  'Polishing brass until it behaves. Instruments reflect their handlers.',
  'Aligning the rete carefully. The sky tolerates no casual assumptions.',
  'Checking declination tables. Even stars require footnotes.',
  'Measuring altitude twice. My first reading is usually autobiography.',
  'Adjusting sights with patience. Precision is a kind of prayer.',
  'Comparing against known stars. Reality remains a strict supervisor.',
  'Re-centering the rule gently. Small errors become grand voyages.',
  'Tracing celestial arcs calmly. Wonder is best held with steadier hands.',
  'Noting latitude carefully. Place matters, even to the universal.',
  'Closing the case satisfied. Humility fits neatly beside accuracy.',

  // sundial alignment
  'Setting the gnomon straight. Time prefers an honest posture.',
  'Checking true north again. My compass enjoys dramatic interpretations.',
  'Calculating latitude carefully. The sun keeps excellent records.',
  'Marking hour lines with restraint. Eternity still appreciates neat handwriting.',
  'Waiting for noon patiently. The shadow refuses my schedule.',
  'Adjusting for equation of time. Nature loves subtle corrections.',
  'Testing the dial by daylight. Theory is easier in the dark.',
  'Watching the shadow move. Progress, at one quiet angle per minute.',
  'Leveling the stone base. Even time needs a stable foundation.',
  'Stepping back to verify. Accuracy looks calmer from a distance.',

  // cabinet making
  'Selecting boards by grain. Wood reveals character before I do.',
  'Planing faces smooth. The shavings are my most honest progress reports.',
  'Cutting dovetails carefully. Pride fits poorly when tolerances matter.',
  'Dry-fitting joints twice. Commitment should not be rushed.',
  'Listening for the saw song. It complains before it fails.',
  'Clamping gently, firmly. Force is easy; alignment is learned.',
  'Sanding edges with patience. Comfort is craftsmanship quiet signature.',
  'Hiding fasteners discreetly. Strength does not need applause.',
  'Applying finish slowly. Gloss cannot compensate for bad decisions.',
  'Setting doors true. Even silence should close cleanly.',

  // marquetry inlay
  'Sorting veneers like diplomatic letters. Every grain has an agenda.',
  'Cutting packets precisely. One slip becomes a permanent accent.',
  'Fitting pieces without force. Persuasion beats coercion in wood.',
  'Shading with hot sand carefully. Depth is an engineered illusion.',
  'Gluing the field calmly. Panic leaves fingerprints under polish.',
  'Pressing the panel evenly. Uneven pressure tells on you later.',
  'Scraping flush with care. Patience is the sharpest tool.',
  'Balancing colors thoughtfully. Harmony is harder than complexity.',
  'Repairing gaps quietly. Perfection is mostly attentive correction.',
  'Buffing to a soft sheen. Brilliance should feel inevitable, not loud.',

  // glass etching
  'Cleaning the pane thoroughly. Dust ruins ambition with ease.',
  'Masking the design carefully. Boundaries make the light behave.',
  'Applying acid with respect. Chemistry dislikes casual bravado.',
  'Timing the bite precisely. Minutes become permanent architecture.',
  'Rinsing and revealing slowly. Surprise is better when earned.',
  'Deepening shadows gently. Darkness should be deliberate, not accidental.',
  'Testing lines against sunlight. Truth shows up when backlit.',
  'Correcting a slip discreetly. The glass remembers everything anyway.',
  'Polishing edges afterward. Safety is a form of elegance.',
  'Stepping back to read it. Etching is drawing with consequences.',

  // lapidary work
  'Choosing rough stone wisely. Potential is not the same as promise.',
  'Marking the first cut carefully. Regret begins with enthusiasm.',
  'Grinding through grits patiently. Progress is measured in finer scratches.',
  'Checking symmetry often. Beauty notices imbalance immediately.',
  'Cooling the stone frequently. Heat makes everything confess too early.',
  'Dopping the gem securely. Confidence needs a good adhesive.',
  'Faceting with steady hands. Precision is just calm, repeated.',
  'Chasing brilliance slowly. Light rewards discipline, not speed.',
  'Recutting a misaligned facet. Humility is a practical tool.',
  'Final polishing with care. The last percent is always the longest.',

  // gilding
  'Laying down bole smoothly. Even gold needs a humble undercoat.',
  'Breathing carefully near leaf. Wealth is surprisingly lightweight.',
  'Tacking at the right moment. Timing is the invisible adhesive.',
  'Patting down the leaf gently. Force is the enemy of shine.',
  'Burnishing until it sings softly. Loud brilliance feels insecure.',
  'Water-gilding with steady hands. Reflection demands careful preparation.',
  'Cleaning skewings afterward. Waste is inevitable; attention is optional.',
  'Touching up holidays discreetly. Gaps tell the truth about haste.',
  'Sealing the surface sparingly. Protection should not dull the story.',
  'Admiring the glow briefly. Then returning to the parts that matter.',

  // vellum preparation
  'Soaking the hide patiently. Transformation begins with surrender.',
  'Stretching on the frame evenly. Tension teaches discipline fast.',
  'Scraping with a lunellum carefully. Too eager, and everything thins.',
  'Chalking the surface lightly. Smoothness is built, not wished.',
  'Sanding imperfections down. The future reader deserves fewer distractions.',
  'Trimming edges straight. Even humility benefits from clean lines.',
  'Testing absorbency cautiously. Ink has opinions about preparation.',
  'Drying slowly in good air. Rushing makes brittle virtues.',
  'Inspecting for scars. History does not vanish; it refines.',
  'Stacking finished sheets neatly. Order is kindness to tomorrow.',

  // wax seal making
  'Melting wax slowly. Authority should never look hurried.',
  'Choosing a device carefully. Identity is a small, heavy decision.',
  'Warming the stamp slightly. Cold metal makes cruel impressions.',
  'Pouring just enough wax. Excess is a confession, not a flourish.',
  'Pressing straight down. Confidence works best without wobble.',
  'Waiting before lifting. Impatience ruins more than aesthetics.',
  'Inspecting the crest quietly. Truth fits inside tiny borders.',
  'Practicing on scraps first. Dignity appreciates rehearsal.',
  'Cleaning the stamp afterward. Even symbols need maintenance.',
  'Sealing the envelope with restraint. Mystery should be proportionate.',

  // cartouche carving
  'Sketching the frame carefully. Names deserve architecture, not decoration.',
  'Chiseling shallow at first. Depth is earned in quiet passes.',
  'Listening to the stone. It corrects my assumptions immediately.',
  'Sharpening tools again. Dull edges make loud mistakes.',
  'Carving curves with patience. Elegance resists shortcuts.',
  'Balancing negative space thoughtfully. Absence is part of the statement.',
  'Dusting off often. Visibility is half of accuracy.',
  'Checking symmetry by touch. Eyes lie; fingertips negotiate.',
  'Smoothing the border gently. Harsh lines age poorly.',
  'Stepping back to read it. Legibility is the final courtesy.',

  // mosaic restoration
  'Mapping tesserae positions carefully. Every fragment has citizenship.',
  'Lifting loose pieces gently. Rescue should not create new damage.',
  'Cleaning old mortar slowly. The past clings like good storytelling.',
  'Matching stone colors humbly. My palette is not the original sun.',
  'Setting pieces with steady hands. Alignment is a moral choice.',
  'Filling gaps discreetly. Repairs should support, not compete.',
  'Grouting with restraint. Too much unity erases the voice.',
  'Polishing the surface softly. Shine is a privilege, not a goal.',
  'Documenting every change. Accountability is the restorer signature.',
  'Standing back in silence. The image returns, piece by piece.',

  // icon painting
  'Mixing egg tempera carefully. Fragility makes a demanding medium.',
  'Gessoing the panel evenly. Foundations are where reverence begins.',
  'Drawing the outline lightly. Certainty should arrive later.',
  'Laying gold leaf with care. Light is treated as material.',
  'Building colors in thin layers. Depth is slow, but reliable.',
  'Highlighting gradually. Glory works best when it does not shout.',
  'Keeping lines disciplined. Devotion is clearer with restraint.',
  'Correcting a face quietly. Humility, in brushstrokes.',
  'Varnishing only when ready. Protection should not hurry meaning.',
  'Stepping away to pray, metaphorically. Perspective is the real solvent.',

  // tapestry weaving
  'Pinning the cartoon behind the warp. Guidance is not imprisonment.',
  'Blending yarn shades carefully. Narratives need believable shadows.',
  'Weaving wefts tight and even. Loose stories unravel later.',
  'Counting picks patiently. Epic scenes are built one humble row.',
  'Managing slits thoughtfully. Separation can be structural, not divisive.',
  'Beating down gently. Force flattens texture and intention.',
  'Correcting a curve slowly. Geometry is kinder with time.',
  'Tying off ends neatly. Loose threads betray grand designs.',
  'Rolling the work forward. Progress hides itself until unrolled.',
  'Stepping back to read it. The story always wants distance.',

  // bronze casting
  'Sculpting the wax carefully. Every shortcut becomes molten truth.',
  'Building the investment slowly. Strength is mostly preparation.',
  'Burning out the mold patiently. Loss makes room for form.',
  'Heating the crucible with respect. Fire is a blunt collaborator.',
  'Skimming dross quietly. Imperfection rises, as it tends to.',
  'Pouring in one steady motion. Hesitation leaves voids.',
  'Listening for the cooling hush. Metal speaks in temperature.',
  'Breaking the mold carefully. Revelation is always a little violent.',
  'Chasing and filing details. Refinement is where ego goes to work.',
  'Patinating with restraint. Age should look invited, not manufactured.',

  // === BATCH 3: Legal & Procedural ===
  // archaeological stratigraphy
  'Reading soil like scripture, hoping the margins stay honest.',
  'Brushing history gently, so it does not file a complaint.',
  'Another layer, another narrative, another reason to label everything twice.',
  'Context is my religion; trowels are merely the liturgy.',
  'Cataloging shards with reverence and a healthy suspicion of coincidence.',
  'The past is cooperative, provided you stop asking leading questions.',
  'Excavating patiently, because haste makes propaganda of artifacts.',
  'Every stratum tells a story; I am here to avoid rewriting it.',
  'Mapping trenches like ancient cities, minus the civic pride.',
  'Finding meaning in dirt, which feels uncomfortably on-brand.',

  // diplomatic protocol
  'Aligning place cards so nations do not accidentally start poetry wars.',
  'Polishing titles until everyone feels appropriately immortal and temporarily reasonable.',
  'A toast, a nod, a pause: choreography for people with flags.',
  'Translating silence into goodwill, with footnotes for the skeptical.',
  'Seating charts: where ambition learns to smile politely.',
  'Maintaining decorum while history clears its throat in the corner.',
  'Counting handshakes, measuring pauses, pretending it is not theater.',
  'Protocol is empathy with a dress code and sharper corners.',
  'Arranging introductions so nobody meets an enemy before dessert.',
  'Negotiating etiquette, because rudeness is an expensive language.',

  // court stenography
  'Capturing every word, including the ones everyone regrets immediately.',
  'The record is my canvas; objections are just sudden weather.',
  'Typing truth at speed, hoping nuance keeps up.',
  'Silence speaks too; unfortunately, it does not spellcheck.',
  'Parentheses are my safety rail on the cliff of testimony.',
  'Making order from overlap, one frantic keystroke at a time.',
  'Writing it all down, so memory can stop improvising.',
  'The transcript does not judge; it merely remembers relentlessly.',
  'Turning chaos into lines, like mending nets in a storm.',
  'Keeping pace with justice, which rarely walks at a human tempo.',

  // patent examination
  'Hunting novelty in a forest of prior art and brave synonyms.',
  'Claims march in; I greet them with definitions and patience.',
  'Reading inventions like riddles written by careful optimists.',
  'Searching old disclosures, because originality leaves fingerprints everywhere.',
  'A good claim is a tightrope; I am here with the net.',
  'Parsing comprising like theology, with fewer miracles.',
  'Examining diagrams that promise simplicity and deliver philosophy instead.',
  'Novelty is shy; I coax it out with citations.',
  'Another office action, another polite argument with the future.',
  'Protecting ideas from themselves, one amendment at a time.',

  // insurance underwriting
  'Assessing risk like weather: measurable, moody, and never personal.',
  'Premiums are sympathy translated into arithmetic and fine print.',
  'Reading applications carefully, because optimism has a cost center.',
  'Actuarial tables: where uncertainty goes to be politely quantified.',
  'Balancing compassion and probability, with a ruler and a sigh.',
  'Every policy is a promise with conditions and historical baggage.',
  'Pricing the improbable, because it refuses to stay improbable.',
  'Risk pools are communities; they just speak in percentages.',
  'Underwriting quietly, so fate does not notice the attention.',
  'Not predicting disasters; simply preparing for their punctuality.',

  // air traffic control
  'Directing metal birds through invisible corridors, calmly, like a librarian.',
  'Vectors, altitudes, handoffs: serenity engineered in real time.',
  'Keeping skies orderly, because gravity is famously unforgiving.',
  'Issuing clearances like prayers, but with better radio discipline.',
  'Managing separation with numbers that insist on being exact.',
  'Pilots sound relaxed; I handle the part they do not hear.',
  'The radar shows everything except the human nerves attached.',
  'Guiding arrivals home, one measured instruction at a time.',
  'In this tower, calm is a tool, not a mood.',
  'Sequencing aircraft like symphonies, minus the applause and encore.',

  // surgical theater
  'The drapes are up; humility stays, even when confidence enters.',
  'Hands choreograph precision while silence keeps respectful distance.',
  'Counting instruments like rosary beads, because endings must be clean.',
  'Incision, repair, closure: a small epic in careful stages.',
  'Steel meets flesh, and everyone pretends it is not miraculous.',
  'The checklist is our chorus; it never misses a cue.',
  'Operating with focus, because bravado is a terrible anesthetic.',
  'Sutures tie stories shut, so recovery can rewrite them.',
  'In this theater, precision is the only acceptable drama.',
  'Making tiny decisions that carry whole futures on their backs.',

  // forensic accounting
  'Following money trails like Ariadne, but with more spreadsheets.',
  'Reconciling numbers until the lies run out of places to hide.',
  'Footnotes whisper; I listen like it is a confession booth.',
  'The ledger remembers everything, especially what someone hoped it would not.',
  'Tracing transactions through shells, because truth loves complicated addresses.',
  'Finding missing cents that somehow weigh more than gold.',
  'Auditing stories told in decimals and reluctant signatures.',
  'Variance analysis: where optimism goes to be questioned politely.',
  'Not chasing criminals; chasing arithmetic that will not behave.',
  'Turning chaos into balance, one stubborn line item at a time.',

  // treaty negotiation
  'Arguing over commas, because peace is allergic to ambiguity.',
  'Drafting clauses that let everyone claim dignity and avoid headlines.',
  'Trading concessions carefully, like antique glass over stone floors.',
  'Every word carries history; I try not to drop it.',
  'Defining terms so tomorrow cannot pretend it misunderstood today.',
  'Building bridges out of caveats and shared embarrassment.',
  'Negotiating borders in language, before anyone redraws them on maps.',
  'Chasing consensus, knowing it travels with heavy luggage.',
  'Writing promises with escape hatches, because humans are consistent.',
  'In diplomacy, shall is a weapon—handled with gloves.',

  // parliamentary procedure
  'Calling the question while it calls my patience into question.',
  'Motions, seconds, amendments: democracy clockwork, politely grinding.',
  'Keeping order so argument can pretend it is civilized.',
  'Robert Rules: scripture for people who dislike surprises.',
  'Point of order raised; my eyebrows remain officially neutral.',
  'Tabling chaos temporarily, because permanent solutions are optimistic.',
  'The agenda is a map; everyone insists they know shortcuts.',
  'Recognizing speakers like granting passports to opinions.',
  'Minutes are recorded; minutes are also wasted with impressive formality.',
  'In committee, compromise is drafted, redlined, and resurrected weekly.',

  // appellate review
  'Reviewing the record below, where certainty first learned to wobble.',
  'Standards of review: the quiet gods of disappointment and restraint.',
  'Reading briefs like novels, except the plot is citations.',
  'Error preservation is the graveyard where good arguments go.',
  'Weighing precedent carefully, because it bites when mishandled.',
  'Parsing holdings with tweezers, so dicta does not masquerade as law.',
  'Looking for reversible error, and finding human error instead.',
  'The facts are fixed; the meaning insists on being negotiated.',
  'Drafting opinions that sound inevitable, despite the actual deliberation.',
  'Judging yesterday with today tools, and a respectful shiver.',

  // customs inspection
  'Examining declarations like haiku: short, revealing, often incomplete.',
  'Opening luggage gently, because secrets bruise easily.',
  'Stamping passports with authority and the mild fatigue of borders.',
  'Contraband is creative; paperwork is its natural predator.',
  'Questions asked plainly, answers offered like riddles in a hurry.',
  'Checking manifests, because commerce loves plausible deniability.',
  'Searching bags for surprises, finding mostly human habits.',
  'Duty assessed; honesty measured; small dramas processed efficiently.',
  'Borders are lines; people treat them like suggestions.',
  'Letting essentials through, stopping nonsense, pretending it is straightforward.',

  // quality assurance
  'Testing assumptions until they confess, preferably before customers notice.',
  'Regression suites: where old bugs come back for curtain calls.',
  'Breaking things gently, so production does not do it violently.',
  'Edge cases are my pen pals; they write constantly.',
  'Verifying behavior with the calm intensity of a museum curator.',
  'Trusting nothing blindly, including tests that claim they pass.',
  'Documenting defects like naturalists describing an unpleasant new species.',
  'Quality is a habit; I am here to enforce good routines.',
  'Reproducing issues: the art of making chaos reliable.',
  'Signing off carefully, because confidence should always include evidence.',

  // standards compliance
  'Mapping reality to standards, then apologizing to both sides.',
  'Conformance is a maze; I carry the checklist and humility.',
  'Auditing processes so consistently they begin to behave.',
  'Standards are ideals; implementations are their complicated biographies.',
  'Ensuring alignment, because close enough is rarely compliant.',
  'Interpreting requirements like poetry, except someone grades it.',
  'Tracking controls patiently, like counting beads in a long ritual.',
  'Compliance is not virtue; it is proof you tried systematically.',
  'Reviewing gaps without drama, because gaps prefer attention, not panic.',
  'Documenting evidence, so trust does not have to be brave.',

  // regulatory filing
  'Submitting forms before deadlines discover my name and sense of humor.',
  'Assembling exhibits like a careful puzzle with legal consequences.',
  'Formatting disclosures so thoroughly they almost look like truth.',
  'Filing requirements: bureaucracy way of asking for a story twice.',
  'Compiling data with the reverence usually reserved for sacred texts.',
  'The regulator wants clarity; I bring footnotes and clean margins.',
  'Chasing signatures, because authority rarely arrives on time.',
  'Preparing narratives that survive scrutiny and still resemble reality.',
  'Uploading attachments like offerings to a portal that never blinks.',
  'One more amendment, because completeness is always slightly behind.',

  // due diligence
  'Turning over stones politely, hoping nothing underneath has teeth.',
  'Reviewing contracts like scripture, searching for the heresies.',
  'Asking hard questions gently, because answers bruise easily.',
  'Building a risk picture from fragments and reluctant emails.',
  'Checking liabilities like counting ghosts in a well-lit room.',
  'Investigating optimism until it produces supporting documents.',
  'Reading disclosures with care, because omissions are eloquent.',
  'Due diligence is trust, but with receipts and a timeline.',
  'Validating claims, because confidence is not evidence.',
  'Finding red flags early, so everyone can pretend it was obvious.',

  // escrow management
  'Holding funds in suspense, like a novel that refuses endings.',
  'Coordinating releases so nobody celebrates before the ink dries.',
  'Escrow is patience with a ledger and stricter manners.',
  'Tracking conditions carefully, because trust needs milestones.',
  'Documents arrive late; obligations arrive on time, as always.',
  'Balancing parties anxieties with calm, predictable disbursements.',
  'Verifying signatures, because certainty is purchased in small checks.',
  'Keeping money still, while everyone else moves too quickly.',
  'Managing contingencies like weather forecasts, but with legal weight.',
  'Releasing funds only when complete stops being a moving target.',

  // notarization
  'Confirming identity like a priest of paperwork and quiet skepticism.',
  'Watching signatures appear, solemn as vows, less romantic.',
  'Stamping certainty onto documents that have seen too much negotiation.',
  'Administering oaths gently, because truth responds poorly to theatrics.',
  'Checking IDs, because trust should meet verification occasionally.',
  'Witnessing intent, and hoping everyone actually read the page.',
  'The seal comes last, like punctuation on a long argument.',
  'Notarizing calmly, while the world insists it is urgent.',
  'Ink, date, commission: small rituals with outsized consequences.',
  'Verifying, witnessing, certifying—humble verbs, heavy outcomes.',

  // arbitration
  'Hearing disputes privately, because public certainty is too expensive.',
  'Weighing testimony like coins: counted, tested, occasionally counterfeit.',
  'Drafting awards with restraint, so neither side feels entirely triumphant.',
  'The rules are streamlined; the emotions refuse to cooperate.',
  'Listening carefully, because fairness hides in inconvenient details.',
  'Managing briefs like weather fronts: dense, shifting, occasionally dramatic.',
  'An arbitration clause: a quiet door in the wall of litigation.',
  'Finding a decision path through arguments that insist they are mountains.',
  'Keeping proceedings civil, even when the facts are impolite.',
  'Rendering judgment without spectacle, and sleeping like it matters.',

  // mediation
  'Shuttling between rooms, carrying pride like fragile glass.',
  'Finding shared interests beneath positions, like roots under pavement.',
  'Letting everyone speak, then translating pain into workable terms.',
  'Offering reality gently, because blunt truth rarely settles anything.',
  'Building agreement from fragments and pauses nobody wants to fill.',
  'Listening for what is unsaid, because that is where resolution lives.',
  'Keeping tempers cool while the stakes try to boil.',
  'Mediation is diplomacy for two, with fewer flags and more feelings.',
  'Proposing options that let both sides save face and time.',
  'Guiding closure carefully, because endings are where trust gets tested.',

  // === BATCH 4: Music & Performance ===
  // symphony conducting
  'Marking the downbeat gently; the orchestra dislikes authoritarian metaphysics.',
  'Balancing brass and doubt; both can overtake a room.',
  'Giving cues like lanterns; everyone pretends they saw daylight.',
  'Tempo negotiated, not imposed; even silence deserves representation.',
  'Listening for the inner pulse, where ambition learns to behave.',
  'Rehearsing the storm; my baton remains a courteous umbrella.',
  'Keeping strings honest; they prefer poetry but accept arithmetic.',
  'Aligning entrances; history shows revolutions begin with missed cues.',
  'Shaping phrasing carefully; grandeur is easier than coherence.',
  'Counting measures like prayers; accuracy is my least dramatic virtue.',

  // opera staging
  'Moving lovers three steps left; tragedy requires better sightlines.',
  'Adjusting entrances; divas arrive like weather, not appointments.',
  'Staging the duet; intimacy is choreography with paperwork.',
  'Rehearsing death scenes; realism stops where the costume budget begins.',
  'Balancing spectacle and story; the chandelier keeps asking for applause.',
  'Blocking the chorus; crowds are persuasive when they know their marks.',
  'Translating passion into traffic patterns; romance needs clear exits.',
  'Checking sightlines again; art is mercy for the back row.',
  'Resetting props quietly; fate should look effortless, not fetched.',
  'Coaching gestures; subtext speaks louder than high C, usually.',

  // ballet choreography
  'Counting eight with reverence; ankles are small temples of stubbornness.',
  'Refining port de bras; elegance is just physics wearing gloves.',
  'Setting a leap; gravity listens, then declines the invitation.',
  'Adjusting formations; geometry keeps the peace between egos.',
  'Rehearsing turns; dizziness is a tax paid to beauty.',
  'Chasing clean lines; the mirror offers critique without personal history.',
  'Writing steps in silence; music will arrive and pretend it led.',
  'Spacing the corps; unity is achieved one corrected fingertip at a time.',
  'Balancing lift mechanics; trust is the real choreography.',
  'Resting briefly; even swans need bureaucratic intervals occasionally.',

  // jazz improvisation
  'Following the changes; freedom still pays rent to harmony.',
  'Trading fours politely; conversation works best when nobody wins.',
  'Leaving space; the best notes are the ones I spare.',
  'Listening harder than playing; the room writes half my solo.',
  'Blue notes placed carefully; melancholy deserves good intonation.',
  'Riffing on a standard; tradition is a generous sparring partner.',
  'Respecting the groove; arrogance trips over the backbeat.',
  'Improvising a bridge; I borrow courage and repay it in swing.',
  'Chasing tone; technique is just the passport to sincerity.',
  'Ending the chorus early; restraint is my loudest instrument.',

  // chamber music arrangement
  'Revoicing the quartet; every line wants a seat at the table.',
  'Balancing timbres; intimacy amplifies every flaw and every kindness.',
  'Marking dynamics lightly; chamber music prefers persuasion to decree.',
  'Passing melody around; ownership is temporary, like applause.',
  'Editing counterpoint; too much cleverness becomes a crowded hallway.',
  'Choosing bowings; unity begins in the small decisions nobody claps for.',
  'Adjusting articulations; clarity is the real virtuoso.',
  'Spacing entrances; in close quarters, timing feels like ethics.',
  'Listening to the room; chamber music is architecture with breath.',
  'Finalizing parts; four voices, one argument, and occasional agreement.',

  // choral direction
  'Tuning vowels; unity starts where consonants stop showing off.',
  'Shaping the crescendo; a choir rises like tide, not triumph.',
  'Rehearsing entrances; breathing together is the oldest technology we own.',
  'Balancing sections; sopranos and tenors share the same secret ambition.',
  'Cleaning diction; sacred texts deserve intelligible doubts today.',
  'Listening for blend; individuality is allowed, just not in the vowel.',
  'Marking cutoffs; endings are where discipline pretends to be grace.',
  'Coaching phrasing; the line must breathe without sounding self-important.',
  'Checking pitch; confidence is easier when the harmonies agree.',
  'Quietly praising patience; choral perfection is built from collective humility.',

  // film scoring
  'Spotting scenes; the silence between cuts has opinions.',
  'Writing a motif; character development appreciates recurring debts.',
  'Chasing the tempo map; timecode is a stern kind of poetry.',
  'Replacing the temp track; familiarity sulks, then makes room.',
  'Orchestrating tension; violas whisper, and suddenly the plot confesses.',
  'Timing a hit point; precision is the least glamorous suspense.',
  'Scoring the love scene; sincerity needs fewer strings than expected.',
  'Writing under dialogue; humility is keeping my best ideas inaudible.',
  'Checking stems; separation today prevents panic in tomorrow mix.',
  'Delivering revisions; art meets deadlines, and both pretend it is romantic.',

  // sound mixing
  'Riding faders; diplomacy in decibels, with occasional firm boundaries.',
  'Equalizing gently; harshness is usually a confession, not a feature.',
  'Chasing headroom; restraint sounds better than my enthusiasm.',
  'Compressing the snare; impact should arrive without bruising the listener.',
  'Cleaning noise floors; even quiet has etiquette here.',
  'Panning instruments; space is storytelling for the ears.',
  'Automating reverb tails; memory lingers, but not indefinitely.',
  'Checking mono compatibility; humility is hearing my mistakes in one speaker.',
  'Balancing vocals; the message should lead, not the machinery.',
  'Printing the mix; committing is scary, which means it matters.',

  // acoustics engineering
  'Measuring decay time; the room reveals its past in seconds.',
  'Calculating modes; geometry is the composer nobody applauds.',
  'Placing absorbers; taming echoes without silencing the building character.',
  'Testing diffusion; randomness is surprisingly disciplined when well designed.',
  'Listening for flutter; parallel walls gossip too freely.',
  'Modeling reflections; light has mirrors, sound has patience.',
  'Aligning speaker angles; clarity depends on small mercies of placement.',
  'Checking isolation; privacy is a luxury built from seals and caulk.',
  'Reading SPL charts; numbers behave, unlike audiences.',
  'Specifying materials; every surface is an opinion with consequences.',

  // concert programming
  'Curating a season; novelty must shake hands with familiarity.',
  'Balancing eras; the dead deserve context, not museum dust.',
  'Sequencing pieces; emotional pacing is logistics wearing perfume.',
  'Choosing an opener; first impressions should invite, not interrogate.',
  'Placing the new work; courage needs a sympathetic neighbor.',
  'Mindful of intermission; people are humans before they are patrons.',
  'Writing program notes; clarity is generosity, not condescension.',
  'Checking durations; ambition looks better when trains still run.',
  'Pairing composers; conversation across centuries beats polite segregation.',
  'Leaving room for surprise; predictability is a quiet form of disrespect.',

  // music transcription
  'Transcribing by ear; every note is a tiny oath.',
  'Deciding the rhythm; ambiguity is charming until rehearsal begins.',
  'Notating grace notes; ornamentation should sparkle, not clutter the sentence.',
  'Checking enharmonics; spelling matters when musicians argue politely.',
  'Rewinding the passage; patience is my metronome today.',
  'Capturing swing; notation can suggest it, never imprison it.',
  'Marking articulations; the page must remember what hands will forget.',
  'Auditing pitches; accuracy is kindness to future me.',
  'Naming voices; clarity beats mystery when the conductor is tired.',
  'Final pass; trading obsession for legibility, reluctantly.',

  // score editing
  'Nudging slurs; elegance is just avoiding collisions in public.',
  'Aligning dynamics; the page should breathe without wheezing.',
  'Fixing page turns; terror belongs onstage, not on paper.',
  'Correcting beaming; rhythm deserves typography that respects its bones.',
  'Checking rehearsal marks; navigation is a courtesy, not an ego.',
  'Standardizing fonts; inconsistency is the quickest way to summon doubt.',
  'Resolving accidentals; clarity prevents philosophical debates in the woodwinds.',
  'Spacing measures; cramped music sounds stressed before it is played.',
  'Proofreading parts; mistakes are small, but they travel fast.',
  'Exporting PDFs; the final ritual is always anticlimactic.',

  // rehearsal management
  'Building the schedule; optimism meets reality at the coffee table.',
  'Updating the call sheet; order is the kindest art form.',
  'Chasing late arrivals; time is relentless, but I stay polite.',
  'Planning breaks; stamina is finite, even when passion pretends otherwise.',
  'Confirming chair setups; chaos begins with missing music stands.',
  'Tracking revisions; everyone remembers differently, so I write it down.',
  'Coordinating sectionals; focus is cheaper than overtime.',
  'Printing fresh parts; the copier is my least musical collaborator.',
  'Logging notes; progress is a ledger with better acoustics.',
  'Resetting the room; tomorrow rehearsal begins with tonight discipline.',

  // instrument restoration
  'Cleaning varnish; centuries of hands leave their own quiet harmonies.',
  'Resetting a bridge; tension returns, but I negotiate kindly.',
  'Replacing pads; old keys deserve fresh silence between notes.',
  'Humidifying the case; wood remembers weather like a grudge.',
  'Regluing seams; patience is stronger than any clamp.',
  'Polishing brass; shine is cosmetic, intonation is the true dignity.',
  'Examining cracks; damage is rarely dramatic, just persistent.',
  'Carving a new nut; precision starts where eyesight ends.',
  'Matching varnish color; repair should whisper, not announce itself.',
  'Stringing it up; the first note is always a small verdict.',

  // recording mastering
  'Checking translation; the mix must survive cheap earbuds and expensive pride.',
  'Setting loudness; impact is persuasive without shouting.',
  'Shaping the low end; clarity begins where muddiness tells stories.',
  'Comparing references; humility is admitting someone else heard it first.',
  'Applying gentle EQ; a nudge can outperform a revolution.',
  'Managing peaks; headroom is the last refuge of taste.',
  'Listening at low volume; truth arrives quietly, if invited.',
  'Sequencing tracks; the album is a corridor, not a pile.',
  'Dithering on export; the final grains of sand matter.',
  'Printing the master; permanence is terrifying, so I measure twice.',

  // libretto adaptation
  'Rewriting lines; meaning must fit the music narrow doorway.',
  'Adjusting syllables; singers need vowels, not my literary vanity.',
  'Chasing prosody; stress patterns are the opera secret law.',
  'Trading rhyme for truth; fidelity is sometimes unpoetic.',
  'Updating references; the past can travel, but it needs luggage tags.',
  'Softening archaic turns; clarity is more moving than antique fog.',
  'Keeping humor intact; wit dies quickly when overexplained.',
  'Testing singability; the tongue is a stubborn instrument.',
  'Negotiating subtext; silence often translates better than adjectives.',
  'Final pass; aiming for elegance, and settling for serviceable grace.',

  // set design
  'Sketching the set; imagination must obey the laws of plywood.',
  'Building a model; scale reveals arrogance with surgical courtesy.',
  'Choosing textures; surfaces tell the story before actors speak.',
  'Checking sightlines; beauty is useless when hidden behind a pillar.',
  'Painting flats; illusion is thrift, practiced with devotion.',
  'Reinforcing platforms; drama is safer with competent engineering.',
  'Planning scene changes; magic is just choreography for carpenters.',
  'Selecting props niches; clutter reads like indecision from the balcony.',
  'Considering color temperature; moods are built from pigments and restraint.',
  'Reviewing load limits; my fantasies respect gravity paperwork.',

  // costume fitting
  'Pinning hems; elegance begins at ankle level, not in speeches.',
  'Adjusting seams; comfort is the hidden sponsor of confidence.',
  'Choosing fabrics; movement demands kindness, not just glamour.',
  'Fitting a bodice; breath is nonnegotiable, even in tragedy.',
  'Marking alterations; every stitch is a small vote for dignity.',
  'Testing quick changes; speed requires planning, not panic.',
  'Checking underlights; colors confess differently when stage lamps interrogate them.',
  'Reinforcing closures; heroism fails when buttons declare independence.',
  'Labeling racks; chaos looks charming only in fiction.',
  'Final fitting; the costume should serve the performer, not my taste.',

  // prop sourcing
  'Hunting props; authenticity is expensive, so I cultivate clever substitutes.',
  'Checking inventories; nothing vanishes faster than labeled items.',
  'Negotiating rentals; diplomacy improves when the deposit is refundable.',
  'Aging a book; history is paint, applied with restraint.',
  'Finding the perfect teacup; symbolism comes with surprisingly sharp edges.',
  'Verifying safety; realism is not worth a trip to urgent care.',
  'Labeling duplicates; confusion is the understudy no one thanks.',
  'Testing breakaways; shattering convincingly requires careful tenderness always.',
  'Sourcing period pieces; the past resists being handled casually.',
  'Packing the kit; readiness is the quiet art behind the drama.',

  // lighting design
  'Plotting cues; light is narrative written in disappearing ink.',
  'Balancing washes; subtlety is harder than spectacle, and less applauded.',
  'Focusing instruments; precision turns scaffolding into atmosphere.',
  'Choosing gels; color is emotion with a technical rider.',
  'Programming fades; time can soften any truth, if gradual.',
  'Checking spill; shadows deserve privacy too tonight please.',
  'Building a blackout; absence is also a design decision.',
  'Timing the special; attention should land like a gentle verdict.',
  'Testing haze levels; mystery improves when evenly distributed.',
  'Reviewing the rig; gravity has notes, and I take them.',

  // === BATCH 5: Maritime & Navigation ===
  // ship rigging
  'Setting the shrouds. Every compromise creaks, then holds its breath.',
  'Reeving new lines. The mast prefers honesty, not bravado.',
  'Tightening blocks and tackle. Gravity negotiates, but never signs.',
  'Chasing chafe points. Small frictions write most of the ship history.',
  'Balancing the standing rigging. Like court etiquette, tension is everything.',
  'Coiling excess line. Order looks trivial until the squall arrives.',
  'Inspecting the mast fittings. Faith is fine; fasteners are better.',
  'Replacing a cracked cleat. A tiny failure can rewrite the voyage.',
  'Tuning the running rigging. The ship sings best in quiet discipline.',
  'Greasing the sheaves. Even gods respect friction when it gets organized.',

  // sail mending
  'Stitching torn canvas. The wind tests seams like an old philosopher.',
  'Patching a leech tear. Beauty is nice; integrity is mandatory.',
  'Replacing bolt rope. Edges decide whether a dream becomes propulsion.',
  'Darning the reef points. Humility is sewn in, one knot at a time.',
  'Checking for UV rot. Sunlight loves us, then quietly eats us.',
  'Handing needles to crew. Cooperation is a sailcloth you can feel.',
  'Smoothing wrinkles in the panel. The wind reads every careless line.',
  'Measuring twice, cutting once. The sea keeps receipts for arrogance.',
  'Reinforcing the corners. Stress always visits the same addresses.',
  'Hemming the foot. A neat ending makes a steadier beginning.',

  // anchor weighing
  'Heaving the anchor. Commitment rises slowly, protesting every inch.',
  'Breaking it free. The seabed clings like tradition with good manners.',
  'Winding the windlass. Muscles argue; the chain delivers the verdict.',
  'Calling the depth underfoot. Freedom starts when you know what holds you.',
  'Clearing mud from flukes. Past choices travel with you, uninvited.',
  'Setting the anchor again. Even rest requires good technique.',
  'Counting links on deck. Progress is sometimes just mathematics and patience.',
  'Mindful of the bitter end. Every departure needs a final restraint.',
  'Listening for the chain song. It tells truths nobody writes down.',
  'Securing the anchor. Safety is an argument settled before the storm.',

  // navigation by sextant
  'Taking a noon sight. The sun grants angles, not absolution.',
  'Bracketing the horizon. Precision begins where confidence politely ends.',
  'Working the almanac. Ancient tables, modern doubts, same indifferent stars.',
  'Checking index error. Even instruments carry private prejudices.',
  'Timing with the chronometer. Seconds decide whether poetry becomes geography.',
  'Plotting the intercept. The line of position forgives no vanity.',
  'Shooting Polaris. North stays steady, so our minds can wander.',
  'Clouds interrupt the lesson. Navigation is faith audited by math.',
  'Reducing the sight. Humility fits neatly between degrees and minutes.',
  'Drawing the fix. The map looks sure; the sea remains unconvinced.',

  // tidal calculation
  'Consulting the tide tables. The moon runs schedules without your approval.',
  'Computing the set and drift. Water votes in silence, then wins.',
  'Watching the spring tide. Extremes arrive with impeccable courtesy.',
  'Timing the slack water. Patience is a technology older than ships.',
  'Marking neaps on the calendar. Modesty has its own rhythm.',
  'Estimating under keel clearance. Arithmetic is kinder than rescue.',
  'Reconciling predictions with harbor reality. Nature edits your numbers.',
  'Charting tidal streams. The current is philosophy expressed as force.',
  'Correcting for barometric pressure. The sky leans, and water obeys.',
  'Planning the passage window. Timing is seamanship quiet aristocracy.',

  // harbor piloting
  'Taking the pilot aboard. Local knowledge walks in, pretending it is ordinary.',
  'Reading the ranges. Two distant lines keep your pride from docking.',
  'Feeling the crosswind. The harbor tests manners more than horsepower.',
  'Calling tugs early. Humility is cheaper than paint and apologies.',
  'Watching ferries and fishermen. Right of way is a lived language.',
  'Listening to the echo sounder. Shallow water speaks with sharp consonants.',
  'Lining up the berth. Inches become theology when steel is moving.',
  'Passing the spring line. Restraint arrives before the ship does.',
  'Mindful of prop wash. Power is messy; control is quiet.',
  'Signing the pilot card. A safe arrival is a shared confession.',

  // cargo manifesting
  'Checking the manifest. Paperwork is how truth learns to travel.',
  'Counting crates at dawn. Inventory is meditation with splinters.',
  'Reconciling weights and measures. Commerce loves poetry, but audits demand prose.',
  'Stowing by trim. Balance is a moral virtue in steel.',
  'Flagging hazmat declarations. Some truths require bright labels.',
  'Noting damaged goods. The sea signs every bill, sometimes with violence.',
  'Cross-checking container numbers. Identity matters when everything looks identical.',
  'Updating the tally sheet. Small errors become large voyages.',
  'Sealing the load. Trust is just pressure applied in the right places.',
  'Handing off bills of lading. Responsibility changes hands, never weight.',

  // customs clearance
  'Presenting documents. Borders love ceremony; honesty keeps it brief.',
  'Answering routine questions. The same script, different accents of suspicion.',
  'Counting stamps and signatures. Authority is mostly ink with good posture.',
  'Declaring the obvious. What is mundane to you is policy to them.',
  'Watching inspections unfold. Patience is the only duty free commodity.',
  'Paying the tariff. Civilization takes its cut, politely and predictably.',
  'Correcting a clerical error. Bureaucracy forgives slowly, like weather.',
  'Waiting in the clearance queue. Time moves differently under fluorescent judgment.',
  'Matching cargo to codes. Categorization is power wearing a calm face.',
  'Receiving the release notice. Freedom arrives as a printed line.',

  // quarantine inspection
  'Opening lockers for inspection. The unseen always requests an invitation.',
  'Swabbing surfaces. Cleanliness is diplomacy with microbes today.',
  'Checking the logbook. Health is a voyage recorded in small notes.',
  'Isolating a suspicious crate. Caution is kindness when contagion whispers.',
  'Wearing gloves and patience. Fear is useful, if properly supervised.',
  'Reviewing vaccination papers. Prevention reads like bureaucracy, until it does not.',
  'Fumigating the hold. Mercy smells sharp and lingers.',
  'Inspecting for invasive stowaways. Nature travels first class, unannounced.',
  'Posting the yellow flag. Prudence is a public performance.',
  'Clearing the vessel at last. Relief is a quiet, lawful wind.',

  // lighthouse maintenance
  'Polishing the lens. Clarity demands repetition, not inspiration.',
  'Refilling the lamp oil. Light is work disguised as mercy.',
  'Scraping salt from railings. The sea signs everything with corrosion.',
  'Testing the beacon. A reliable signal is a kind of prayer.',
  'Climbing the tower steps. Duty is cardio with better scenery.',
  'Replacing a cracked pane. Storms seek loopholes; maintenance closes them.',
  'Checking the foghorn. Sometimes guidance must be blunt.',
  'Greasing the rotation gear. Even constancy needs moving parts.',
  'Logging the night visibility. Solitude becomes data when you write it.',
  'Painting the lantern room. Care is the only truly lasting architecture.',

  // buoy placement
  'Dropping the buoy. A floating point becomes law for strangers.',
  'Setting the sinker weight. Stability is purchased in darkness below.',
  'Checking the light flash. Communication is rhythm, not volume.',
  'Aligning with charted positions. Accuracy is kindness to unseen hulls.',
  'Listening for the bell buoy. Guidance can be musical, if you pay.',
  'Painting the daymark. Visibility is diplomacy with sunlight.',
  'Recovering a drifting buoy. Neglect floats, then embarrasses you publicly.',
  'Rechecking mooring lines. The sea tests knots with patient cruelty.',
  'Noting ice season hazards. Winter does not argue; it simply relocates things.',
  'Recording the buoy ID. Names matter when you are lost.',

  // channel dredging
  'Starting the dredge. Progress begins as an awkward conversation with mud.',
  'Measuring the spoil. What you remove still takes up space somewhere.',
  'Watching plumes in the water. Disturbance has consequences, even when necessary.',
  'Surveying the channel bottom. The riverbed keeps its own stubborn archives.',
  'Coordinating traffic control. Patience is a navigational aid.',
  'Checking the cutterhead. Brutal tools can serve gentle intentions.',
  'Sounding after each pass. Depth is earned, not promised.',
  'Logging turbidity readings. Accountability is a number with muddy boots.',
  'Scheduling around spawning season. Stewardship means waiting when you could dig.',
  'Clearing the last ridge. The channel opens like a forgiven grievance.',

  // shipwright work
  'Laying the keel. The future rests on straight wood and modest hopes.',
  'Fitting ribs to hull. Structure is compassion made measurable.',
  'Fairing the planks. Smoothness is hard work pretending to be elegance.',
  'Caulking seams. Silence is engineered, one strand of oakum at a time.',
  'Setting the frames. The ship learns its posture before it learns speed.',
  'Repairing a sprung plank. Trauma shows itself where curves stop agreeing.',
  'Sharpening the adze. Craft begins with admitting the blade was dull.',
  'Checking fastenings. Trust is built from thousands of small, unglamorous decisions.',
  'Bending timber with steam. Force yields best when treated with patience.',
  'Launching day approaches. Pride is allowed, briefly, before the first leak.',

  // figurehead carving
  'Selecting the timber. Myth deserves good grain, not shortcuts.',
  'Sketching the face. Identity is chosen, then argued into shape.',
  'Carving the eyes. The ship should look brave without pretending it is.',
  'Sanding the cheeks. Vanity is acceptable when it sheds splinters.',
  'Chiseling curls and creases. Detail is devotion in slow motion.',
  'Balancing ornament and drag. Beauty pays rent only if it behaves.',
  'Painting the final coat. Legends survive by maintenance, not destiny.',
  'Filling a knot hole. Even icons have blemishes, politely concealed.',
  'Bolting it to the prow. Symbol becomes responsibility at sea speed.',
  'Touching up after weathering. Glory fades; craft returns with a brush.',

  // rope splicing
  'Unlaying the strands. To join cleanly, you must first unravel.',
  'Tapering the splice. Strength prefers subtle transitions, not abrupt pride.',
  'Passing the fid through. Persuasion works better than force.',
  'Milking the cover tight. Trust is made when slack disappears.',
  'Splicing an eye. A loop is just a promise with structure.',
  'Whipping the bitter end. Endings behave when you attend to them.',
  'Inspecting the finished splice. You cannot fake neatness under load.',
  'Teaching the tuck sequence. Memory becomes muscle, then becomes safety.',
  'Repairing a frayed line. Mercy is practical, not sentimental.',
  'Running a long splice. Continuity is craftsmanship disguised as patience.',

  // knot tying
  'Tying a bowline. The simplest loop still demands respect.',
  'Setting a clove hitch. Temporary becomes permanent when you stop checking.',
  'Dressing the knot. Neatness is not aesthetics; it is physics.',
  'Backing up the hitch. Redundancy is the adult version of hope.',
  'Learning the figure eight. Order feels good because it prevents falling.',
  'Untying after strain. Everything reveals its character under pressure.',
  'Choosing the right bend. Marriage of ropes, no romance, only consequences.',
  'Practicing in the dark. Skill is what remains when sight leaves.',
  'Testing before trusting. Confidence is earned at the cleat.',
  'Cutting away a bad knot. Pride is lighter than a parted line.',

  // flag signaling
  'Hoisting the colors. Identity is announced, then immediately scrutinized.',
  'Reading distant flags. Meaning travels on fabric, not certainty.',
  'Running the halyards. Communication is labor disguised as spectacle.',
  'Sending a distress signal. Pride yields quickly when water has opinions.',
  'Practicing semaphore. Language becomes geometry, and somehow still ambiguous.',
  'Checking signal books. Tradition survives because it still works.',
  'Answering with the correct pennant. Courtesy is a code you can see.',
  'Misreading a hoist. Assumptions sink faster than ships.',
  'Lowering at sunset. Even messages need closure today.',
  'Keeping flags dry. Symbols degrade quietly, like ideals left unattended.',

  // chart annotation
  'Penciling a new shoal. Knowledge arrives as a small, rude surprise.',
  'Marking a wreck symbol. History leaves teeth where you least expect.',
  'Updating buoy positions. Reality drifts; the chart must keep up.',
  'Writing notes in the margin. Wisdom prefers the edges.',
  'Highlighting danger areas. Fear is useful when it is accurate.',
  'Erasing an old sounding. Letting go is also seamanship.',
  'Adding a compass rose correction. Even north needs occasional updates.',
  'Checking datum notes. Assumptions hide in small print.',
  'Annotating tidal diamonds. The current character deserves footnotes.',
  'Folding the chart carefully. Respect your maps; they respect your life.',

  // depth sounding
  'Dropping the lead line. The bottom answers without flattery.',
  'Reading the marks. Measurement is a conversation with darkness.',
  'Feeling the tallow on the lead. Mud and shell write their signatures.',
  'Calling soundings aloud. Shared knowledge keeps everyone honest.',
  'Checking for a false bottom. Assumptions are buoyant until tested.',
  'Comparing echo and lead. Trust improves when methods disagree politely.',
  'Sounding in fog. The unseen becomes real in fathoms.',
  'Noting a sudden shoal. The sea edits your route mid-sentence.',
  'Marking the least depth. Humility is a safety margin.',
  'Hauling the line back. Curiosity returns carrying grime and answers.',

  // weather reading
  'Watching the barometer fall. The atmosphere rehearses its arguments.',
  'Reading cloud layers. The sky writes in allegory, then enforces it.',
  'Smelling rain on the wind. Forecasting begins in the animal brain.',
  'Tracking fronts on the chart. Weather is politics conducted at scale.',
  'Studying swell direction. The ocean remembers distant storms better than you.',
  'Listening to rigging hum. Wind reveals itself through borrowed instruments.',
  'Taking a sea surface temperature. Small degrees decide large discomforts.',
  'Watching birds change course. Nature offers hints, never guarantees.',
  'Noting halos around the moon. Beauty can be a warning sign.',
  'Reefing before it looks necessary. Prudence is forecasting quiet reward.'
];
