name: Preview builds

on:
  push:
    branches: ['dev']

jobs:
  build_android:
    name: Build Android Preview
    type: build
    params:
      platform: android
      profile: preview

  build_ios:
    name: Build iOS Preview
    type: build
    params:
      platform: ios
      profile: preview
